// Code generated by go-swagger; DO NOT EDIT.

package v2stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ChangeImageReader is a Reader for the ChangeImage structure.
type ChangeImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewChangeImageDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewChangeImageDefault creates a ChangeImageDefault with default headers values
func NewChangeImageDefault(code int) *ChangeImageDefault {
	return &ChangeImageDefault{
		_statusCode: code,
	}
}

/*ChangeImageDefault handles this case with default header values.

successful operation
*/
type ChangeImageDefault struct {
	_statusCode int
}

// Code gets the status code for the change image default response
func (o *ChangeImageDefault) Code() int {
	return o._statusCode
}

func (o *ChangeImageDefault) Error() string {
	return fmt.Sprintf("[PUT /v2/stacks/changeImage/{name}][%d] changeImage default ", o._statusCode)
}

func (o *ChangeImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
