// Code generated by go-swagger; DO NOT EDIT.

package v2stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutstopStackV2Reader is a Reader for the PutstopStackV2 structure.
type PutstopStackV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutstopStackV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPutstopStackV2Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPutstopStackV2Default creates a PutstopStackV2Default with default headers values
func NewPutstopStackV2Default(code int) *PutstopStackV2Default {
	return &PutstopStackV2Default{
		_statusCode: code,
	}
}

/*PutstopStackV2Default handles this case with default header values.

successful operation
*/
type PutstopStackV2Default struct {
	_statusCode int
}

// Code gets the status code for the putstop stack v2 default response
func (o *PutstopStackV2Default) Code() int {
	return o._statusCode
}

func (o *PutstopStackV2Default) Error() string {
	return fmt.Sprintf("[PUT /v2/stacks/stop/{name}][%d] putstopStackV2 default ", o._statusCode)
}

func (o *PutstopStackV2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
