// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AttachedFreeIpaRequest attached free ipa request
// swagger:model AttachedFreeIpaRequest
type AttachedFreeIpaRequest struct {

	// Create freeipa in environment
	// Required: true
	Create *bool `json:"create"`
}

// Validate validates this attached free ipa request
func (m *AttachedFreeIpaRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AttachedFreeIpaRequest) validateCreate(formats strfmt.Registry) error {

	if err := validate.Required("create", "body", m.Create); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AttachedFreeIpaRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AttachedFreeIpaRequest) UnmarshalBinary(b []byte) error {
	var res AttachedFreeIpaRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
