export MAVEN_METADATA_URL = maven.sequenceiq.com/releases/com/sequenceiq/cloudbreak/maven-metadata.xml
export DOCKER_IMAGE = hortonworks/cloudbreak-mock-infrastructure

dockerhub-tag:
	./deploy.sh $(VERSION)