server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/infrastructure-mock.p12
    key-store-password: password
    key-alias: infrastructure-mock
  port: 10090
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    converters:
      preferred-json-mapper: gson
  resources:
      add-mappings: false
mock:
  experiences:
    liftie:
      createDummyCluster: false
    dwx:
      createDummyCluster: false
