// Code generated by go-swagger; DO NOT EDIT.

package v1imagecatalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPublicImageCatalogsByIDParams creates a new GetPublicImageCatalogsByIDParams object
// with the default values initialized.
func NewGetPublicImageCatalogsByIDParams() *GetPublicImageCatalogsByIDParams {
	var ()
	return &GetPublicImageCatalogsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicImageCatalogsByIDParamsWithTimeout creates a new GetPublicImageCatalogsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPublicImageCatalogsByIDParamsWithTimeout(timeout time.Duration) *GetPublicImageCatalogsByIDParams {
	var ()
	return &GetPublicImageCatalogsByIDParams{

		timeout: timeout,
	}
}

// NewGetPublicImageCatalogsByIDParamsWithContext creates a new GetPublicImageCatalogsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPublicImageCatalogsByIDParamsWithContext(ctx context.Context) *GetPublicImageCatalogsByIDParams {
	var ()
	return &GetPublicImageCatalogsByIDParams{

		Context: ctx,
	}
}

// NewGetPublicImageCatalogsByIDParamsWithHTTPClient creates a new GetPublicImageCatalogsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPublicImageCatalogsByIDParamsWithHTTPClient(client *http.Client) *GetPublicImageCatalogsByIDParams {
	var ()
	return &GetPublicImageCatalogsByIDParams{
		HTTPClient: client,
	}
}

/*GetPublicImageCatalogsByIDParams contains all the parameters to send to the API endpoint
for the get public image catalogs by Id operation typically these are written to a http.Request
*/
type GetPublicImageCatalogsByIDParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) WithTimeout(timeout time.Duration) *GetPublicImageCatalogsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) WithContext(ctx context.Context) *GetPublicImageCatalogsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) WithHTTPClient(client *http.Client) *GetPublicImageCatalogsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) WithName(name string) *GetPublicImageCatalogsByIDParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get public image catalogs by Id params
func (o *GetPublicImageCatalogsByIDParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicImageCatalogsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
