package com.sequenceiq.environment.environment;

public enum EnvironmentStatus {
    CREATION_INITIATED,
    DELETE_INITIATED,
    NETWORK_CREATION_IN_PROGRESS,
    NETWORK_DELETE_IN_PROGRESS,
    RDBMS_CREATION_IN_PROGRESS,
    RDBMS_DELETE_IN_PROGRESS,
    FREEIPA_CREATION_IN_PROGRESS,
    FREEIPA_DELETE_IN_PROGRESS,
    DETACH_CREDENTIAL_IN_PROGRESS,
    AVAILABLE,
    ARCHIVED,
    CORRUPTED
}
