// Code generated by go-swagger; DO NOT EDIT.

package v3_organization_id_proxyconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// CreateProxyconfigInOrganizationReader is a Reader for the CreateProxyconfigInOrganization structure.
type CreateProxyconfigInOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProxyconfigInOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateProxyconfigInOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateProxyconfigInOrganizationOK creates a CreateProxyconfigInOrganizationOK with default headers values
func NewCreateProxyconfigInOrganizationOK() *CreateProxyconfigInOrganizationOK {
	return &CreateProxyconfigInOrganizationOK{}
}

/*CreateProxyconfigInOrganizationOK handles this case with default header values.

successful operation
*/
type CreateProxyconfigInOrganizationOK struct {
	Payload *models_cloudbreak.ProxyConfigResponse
}

func (o *CreateProxyconfigInOrganizationOK) Error() string {
	return fmt.Sprintf("[POST /v3/{organizationId}/proxyconfigs][%d] createProxyconfigInOrganizationOK  %+v", 200, o.Payload)
}

func (o *CreateProxyconfigInOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_cloudbreak.ProxyConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
