// Code generated by go-swagger; DO NOT EDIT.

package v3_organization_id_proxyconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteProxyconfigInOrganizationParams creates a new DeleteProxyconfigInOrganizationParams object
// with the default values initialized.
func NewDeleteProxyconfigInOrganizationParams() *DeleteProxyconfigInOrganizationParams {
	var ()
	return &DeleteProxyconfigInOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProxyconfigInOrganizationParamsWithTimeout creates a new DeleteProxyconfigInOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteProxyconfigInOrganizationParamsWithTimeout(timeout time.Duration) *DeleteProxyconfigInOrganizationParams {
	var ()
	return &DeleteProxyconfigInOrganizationParams{

		timeout: timeout,
	}
}

// NewDeleteProxyconfigInOrganizationParamsWithContext creates a new DeleteProxyconfigInOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteProxyconfigInOrganizationParamsWithContext(ctx context.Context) *DeleteProxyconfigInOrganizationParams {
	var ()
	return &DeleteProxyconfigInOrganizationParams{

		Context: ctx,
	}
}

// NewDeleteProxyconfigInOrganizationParamsWithHTTPClient creates a new DeleteProxyconfigInOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteProxyconfigInOrganizationParamsWithHTTPClient(client *http.Client) *DeleteProxyconfigInOrganizationParams {
	var ()
	return &DeleteProxyconfigInOrganizationParams{
		HTTPClient: client,
	}
}

/*DeleteProxyconfigInOrganizationParams contains all the parameters to send to the API endpoint
for the delete proxyconfig in organization operation typically these are written to a http.Request
*/
type DeleteProxyconfigInOrganizationParams struct {

	/*Name*/
	Name string
	/*OrganizationID*/
	OrganizationID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) WithTimeout(timeout time.Duration) *DeleteProxyconfigInOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) WithContext(ctx context.Context) *DeleteProxyconfigInOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) WithHTTPClient(client *http.Client) *DeleteProxyconfigInOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) WithName(name string) *DeleteProxyconfigInOrganizationParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) SetName(name string) {
	o.Name = name
}

// WithOrganizationID adds the organizationID to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) WithOrganizationID(organizationID int64) *DeleteProxyconfigInOrganizationParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete proxyconfig in organization params
func (o *DeleteProxyconfigInOrganizationParams) SetOrganizationID(organizationID int64) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProxyconfigInOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", swag.FormatInt64(o.OrganizationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
