// Code generated by go-swagger; DO NOT EDIT.

package v1flexsubscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutPublicUsedForControllerFlexSubscriptionByNameParams creates a new PutPublicUsedForControllerFlexSubscriptionByNameParams object
// with the default values initialized.
func NewPutPublicUsedForControllerFlexSubscriptionByNameParams() *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	var ()
	return &PutPublicUsedForControllerFlexSubscriptionByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutPublicUsedForControllerFlexSubscriptionByNameParamsWithTimeout creates a new PutPublicUsedForControllerFlexSubscriptionByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutPublicUsedForControllerFlexSubscriptionByNameParamsWithTimeout(timeout time.Duration) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	var ()
	return &PutPublicUsedForControllerFlexSubscriptionByNameParams{

		timeout: timeout,
	}
}

// NewPutPublicUsedForControllerFlexSubscriptionByNameParamsWithContext creates a new PutPublicUsedForControllerFlexSubscriptionByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutPublicUsedForControllerFlexSubscriptionByNameParamsWithContext(ctx context.Context) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	var ()
	return &PutPublicUsedForControllerFlexSubscriptionByNameParams{

		Context: ctx,
	}
}

// NewPutPublicUsedForControllerFlexSubscriptionByNameParamsWithHTTPClient creates a new PutPublicUsedForControllerFlexSubscriptionByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutPublicUsedForControllerFlexSubscriptionByNameParamsWithHTTPClient(client *http.Client) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	var ()
	return &PutPublicUsedForControllerFlexSubscriptionByNameParams{
		HTTPClient: client,
	}
}

/*PutPublicUsedForControllerFlexSubscriptionByNameParams contains all the parameters to send to the API endpoint
for the put public used for controller flex subscription by name operation typically these are written to a http.Request
*/
type PutPublicUsedForControllerFlexSubscriptionByNameParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) WithTimeout(timeout time.Duration) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) WithContext(ctx context.Context) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) WithHTTPClient(client *http.Client) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) WithName(name string) *PutPublicUsedForControllerFlexSubscriptionByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put public used for controller flex subscription by name params
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutPublicUsedForControllerFlexSubscriptionByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
