package sssd

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteSssdParams creates a new DeleteSssdParams object
// with the default values initialized.
func NewDeleteSssdParams() *DeleteSssdParams {
	var ()
	return &DeleteSssdParams{}
}

/*DeleteSssdParams contains all the parameters to send to the API endpoint
for the delete sssd operation typically these are written to a http.Request
*/
type DeleteSssdParams struct {

	/*ID*/
	ID int64
}

// WithID adds the id to the delete sssd params
func (o *DeleteSssdParams) WithID(id int64) *DeleteSssdParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSssdParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
