package sssd

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSssdAccountNameParams creates a new GetSssdAccountNameParams object
// with the default values initialized.
func NewGetSssdAccountNameParams() *GetSssdAccountNameParams {
	var ()
	return &GetSssdAccountNameParams{}
}

/*GetSssdAccountNameParams contains all the parameters to send to the API endpoint
for the get sssd account name operation typically these are written to a http.Request
*/
type GetSssdAccountNameParams struct {

	/*Name*/
	Name string
}

// WithName adds the name to the get sssd account name params
func (o *GetSssdAccountNameParams) WithName(name string) *GetSssdAccountNameParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSssdAccountNameParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
