// Code generated by go-swagger; DO NOT EDIT.

package v1proxyconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPublicProxyConfigParams creates a new GetPublicProxyConfigParams object
// with the default values initialized.
func NewGetPublicProxyConfigParams() *GetPublicProxyConfigParams {
	var ()
	return &GetPublicProxyConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPublicProxyConfigParamsWithTimeout creates a new GetPublicProxyConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPublicProxyConfigParamsWithTimeout(timeout time.Duration) *GetPublicProxyConfigParams {
	var ()
	return &GetPublicProxyConfigParams{

		timeout: timeout,
	}
}

// NewGetPublicProxyConfigParamsWithContext creates a new GetPublicProxyConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPublicProxyConfigParamsWithContext(ctx context.Context) *GetPublicProxyConfigParams {
	var ()
	return &GetPublicProxyConfigParams{

		Context: ctx,
	}
}

// NewGetPublicProxyConfigParamsWithHTTPClient creates a new GetPublicProxyConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPublicProxyConfigParamsWithHTTPClient(client *http.Client) *GetPublicProxyConfigParams {
	var ()
	return &GetPublicProxyConfigParams{
		HTTPClient: client,
	}
}

/*GetPublicProxyConfigParams contains all the parameters to send to the API endpoint
for the get public proxy config operation typically these are written to a http.Request
*/
type GetPublicProxyConfigParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get public proxy config params
func (o *GetPublicProxyConfigParams) WithTimeout(timeout time.Duration) *GetPublicProxyConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get public proxy config params
func (o *GetPublicProxyConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get public proxy config params
func (o *GetPublicProxyConfigParams) WithContext(ctx context.Context) *GetPublicProxyConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get public proxy config params
func (o *GetPublicProxyConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get public proxy config params
func (o *GetPublicProxyConfigParams) WithHTTPClient(client *http.Client) *GetPublicProxyConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get public proxy config params
func (o *GetPublicProxyConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get public proxy config params
func (o *GetPublicProxyConfigParams) WithName(name string) *GetPublicProxyConfigParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get public proxy config params
func (o *GetPublicProxyConfigParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicProxyConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
