package com.sequenceiq.cloudbreak.api.endpoint.v4.stacks.base;

public enum InstanceStatus {
    REQUESTED, CREATED, UNREGISTERED, REGISTERED, DECOMMISSIONED, TERMINATED, DELETED_ON_PROVIDER_SIDE, FAILED, STOPPED, ORCHESTRATION_FAILED,
    DECOMMISSION_FAILED
}
