package com.sequenceiq.distrox.api.v1.distrox.model.cluster.kraft;

public enum KraftMigrationOperationStatus {
    NOT_APPLICABLE,
    ZOOKEEPER_TO_KRAFT_MIGRATION_TRIGGERABLE,
    INSTALLING_KRAFT_SERVICE_FOR_MIGRATION_IN_PROGRESS,
    ZOOKEEPER_TO_KRAFT_MIGRATION_IN_PROGRESS,
    ZOOKEEPER_TO_KRAFT_MIGRATION_COMPLETE,
    ZOOKEEPER_TO_KRAFT_MIGRATION_FAILED,
    FINALIZE_ZOOKEEPER_TO_KRAFT_MIGRATION_IN_PROGRESS,
    FINALIZE_ZOOKEEPER_TO_KRAFT_MIGRATION_COMPLETE,
    FINALIZE_ZOOKEEPER_TO_KRAFT_MIGRATION_FAILED,
    ROLLBACK_ZOOKEEPER_TO_KRAFT_MIGRATION_IN_PROGRESS,
    ROLLBACK_ZOOKEEPER_TO_KRAFT_MIGRATION_COMPLETE,
    ROLLBACK_ZOOKEEPER_TO_KRAFT_MIGRATION_FAILED;
}
