# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
  - package-ecosystem: "gradle" # Daily security-updates only for npm versions on the release branch
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "CB-2.85.0"
    labels:
      - "security-update"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      security-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        applies-to: security-updates # Applies the group rule to version updates
        patterns:
          - "*"
