// Code generated by go-swagger; DO NOT EDIT.

package v1rdsconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePrivateRdsReader is a Reader for the DeletePrivateRds structure.
type DeletePrivateRdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePrivateRdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeletePrivateRdsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeletePrivateRdsDefault creates a DeletePrivateRdsDefault with default headers values
func NewDeletePrivateRdsDefault(code int) *DeletePrivateRdsDefault {
	return &DeletePrivateRdsDefault{
		_statusCode: code,
	}
}

/*DeletePrivateRdsDefault handles this case with default header values.

successful operation
*/
type DeletePrivateRdsDefault struct {
	_statusCode int
}

// Code gets the status code for the delete private rds default response
func (o *DeletePrivateRdsDefault) Code() int {
	return o._statusCode
}

func (o *DeletePrivateRdsDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/rdsconfigs/user/{name}][%d] deletePrivateRds default ", o._statusCode)
}

func (o *DeletePrivateRdsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
