// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDatabaseInWorkspaceParams creates a new DeleteDatabaseInWorkspaceParams object
// with the default values initialized.
func NewDeleteDatabaseInWorkspaceParams() *DeleteDatabaseInWorkspaceParams {
	var ()
	return &DeleteDatabaseInWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDatabaseInWorkspaceParamsWithTimeout creates a new DeleteDatabaseInWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDatabaseInWorkspaceParamsWithTimeout(timeout time.Duration) *DeleteDatabaseInWorkspaceParams {
	var ()
	return &DeleteDatabaseInWorkspaceParams{

		timeout: timeout,
	}
}

// NewDeleteDatabaseInWorkspaceParamsWithContext creates a new DeleteDatabaseInWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDatabaseInWorkspaceParamsWithContext(ctx context.Context) *DeleteDatabaseInWorkspaceParams {
	var ()
	return &DeleteDatabaseInWorkspaceParams{

		Context: ctx,
	}
}

// NewDeleteDatabaseInWorkspaceParamsWithHTTPClient creates a new DeleteDatabaseInWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDatabaseInWorkspaceParamsWithHTTPClient(client *http.Client) *DeleteDatabaseInWorkspaceParams {
	var ()
	return &DeleteDatabaseInWorkspaceParams{
		HTTPClient: client,
	}
}

/*DeleteDatabaseInWorkspaceParams contains all the parameters to send to the API endpoint
for the delete database in workspace operation typically these are written to a http.Request
*/
type DeleteDatabaseInWorkspaceParams struct {

	/*Name*/
	Name string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) WithTimeout(timeout time.Duration) *DeleteDatabaseInWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) WithContext(ctx context.Context) *DeleteDatabaseInWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) WithHTTPClient(client *http.Client) *DeleteDatabaseInWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) WithName(name string) *DeleteDatabaseInWorkspaceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) SetName(name string) {
	o.Name = name
}

// WithWorkspaceID adds the workspaceID to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) WithWorkspaceID(workspaceID int64) *DeleteDatabaseInWorkspaceParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the delete database in workspace params
func (o *DeleteDatabaseInWorkspaceParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDatabaseInWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
