version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 7
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 40
  method-lines:
    config:
      threshold: 40
  file-lines:
    config:
      threshold: 400
exclude_patterns:
- "**/mock/"
- "**/test/"
- "**/*Test.java"
- "**/*Tests.java"
- "**/*Converter.java"
