FORMAT: 1A
HOST: http://apidocs.sequenceiq.com/stackbreak

# cloudbreak
*Cloudbreak is a powerful left surf that breaks over a coral reef, a mile off southwest the island of Tavarua, Fiji.*

*Cloudbreak is a cloud agnostic Hadoop as a Service API. Abstracts the provisioning and ease management and monitoring of on-demand clusters.*

Cloudbreak is a RESTful application development platform with the goal of helping developers to build solutions for deploying Hadoop YARN clusters in different environments. Once it is deployed in your favorite servlet container it exposes a REST API allowing to span up Hadoop clusters of arbitary sizes and cloud providers. Provisioning Hadoop has never been easier.
Cloudbreak is built on the foundation of cloud providers API (Amazon AWS, Microsoft Azure), Apache Ambari, Docker lightweight containers, Serf and dnsmasq. 


##Benefits

###Secure
It supports a token based and OAuth2 authentication model. The cluster is provisioned in a logically isolated network (Virtual Private Cloud) of your cloud favorite cloud provider.
If the cluster is launched in a VPC network, the framework gonfigure firewall settings that control the network access of your launched instances. For example a Hadoop Resource Manager can be accessed from the internet, whereas non of the other nodes are available.
Cloudbreak does not store or manages your cloud credentials - it is the end user's responsability to link Cloudbreak with her/his cloud account. We provide utilities to ease this process (IAM on Amazon, certificates on Azure).

###Elastic
Using Cloudbreak API you can provision an arbitrary number of Hadoop nodes - the API does the hard work for you, and span up the cluster, configure the networks and the selected Hadoop services without any interaction. 
POST once and use it anytime after.

###Scalable
As your workload changes, the API allows you to add or remove nodes on the fly. Cloudbreak does the hard work of reconfiguring the infrastructure, provision or decomission Hadoop nodes and let the cluster be continuosely operational. 
Once provisioned, new nodes will take up the load and increase the cluster throughput.

###Blueprints
Supports different Hadoop cluster blueprints. Hostgroups defined in blueprints can be associated to different VPC subnets and availability zones, thus you can span up a cluster for deploying highly available applications.

###Flexible
You have the option to choose your favorite cloud provider and different pricing models. The API translated the calls towards different cloud vendors - you develop and use one common API, no need to rewrite you code when changing between cloud providers.


# Group User authentication
Authentication related resources of the **Cloudbreak API**.

The API supports token based and OAuth2 authentication. 
All operations against a REST resource must be authenticated.

## Authentication [/authenticate]
### Authenticates a user [POST]
After successful authentication the call will return with an authentication token, and the user role. The token invalidates with the HTTP session or with the expiration of OAuth2 token. 

+ Request (application/json)

        {
            "username": "mick.fanning@surf.com",
            "password": "magicseaweed"
        }

+ Response 200 (application/json)

        {
            "token": "user:c45sdfdsfo234jgkhsdgf324",
            "roles": {
                "ROLE_COMPANY_ADMIN": true,
                "ROLE_COMPANY_USER ": true
            },
            "name": "mick.fanning@surf.com"
        }

# Group User management
User management related resources of the **Cloudbreak API**.

These calls require *COMPANY_ADMIN* roles. A company administrator is the user who registers the company.
Currently there are two user roles supported: regular users as  *COMPANY_USER* and admin users as *COMPANY_ADMIN*.

## User management [/users]
### Creates a new user [POST]
Creates a new user with the specified username/password and role.

+ Request (application/json)

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

    + Body

            {
                "username": "kelly.slater@surf.com",
                "password": "magicseaweed",
                "userRole": {COMPANY_ADMIN, COMPANY_USER}
            }

+ Response 200 (application/json)

        {
            "id": "user-2"
        }

### List all users [GET]
Users in *COMPANY_ADMIN* role can retrieve all users belonging to the company. 
The information contains generic user info, cloud and Hadoop cluster configurations belonging to the particular user.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324


+ Response 200 (application/json)

        [
            {
               TBD
            }
        ]

## User informations [/me]
Retrieve informations about the authenticated 

### Retrieve a user config [GET]
The information contains generic user info, cloud and Hadoop cluster configurations belonging to the particular user.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            {
               TBD
            }
        }



# Group Cloud authentication
Cloud Authentication related resources of the **Cloudbreak API**.
Adds an AWS IAM role ARN or Azure JKS to user's account.


## Associate a cloud credential to user [/credential]
### Associate credential [POST]
Adds an AWS IAM role ARN or the user's account.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body

            {
                "cloudPlatform": “AWS",
                "parameters": {
                    “roleArn": “arn:aws:iam::755047400000:role/seq-self-cf"
                }
            }


    + Response 201 (application/json)
    
            {
                
            }

## Associate a cloud credential to user [/credential]
### Associate credential [POST]
Adds a Azure JKS the user's account.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
    + Body

            {
                "cloudPlatform": "AZURE",
                "parameters": {
                    "subscriptionId": "1234-5678-1234-5678",
                    "jksPassword": "pw123"
                }
            }

    + Response 201 (application/json)
    
            {
                
            }
            
            
##Retrieves the cloud credentials of a user [/credential]
### Retrieve credentials [GET]
Retrieve all the associated cloud credentials of a user

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

          {
            "cloudPlatform": “AWS",
            "parameters": {
                “roleArn": “arn:aws:iam::755047400000:role/seq-self-cf"
            }
          },
          {
            "cloudPlatform": "AZURE",
            "parameters": {
                "subscriptionId": "1234-5678-1234-5678",
                "jksPassword": "pw123"
            }
         }
        
##Retrieves the cloud credential configuration of a user [/credential/{id}]
### Retrieve the user's JKS file [GET]
Retrieves the Azure cloud JKS file associated with the user account
+ Parameters
    + id (required String `azure-credential-id`) ... The identifier of the Azure `credential`.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
        }


##Deletes the associated cloud credential from the user account [/credential/{id}]
### Deletes the associated credential[DELETE]
Retrieves the Azure cloud JKS file associated with the user account
+ Parameters
    + id (required String `azure-credential-id`) ... The identifier of the Azure `credential`.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
        }
        

# Group Infrastructure configuration
Infrastructure  related resources of the **Cloudbreak API**.
Creates an AWS CloudFormation  or an Azure stack. Allows configurations of VPC, subnet, internet gateway, route table, securityGroups, ACLs, instances. 

## Creates the AWS infrastructure [/template]
### Create infrastructure [POST]
Creates an AWS CloudFormation stack (vpc, subnet, internetGateway, routeTable, securityGroups, ACLs, instances)

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body

           {
              "cloudPlatform": "AWS",
              “name": “my-template-1",
              "parameters": {
                "sshLocation”: “0.0.0.0/0"
                "region": "eu-west-1",
                "keyName": "sequence-eu", 
                "instanceType": “m3.xlarge",
                “amiId”: “ami-12345678"
              }
            }

    + Response 200 (application/json)
    
            {
                "infraId": "aws-infra-id"
            }


## Creates and infrastructure on Azure [/template]
### Create infrastructure [POST]
Creates an Azure infrastructure stack (vpc, subnet, instances)

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body

        {
          "cloudPlatform": "AZURE",
          “name": "my-azure-cluster",
          "parameters": {
            "location": "NORTH_EUROPE",
            "description": "my-azure-cluster description",
            "addressPrefix": "172.16.0.0/16",
            "subnetAddressPrefix": "172.16.0.0/24",
            "deploymentSlot": "production",
            "imageName": "c290a6b031d841e09f2da759bbabe71f__Oracle-Linux-6",
            "username": "ricsiuser",
            "password": "Password!@#$",
            "disableSshPasswordAuthentication": "true",
            "vmType": "Small"
          }
        }


    + Response 200 (application/json)
    
            {
                "infraId": "azure-infra-id"
            }

## Retrieves al the created infrastructures of a user [/template]
### List infrastructures [GET]
Describes the cloud infrastructures belonging to the user

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
    + Body

            {
            
            }

    + Response 200 (application/json)
    
            {
              "cloudPlatform": "AWS",
              “name": “my-template-1",
              "parameters": {
                "sshLocation”: “0.0.0.0/0"
                "region": "eu-west-1",
                "keyName": "sequence-eu",
                "instanceType": “m3.xlarge"
                “amiId”: “ami-12345678"
              }
            },{
              "cloudPlatform": "AZURE",
              “name": "my-azure-cluster",
              "parameters": {
                "location": "NORTH_EUROPE",
                "description": "my-azure-cluster description",
                "addressPrefix": "172.16.0.0/16",
                "subnetAddressPrefix": "172.16.0.0/24",
                "deploymentSlot": "production",
                "imageName": "c290a6b031d841e09f2da759bbabe71f__Oracle-Linux-6",
                "username": "ricsiuser",
                "password": "Password!@#$",
                "disableSshPasswordAuthentication": "true",
                "vmType": "Small"
              }
        

##Describe the infrastructure [/template/{id}]
### Retrieve one particulat AWS or Azure infrastructure by id [GET]
Retrieves the AWS or Azure infrastructure by submitting the infrastcuture ID
+ Parameters
    + id (required String `aws-infrastructure-id`) ... The identifier of the Azure `credential`.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
            "id":"stack-123",
            {
              "cloudPlatform": "AWS",
              “name": “my-template-1",
              "parameters": {
                "sshLocation”: “0.0.0.0/0"
                "region": "eu-west-1",
                "keyName": "sequence-eu",
                "instanceType": “m3.xlarge"
                “amiId”: “ami-12345678"
              }
        }


##Deletes the specified infrastructure from the database [/template/{id}]
### Deletes the infrastructure[DELETE]
Deletes the specified infrastructure stack from the database, unless there is a cloud instance created from this stack.
+ Parameters
    + id (required String `aws-infrastructure-id`) ... The identifier of the Azure `credential`.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
        }
  
# Group Cloud instances
Cloud  related resources of the **Cloudbreak API**.
Creates an AWS or Azure cloud based on the infrastructure stack. Launches the specified number of instances in the selected infrastructure.
## Creates the AWS or Azure cloud [/stack]
### Create infrastructure [POST]
Creates an AWS CloudFormation or Azure cloud from the template stack.
+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body

            {
                "name": "my-cloud-1",
                "clusterSize": 3,
                "templateId": "1"
            }

    + Response 200 (application/json)
    
            {
                "infraId": "aws-infra-id"
            }


## Retrieves all the clouds of a user [/stack]
### List infrastructures [GET]
Describes the clouds belonging to the user

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
    + Body

            {
            
            }

    + Response 200 (application/json)
    
        {
          "nodeCount": 2,
          "templateId": "1",
          "cloudPlatform": "AWS",
          "name": "stack-123",
          "status": "CREATED",
          "creationTime": "2010-07-27T22:28:28Z",
          "ambarServerIP": "ambari.server.ip",
          "stackDescription": {
                "resources": {
                "stackResources": [
                {
                  "description": null,
                  "stackName": "coreos",
                  "stackId": "arn:aws:cloudformation:eu-west-1:755047402263:stack/coreos/fa71a930-e16b-11e3-8185-50014118ec7c",
                  "logicalResourceId": "CoreOSELB",
                  "physicalResourceId": "coreos-CoreOSELB-EIJBBQ9335MT",
                  "resourceType": "AWS::ElasticLoadBalancing::LoadBalancer",
                  "timestamp": 1400733975000,
                  "resourceStatus": "CREATE_COMPLETE",
                  "resourceStatusReason": null
                },
                {
                  "description": null,
                  "stackName": "coreos",
                  "stackId": "arn:aws:cloudformation:eu-west-1:755047402263:stack/coreos/fa71a930-e16b-11e3-8185-50014118ec7c",
                  "logicalResourceId": "CoreOSUser",
                  "physicalResourceId": "coreos-CoreOSUser-1W69DK6OLLTXZ",
                  "resourceType": "AWS::IAM::User",
                  "timestamp": 1400733980000,
                  "resourceStatus": "CREATE_COMPLETE",
                  "resourceStatusReason": null
                }
              ]
            },
            "stack": {
              "nextToken": null,
              "stacks": [
                {
                  "tags": [
                    {
                      "value": "coreos",
                      "key": "Name"
                    }
                  ],
                  "capabilities": [
                    "CAPABILITY_IAM"
                  ],
                  "timeoutInMinutes": null,
                  "notificationARNs": [],
                  "disableRollback": false,
                  "stackId": "arn:aws:cloudformation:eu-west-1:755047402263:stack/coreos/fa71a930-e16b-11e3-8185-50014118ec7c",
                  "stackName": "coreos",
                  "description": "CoreOS stack",
                  "parameters": [
                    {
                      "parameterValue": "sequence-eu",
                      "parameterKey": "KeyPair"
                    },
                    {
                      "parameterValue": "0.0.0.0/0",
                      "parameterKey": "AllowSSHFrom"
                    }
                  ]
                }
              ]
            }
          }
        }
          
##Describe the cloud [/stack/{id}]
### Retrieve one particulat AWS or Azure infrastructure by id [GET]
Retrieves the AWS or Azure infrastructure by submitting the infrastcuture ID
+ Parameters
    + id (required String `aws-infrastructure-id`) ... The identifier of the Azure `credential`.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

     {
          "nodeCount": 2,
          "templateId": "1",
          "cloudPlatform": "AWS",
          "name": "stack-123",
          "status": "CREATED",
          "creationTime": "2010-07-27T22:28:28Z",
          "ambarServerIP": "ambari.server.ip",
          "stackDescription": {
            "resources": {
              "stackResources": [
                {
                  "description": null,
                  "stackName": "coreos",
                  "stackId": "arn:aws:cloudformation:eu-west-1:755047402263:stack/coreos/fa71a930-e16b-11e3-8185-50014118ec7c",
                  "logicalResourceId": "CoreOSELB",
                  "physicalResourceId": "coreos-CoreOSELB-EIJBBQ9335MT",
                  "resourceType": "AWS::ElasticLoadBalancing::LoadBalancer",
                  "timestamp": 1400733975000,
                  "resourceStatus": "CREATE_COMPLETE",
                  "resourceStatusReason": null
                },
                {
                  "description": null,
                  "stackName": "coreos",
                  "stackId": "arn:aws:cloudformation:eu-west-1:755047402263:stack/coreos/fa71a930-e16b-11e3-8185-50014118ec7c",
                  "logicalResourceId": "CoreOSUser",
                  "physicalResourceId": "coreos-CoreOSUser-1W69DK6OLLTXZ",
                  "resourceType": "AWS::IAM::User",
                  "timestamp": 1400733980000,
                  "resourceStatus": "CREATE_COMPLETE",
                  "resourceStatusReason": null
                }
              ]
            },
            "stack": {
              "nextToken": null,
              "stacks": [
                {
                  "tags": [
                    {
                      "value": "coreos",
                      "key": "Name"
                    }
                  ],
                  "capabilities": [
                    "CAPABILITY_IAM"
                  ],
                  "timeoutInMinutes": null,
                  "notificationARNs": [],
                  "disableRollback": false,
                  "stackId": "arn:aws:cloudformation:eu-west-1:755047402263:stack/coreos/fa71a930-e16b-11e3-8185-50014118ec7c",
                  "stackName": "coreos",
                  "description": "CoreOS stack",
                  "parameters": [
                    {
                      "parameterValue": "sequence-eu",
                      "parameterKey": "KeyPair"
                    },
                    {
                      "parameterValue": "0.0.0.0/0",
                      "parameterKey": "AllowSSHFrom"
                    }
                  ]
                }
              ]
            }
          }
        }


##Deletes the specified cloud [/stack/{id}]
### Deletes the cloud [DELETE]
Deletes the specified cloud from the Amazon on Azure cloud
WARNING: All data will be lost - unless there was no storage configured. It is the user's responsibilty to backup data or take snapshots uning the cloud interface.
+ Parameters
    + id (required String `aws-cloud-id`) ... The identifier of the Azure `credential`.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
        }      
        
# Group Hadoop stack configuration
Hadoop stack  related resources of the **Cloudbreak API**.

Creates a Hadoop cluster stack. Allows configurations of different stacks (blueprints) to be used later to create cluster instances.


## Creates a Hadoop stack [/blueprint]
### Create stack [POST]
Creates a Hadoop stack based on the blueprint. The blueprint specifies the Hadoop services, and other Hadoop specific configurations. 
The cardinality specifies the desired number of nodes for the hostgroup. When the cluster is created these number can be overrided.
+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body
    
    {
          "name": "multi-node-hdfs-yarn",
          "blueprint": {
            "Blueprints": {
              "blueprint_name": "multi-node-hdfs-yarn",
              "stack_name": "HDP",
              "stack_version": "2.0"
            },
            "hostGroups": [
              {
                "name": "master",
                "components": [
                  {
                    "name": "NAMENODE"
                  },
                  {
                    "name": "SECONDARY_NAMENODE"
                  },
                  {
                    "name": "RESOURCEMANAGER"
                  },
                  {
                    "name": "HISTORYSERVER"
                  },
                  {
                    "name": "NAGIOS_SERVER"
                  },
                  {
                    "name": "ZOOKEEPER_SERVER"
                  }
                ],
                "cardinality": "1"
              },
              {
                "name": "slaves",
                "components": [
                  {
                    "name": "DATANODE"
                  },
                  {
                    "name": "HDFS_CLIENT"
                  },
                  {
                    "name": "NODEMANAGER"
                  },
                  {
                    "name": "YARN_CLIENT"
                  },
                  {
                    "name": "MAPREDUCE2_CLIENT"
                  },
                  {
                    "name": "ZOOKEEPER_CLIENT"
                  }
                ],
                "cardinality": "2"
              }
            ]
          }
        }

           
    + Response 200 (application/json)
    
            {
                
            }

## Creates a Hadoop stack [/blueprint]
### Create stack [POST]
Creates a Hadoop stack. The blueprint specifies the Hadoop services and other Hadoop specific configurations. 
The blueprint is available behind a URL. The cardinality specifies the desired number of nodes for the hostgroup. When the cluster is created these number can be overrided.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body

        {
          “name": “multi-node-hdfs-yarn",
          “blueprintUrl”: “http://url.com/blueprint.json”
        }

    + Response 200 (application/json)
    
            {
                
            }


## Retrieves al the created Hadoop  stacks [/blueprint]
### List stacks [GET]
Retrieve all Hadoop cluster stack

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
    + Body

            {
            
            }

    + Response 200 (application/json)
    
            {
                "stackName": "my-ambari-cluster-1",
                "blueprintBody": {
                "host_groups" : [
                      {
                        "name" : "master",
                        "components" : [
                            {
                              "name" : "NAMENODE"
                            },
                            {
                              "name" : "SECONDARY_NAMENODE"
                            },
                            {
                              "name" : "RESOURCEMANAGER"
                            },
                            {
                              "name" : "HISTORYSERVER"
                            },
                            {
                              "name" : "NAGIOS_SERVER"
                            },
                            {
                              "name" : "ZOOKEEPER_SERVER"
                            }
                        ],
                        "cardinality" : "1"
                      },
                      {
                        "name" : "slaves",
                        "components" : [
                            {
                              "name" : "DATANODE"
                            },
                            {
                              "name" : "HDFS_CLIENT"
                            },
                            {
                              "name" : "NODEMANAGER"
                            },
                            {
                              "name" : "YARN_CLIENT"
                            },
                            {
                              "name" : "MAPREDUCE2_CLIENT"
                            },
                            {
                              "name" : "ZOOKEEPER_CLIENT"
                            }
                            ],
                            "cardinality" : "2"
                      }
                    ],
                    "Blueprints" : {
                      "blueprint_name" : "multi-node-hdfs-yarn",
                      "stack_name" : "HDP",
                      "stack_version" : "2.0"
                    }
                  }
            
            }
            

        
##Describe one Hadoop stack  [/blueprint/{id}]
### Retrieve one particulat Hadoop cluster stack [GET]
Retrieves one particulat Hadoop cluster stacj by submitting the stack id.
+ Parameters
    + id (required String `stack-id`) ... The identifier of the stack id.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
                "stackName": "my-ambari-cluster-1",
                "blueprintBody": {
                "host_groups" : [
                      {
                        "name" : "master",
                        "components" : [
                            {
                              "name" : "NAMENODE"
                            },
                            {
                              "name" : "SECONDARY_NAMENODE"
                            },
                            {
                              "name" : "RESOURCEMANAGER"
                            },
                            {
                              "name" : "HISTORYSERVER"
                            },
                            {
                              "name" : "NAGIOS_SERVER"
                            },
                            {
                              "name" : "ZOOKEEPER_SERVER"
                            }
                        ],
                        "cardinality" : "1"
                      },
                      {
                        "name" : "slaves",
                        "components" : [
                            {
                              "name" : "DATANODE"
                            },
                            {
                              "name" : "HDFS_CLIENT"
                            },
                            {
                              "name" : "NODEMANAGER"
                            },
                            {
                              "name" : "YARN_CLIENT"
                            },
                            {
                              "name" : "MAPREDUCE2_CLIENT"
                            },
                            {
                              "name" : "ZOOKEEPER_CLIENT"
                            }
                            ],
                            "cardinality" : "2"
                      }
                    ],
                    "Blueprints" : {
                      "blueprint_name" : "multi-node-hdfs-yarn",
                      "stack_name" : "HDP",
                      "stack_version" : "2.0"
                    }
                  }
            }


##Deletes the specified stack from database [/blueprint/{id}]
### Deletes the stack[DELETE]
WARNING: Deletes the specified infrastructure from the cloud and all associated resources (VPC, subnet, internetGateway, routeTable, securityGroups, ACLs, instances)

+ Parameters
    + id (required String `stacj-id`) ... The identifier of the stack.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
        }
        
        
# Group Hadoop cluster instances
Hadoop cluster related resources of the **Cloudbreak API**.

Creates a Hadoop cluster from the given stack.

## Creates a Hadoop stack [/cluster]
### Create infrastructure [POST]
Creates a Hadoop cluster based on the stack. The stack specifies the Hadoop services, the number of hosts in the hostgroup and other Hadoop specific configurations. 
Number of hosts in hostgroups can be overridean at cluster creation time.
+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
        
    + Body

         {
          "clusterName": "my-cluster",
          "blueprintName": "multi-node-hdfs-yarn",
          "hostGroups": [
            {
              "name": "master",
              "cardinality": 1
            },
            {
              "name": "slave",
              "cardinality": 3
            }
          ]
        }

    + Response 200 (application/json)
    
            {
                
            }



## Retrieves al the created Hadoop clusters from a stack [/cluster]
### List clusters [GET]
Retrieve all Hadoop clusters

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324
            
    + Body

            {
            
            }

    + Response 200 (application/json)

    {
      "cluster": {
        "configurations": [
          {
            "Config": {
              "cluster_name": "MySingleNodeCluster2"
            },
            "type": "capacity-scheduler",
            "tag": "1",
            "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2/configurations?type=capacity-scheduler&tag=1"
          },
          {
            "Config": {
              "cluster_name": "MySingleNodeCluster2"
            },
            "type": "core-site",
            "tag": "1",
            "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2/configurations?type=core-site&tag=1"
          }
        ],
        "hosts": [
          {
            "Hosts": {
              "host_name": "server.ambari.com",
              "cluster_name": "MySingleNodeCluster2"
            },
            "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2/hosts/server.ambari.com"
          }
        ],
        "workflows": [],
        "config_groups": [],
        "services": [
          {
            "ServiceInfo": {
              "service_name": "GANGLIA",
              "cluster_name": "MySingleNodeCluster2"
            },
            "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2/services/GANGLIA"
          },
          {
            "ServiceInfo": {
              "service_name": "HDFS",
              "cluster_name": "MySingleNodeCluster2"
            },
            "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2/services/HDFS"
          }
        ],
        "requests": [
          {
            "Requests": {
              "id": 1,
              "cluster_name": "MySingleNodeCluster2"
            },
            "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2/requests/1"
          }
        ],
        "Clusters": {
          "desired_configs": {
            "zookeeper-log4j": {
              "tag": "1",
              "user": "admin"
            },
            "yarn-site": {
              "tag": "1",
              "user": "admin"
            }
          },
          "version": "HDP-2.1",
          "cluster_name": "MySingleNodeCluster2",
          "cluster_id": 3
        },
        "href": "http://172.17.0.2:8080/api/v1/clusters/MySingleNodeCluster2"
      }
    }
                

        
##Describe one Hadoop cluster  [/cluster/{id}]
### Retrieve one particulat Hadoop cluster configuration [GET]
Retrieves one particulat Hadoop cluster configuration by submitting the cluster id
+ Parameters
    + id (required String `cluster-id`) ... The identifier of the Hadoop cluster

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
                "clusterName": "my-hadoop-cluster-1",
                "stackId":"my-hadoop-stack-1"
                "host_groups" : [
                      {
                        "name" : "master",
                        "cardinality" : "1"
                      },
                      {
                        "name" : "slaves",
                        "cardinality" : "2"
                      }
                    ]
            }


##Deletes the specified Hadoop cluster [/cluster/{id}]
### Deletes the cluster[DELETE]
WARNING: Deletes the cluster - all data in HDFS will be lost. The cluster is destroyed.

+ Parameters
    + id (required String `cluster-id`) ... The identifier of the cluster.

+ Request

    + Headers

            x-auth-token: user:c45sdfdsfo234jgkhsdgf324

+ Response 200 (application/json)

        {
            
        }