package main

import (
	"log"
	"fmt"

	"github.com/sequenceiq/hdc-cli/client/blueprints"

	apiclient "github.com/sequenceiq/hdc-cli/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"
)

func main() {

	// create the API client
	client := apiclient.DefaultOAuth2

	bearerTokenAuth := httptransport.BearerToken("eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI0NWI0ZGU2NS1iOWI1LTRjYzEtODYyMi02Yjg5MzQ5MjczZjQiLCJzdWIiOiI3OWE2ZjYzOS01MDYxLTQ2OTYtODRiNS1hMGYyNWRjZTFmMzEiLCJzY29wZSI6WyJjbG91ZGJyZWFrLm5ldHdvcmtzLnJlYWQiLCJjbG91ZGJyZWFrLnVzYWdlcy51c2VyIiwiY2xvdWRicmVhay5yZWNpcGVzIiwiY2xvdWRicmVhay51c2FnZXMuZ2xvYmFsIiwib3BlbmlkIiwiY2xvdWRicmVhay5wbGF0Zm9ybXMiLCJjbG91ZGJyZWFrLnRlbXBsYXRlcy5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJjbG91ZGJyZWFrLnVzYWdlcy5hY2NvdW50IiwiY2xvdWRicmVhay5ldmVudHMiLCJjbG91ZGJyZWFrLnN0YWNrcy5yZWFkIiwiY2xvdWRicmVhay5ibHVlcHJpbnRzIiwiY2xvdWRicmVhay5zc3NkY29uZmlncyIsImNsb3VkYnJlYWsudGVtcGxhdGVzIiwiY2xvdWRicmVhay5uZXR3b3JrcyIsImNsb3VkYnJlYWsucGxhdGZvcm1zLnJlYWQiLCJjbG91ZGJyZWFrLmNyZWRlbnRpYWxzLnJlYWQiLCJjbG91ZGJyZWFrLnNlY3VyaXR5Z3JvdXBzLnJlYWQiLCJjbG91ZGJyZWFrLnNlY3VyaXR5Z3JvdXBzIiwiY2xvdWRicmVhay5zdGFja3MiLCJjbG91ZGJyZWFrLmNyZWRlbnRpYWxzIiwiY2xvdWRicmVhay5yZWNpcGVzLnJlYWQiLCJjbG91ZGJyZWFrLnNzc2Rjb25maWdzLnJlYWQiLCJjbG91ZGJyZWFrLmJsdWVwcmludHMucmVhZCJdLCJjbGllbnRfaWQiOiJjbG91ZGJyZWFrX3NoZWxsIiwiY2lkIjoiY2xvdWRicmVha19zaGVsbCIsImF6cCI6ImNsb3VkYnJlYWtfc2hlbGwiLCJ1c2VyX2lkIjoiNzlhNmY2MzktNTA2MS00Njk2LTg0YjUtYTBmMjVkY2UxZjMxIiwib3JpZ2luIjoidWFhIiwidXNlcl9uYW1lIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiYXV0aF90aW1lIjoxNDcxNTE4MjEwLCJyZXZfc2lnIjoiNzYzN2FiYzQiLCJpYXQiOjE0NzE1MTgyMTAsImV4cCI6MTQ3MTU2MTQxMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3VhYS9vYXV0aC90b2tlbiIsInppZCI6InVhYSIsImF1ZCI6WyJjbG91ZGJyZWFrX3NoZWxsIiwiY2xvdWRicmVhayIsImNsb3VkYnJlYWsudGVtcGxhdGVzIiwiY2xvdWRicmVhay51c2FnZXMiLCJjbG91ZGJyZWFrLnNlY3VyaXR5Z3JvdXBzIiwiY2xvdWRicmVhay5uZXR3b3JrcyIsIm9wZW5pZCIsInBhc3N3b3JkIiwiY2xvdWRicmVhay5zdGFja3MiLCJjbG91ZGJyZWFrLnBsYXRmb3JtcyIsImNsb3VkYnJlYWsuY3JlZGVudGlhbHMiLCJjbG91ZGJyZWFrLnJlY2lwZXMiLCJjbG91ZGJyZWFrLnNzc2Rjb25maWdzIiwiY2xvdWRicmVhay5ibHVlcHJpbnRzIl19.6AAjkkJ_0EDdd14XZGC9oh4cutxbC6oAi5RAtJNBIFs")
	// make the request to get all items
	resp, err := client.Blueprints.GetPublics(&blueprints.GetPublicsParams{}, &bearerTokenAuth)
	if err != nil {
		log.Fatal(err)
	}

	for _, v := range resp.Payload {
		fmt.Printf("%s\n", v.Name)
	}
}
