// Code generated by go-swagger; DO NOT EDIT.

package v1ldaps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLdapConfigV1Reader is a Reader for the DeleteLdapConfigV1 structure.
type DeleteLdapConfigV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLdapConfigV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteLdapConfigV1Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteLdapConfigV1Default creates a DeleteLdapConfigV1Default with default headers values
func NewDeleteLdapConfigV1Default(code int) *DeleteLdapConfigV1Default {
	return &DeleteLdapConfigV1Default{
		_statusCode: code,
	}
}

/*DeleteLdapConfigV1Default handles this case with default header values.

successful operation
*/
type DeleteLdapConfigV1Default struct {
	_statusCode int
}

// Code gets the status code for the delete ldap config v1 default response
func (o *DeleteLdapConfigV1Default) Code() int {
	return o._statusCode
}

func (o *DeleteLdapConfigV1Default) Error() string {
	return fmt.Sprintf("[DELETE /v1/ldaps][%d] deleteLdapConfigV1 default ", o._statusCode)
}

func (o *DeleteLdapConfigV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
