// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-redbeams/model"
)

// GetDatabaseReader is a Reader for the GetDatabase structure.
type GetDatabaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDatabaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDatabaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDatabaseOK creates a GetDatabaseOK with default headers values
func NewGetDatabaseOK() *GetDatabaseOK {
	return &GetDatabaseOK{}
}

/*GetDatabaseOK handles this case with default header values.

successful operation
*/
type GetDatabaseOK struct {
	Payload *model.DatabaseV4Response
}

func (o *GetDatabaseOK) Error() string {
	return fmt.Sprintf("[GET /v4/databases/{name}][%d] getDatabaseOK  %+v", 200, o.Payload)
}

func (o *GetDatabaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DatabaseV4Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
