// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-redbeams/model"
)

// NewTestDatabaseConnectionParams creates a new TestDatabaseConnectionParams object
// with the default values initialized.
func NewTestDatabaseConnectionParams() *TestDatabaseConnectionParams {
	var ()
	return &TestDatabaseConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestDatabaseConnectionParamsWithTimeout creates a new TestDatabaseConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestDatabaseConnectionParamsWithTimeout(timeout time.Duration) *TestDatabaseConnectionParams {
	var ()
	return &TestDatabaseConnectionParams{

		timeout: timeout,
	}
}

// NewTestDatabaseConnectionParamsWithContext creates a new TestDatabaseConnectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestDatabaseConnectionParamsWithContext(ctx context.Context) *TestDatabaseConnectionParams {
	var ()
	return &TestDatabaseConnectionParams{

		Context: ctx,
	}
}

// NewTestDatabaseConnectionParamsWithHTTPClient creates a new TestDatabaseConnectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTestDatabaseConnectionParamsWithHTTPClient(client *http.Client) *TestDatabaseConnectionParams {
	var ()
	return &TestDatabaseConnectionParams{
		HTTPClient: client,
	}
}

/*TestDatabaseConnectionParams contains all the parameters to send to the API endpoint
for the test database connection operation typically these are written to a http.Request
*/
type TestDatabaseConnectionParams struct {

	/*Body
	  Request for testing connectivity to a database

	*/
	Body *model.DatabaseTestV4Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test database connection params
func (o *TestDatabaseConnectionParams) WithTimeout(timeout time.Duration) *TestDatabaseConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test database connection params
func (o *TestDatabaseConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test database connection params
func (o *TestDatabaseConnectionParams) WithContext(ctx context.Context) *TestDatabaseConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test database connection params
func (o *TestDatabaseConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test database connection params
func (o *TestDatabaseConnectionParams) WithHTTPClient(client *http.Client) *TestDatabaseConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test database connection params
func (o *TestDatabaseConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the test database connection params
func (o *TestDatabaseConnectionParams) WithBody(body *model.DatabaseTestV4Request) *TestDatabaseConnectionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the test database connection params
func (o *TestDatabaseConnectionParams) SetBody(body *model.DatabaseTestV4Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TestDatabaseConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
