// Code generated by go-swagger; DO NOT EDIT.

package v3_workspace_id_kerberos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetKerberosConfigInWorkspaceParams creates a new GetKerberosConfigInWorkspaceParams object
// with the default values initialized.
func NewGetKerberosConfigInWorkspaceParams() *GetKerberosConfigInWorkspaceParams {
	var ()
	return &GetKerberosConfigInWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKerberosConfigInWorkspaceParamsWithTimeout creates a new GetKerberosConfigInWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKerberosConfigInWorkspaceParamsWithTimeout(timeout time.Duration) *GetKerberosConfigInWorkspaceParams {
	var ()
	return &GetKerberosConfigInWorkspaceParams{

		timeout: timeout,
	}
}

// NewGetKerberosConfigInWorkspaceParamsWithContext creates a new GetKerberosConfigInWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKerberosConfigInWorkspaceParamsWithContext(ctx context.Context) *GetKerberosConfigInWorkspaceParams {
	var ()
	return &GetKerberosConfigInWorkspaceParams{

		Context: ctx,
	}
}

// NewGetKerberosConfigInWorkspaceParamsWithHTTPClient creates a new GetKerberosConfigInWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKerberosConfigInWorkspaceParamsWithHTTPClient(client *http.Client) *GetKerberosConfigInWorkspaceParams {
	var ()
	return &GetKerberosConfigInWorkspaceParams{
		HTTPClient: client,
	}
}

/*GetKerberosConfigInWorkspaceParams contains all the parameters to send to the API endpoint
for the get kerberos config in workspace operation typically these are written to a http.Request
*/
type GetKerberosConfigInWorkspaceParams struct {

	/*Name*/
	Name string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) WithTimeout(timeout time.Duration) *GetKerberosConfigInWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) WithContext(ctx context.Context) *GetKerberosConfigInWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) WithHTTPClient(client *http.Client) *GetKerberosConfigInWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) WithName(name string) *GetKerberosConfigInWorkspaceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) SetName(name string) {
	o.Name = name
}

// WithWorkspaceID adds the workspaceID to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) WithWorkspaceID(workspaceID int64) *GetKerberosConfigInWorkspaceParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the get kerberos config in workspace params
func (o *GetKerberosConfigInWorkspaceParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetKerberosConfigInWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
