// Code generated by go-swagger; DO NOT EDIT.

package v1platform_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRegionsByCredentialAndWorkspaceParams creates a new GetRegionsByCredentialAndWorkspaceParams object
// with the default values initialized.
func NewGetRegionsByCredentialAndWorkspaceParams() *GetRegionsByCredentialAndWorkspaceParams {
	var ()
	return &GetRegionsByCredentialAndWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegionsByCredentialAndWorkspaceParamsWithTimeout creates a new GetRegionsByCredentialAndWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegionsByCredentialAndWorkspaceParamsWithTimeout(timeout time.Duration) *GetRegionsByCredentialAndWorkspaceParams {
	var ()
	return &GetRegionsByCredentialAndWorkspaceParams{

		timeout: timeout,
	}
}

// NewGetRegionsByCredentialAndWorkspaceParamsWithContext creates a new GetRegionsByCredentialAndWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegionsByCredentialAndWorkspaceParamsWithContext(ctx context.Context) *GetRegionsByCredentialAndWorkspaceParams {
	var ()
	return &GetRegionsByCredentialAndWorkspaceParams{

		Context: ctx,
	}
}

// NewGetRegionsByCredentialAndWorkspaceParamsWithHTTPClient creates a new GetRegionsByCredentialAndWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRegionsByCredentialAndWorkspaceParamsWithHTTPClient(client *http.Client) *GetRegionsByCredentialAndWorkspaceParams {
	var ()
	return &GetRegionsByCredentialAndWorkspaceParams{
		HTTPClient: client,
	}
}

/*GetRegionsByCredentialAndWorkspaceParams contains all the parameters to send to the API endpoint
for the get regions by credential and workspace operation typically these are written to a http.Request
*/
type GetRegionsByCredentialAndWorkspaceParams struct {

	/*AvailabilityZone*/
	AvailabilityZone *string
	/*CredentialName*/
	CredentialName *string
	/*PlatformVariant*/
	PlatformVariant *string
	/*Region*/
	Region *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithTimeout(timeout time.Duration) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithContext(ctx context.Context) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithHTTPClient(client *http.Client) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAvailabilityZone adds the availabilityZone to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithAvailabilityZone(availabilityZone *string) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetAvailabilityZone(availabilityZone)
	return o
}

// SetAvailabilityZone adds the availabilityZone to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetAvailabilityZone(availabilityZone *string) {
	o.AvailabilityZone = availabilityZone
}

// WithCredentialName adds the credentialName to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithCredentialName(credentialName *string) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetCredentialName(credentialName)
	return o
}

// SetCredentialName adds the credentialName to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetCredentialName(credentialName *string) {
	o.CredentialName = credentialName
}

// WithPlatformVariant adds the platformVariant to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithPlatformVariant(platformVariant *string) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetPlatformVariant(platformVariant)
	return o
}

// SetPlatformVariant adds the platformVariant to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetPlatformVariant(platformVariant *string) {
	o.PlatformVariant = platformVariant
}

// WithRegion adds the region to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) WithRegion(region *string) *GetRegionsByCredentialAndWorkspaceParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the get regions by credential and workspace params
func (o *GetRegionsByCredentialAndWorkspaceParams) SetRegion(region *string) {
	o.Region = region
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegionsByCredentialAndWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AvailabilityZone != nil {

		// query param availabilityZone
		var qrAvailabilityZone string
		if o.AvailabilityZone != nil {
			qrAvailabilityZone = *o.AvailabilityZone
		}
		qAvailabilityZone := qrAvailabilityZone
		if qAvailabilityZone != "" {
			if err := r.SetQueryParam("availabilityZone", qAvailabilityZone); err != nil {
				return err
			}
		}

	}

	if o.CredentialName != nil {

		// query param credentialName
		var qrCredentialName string
		if o.CredentialName != nil {
			qrCredentialName = *o.CredentialName
		}
		qCredentialName := qrCredentialName
		if qCredentialName != "" {
			if err := r.SetQueryParam("credentialName", qCredentialName); err != nil {
				return err
			}
		}

	}

	if o.PlatformVariant != nil {

		// query param platformVariant
		var qrPlatformVariant string
		if o.PlatformVariant != nil {
			qrPlatformVariant = *o.PlatformVariant
		}
		qPlatformVariant := qrPlatformVariant
		if qPlatformVariant != "" {
			if err := r.SetQueryParam("platformVariant", qPlatformVariant); err != nil {
				return err
			}
		}

	}

	if o.Region != nil {

		// query param region
		var qrRegion string
		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {
			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
