// Code generated by go-swagger; DO NOT EDIT.

package v1platform_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-environment/model"
)

// GetDisktypesForWorkspaceReader is a Reader for the GetDisktypesForWorkspace structure.
type GetDisktypesForWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDisktypesForWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDisktypesForWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDisktypesForWorkspaceOK creates a GetDisktypesForWorkspaceOK with default headers values
func NewGetDisktypesForWorkspaceOK() *GetDisktypesForWorkspaceOK {
	return &GetDisktypesForWorkspaceOK{}
}

/*GetDisktypesForWorkspaceOK handles this case with default header values.

successful operation
*/
type GetDisktypesForWorkspaceOK struct {
	Payload *model.PlatformDisksResponse
}

func (o *GetDisktypesForWorkspaceOK) Error() string {
	return fmt.Sprintf("[GET /v1/platform_resources/disk_types][%d] getDisktypesForWorkspaceOK  %+v", 200, o.Payload)
}

func (o *GetDisktypesForWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.PlatformDisksResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
