package models_cloudbreak

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ConnectedClusterRequest connected cluster request

swagger:model ConnectedClusterRequest
*/
type ConnectedClusterRequest struct {

	/* source cluster id
	 */
	SourceClusterID *int64 `json:"sourceClusterId,omitempty"`

	/* source cluster name
	 */
	SourceClusterName *string `json:"sourceClusterName,omitempty"`
}

// Validate validates this connected cluster request
func (m *ConnectedClusterRequest) Validate(formats strfmt.Registry) error {
	return nil
}
