package models_cloudbreak

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*RDSBuildRequest r d s build request

swagger:model RDSBuildRequest
*/
type RDSBuildRequest struct {

	/* requested cluster name

	Required: true
	*/
	ClusterName string `json:"clusterName"`

	/* rds config request

	Required: true
	*/
	RdsConfigRequest *RDSConfig `json:"rdsConfigRequest"`
}

// Validate validates this r d s build request
func (m *RDSBuildRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRdsConfigRequest(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RDSBuildRequest) validateClusterName(formats strfmt.Registry) error {

	if err := validate.RequiredString("clusterName", "body", string(m.ClusterName)); err != nil {
		return err
	}

	return nil
}

func (m *RDSBuildRequest) validateRdsConfigRequest(formats strfmt.Registry) error {

	if m.RdsConfigRequest != nil {

		if err := m.RdsConfigRequest.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
