package models_cloudbreak

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*VMTypeJSON vm type json

swagger:model VmTypeJson
*/
type VMTypeJSON struct {

	/* value
	 */
	Value *string `json:"value,omitempty"`

	/* vm type meta json
	 */
	VMTypeMetaJSON *VMTypeMetaJSON `json:"vmTypeMetaJson,omitempty"`
}

// Validate validates this vm type json
func (m *VMTypeJSON) Validate(formats strfmt.Registry) error {
	return nil
}
