// Code generated by go-swagger; DO NOT EDIT.

package v1distrox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDistroXV1Params creates a new ListDistroXV1Params object
// with the default values initialized.
func NewListDistroXV1Params() *ListDistroXV1Params {
	var (
		onlyDatalakesDefault = bool(false)
	)
	return &ListDistroXV1Params{
		OnlyDatalakes: &onlyDatalakesDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListDistroXV1ParamsWithTimeout creates a new ListDistroXV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDistroXV1ParamsWithTimeout(timeout time.Duration) *ListDistroXV1Params {
	var (
		onlyDatalakesDefault = bool(false)
	)
	return &ListDistroXV1Params{
		OnlyDatalakes: &onlyDatalakesDefault,

		timeout: timeout,
	}
}

// NewListDistroXV1ParamsWithContext creates a new ListDistroXV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewListDistroXV1ParamsWithContext(ctx context.Context) *ListDistroXV1Params {
	var (
		onlyDatalakesDefault = bool(false)
	)
	return &ListDistroXV1Params{
		OnlyDatalakes: &onlyDatalakesDefault,

		Context: ctx,
	}
}

// NewListDistroXV1ParamsWithHTTPClient creates a new ListDistroXV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDistroXV1ParamsWithHTTPClient(client *http.Client) *ListDistroXV1Params {
	var (
		onlyDatalakesDefault = bool(false)
	)
	return &ListDistroXV1Params{
		OnlyDatalakes: &onlyDatalakesDefault,
		HTTPClient:    client,
	}
}

/*ListDistroXV1Params contains all the parameters to send to the API endpoint
for the list distro x v1 operation typically these are written to a http.Request
*/
type ListDistroXV1Params struct {

	/*Environment*/
	Environment *string
	/*OnlyDatalakes*/
	OnlyDatalakes *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list distro x v1 params
func (o *ListDistroXV1Params) WithTimeout(timeout time.Duration) *ListDistroXV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list distro x v1 params
func (o *ListDistroXV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list distro x v1 params
func (o *ListDistroXV1Params) WithContext(ctx context.Context) *ListDistroXV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list distro x v1 params
func (o *ListDistroXV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list distro x v1 params
func (o *ListDistroXV1Params) WithHTTPClient(client *http.Client) *ListDistroXV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list distro x v1 params
func (o *ListDistroXV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironment adds the environment to the list distro x v1 params
func (o *ListDistroXV1Params) WithEnvironment(environment *string) *ListDistroXV1Params {
	o.SetEnvironment(environment)
	return o
}

// SetEnvironment adds the environment to the list distro x v1 params
func (o *ListDistroXV1Params) SetEnvironment(environment *string) {
	o.Environment = environment
}

// WithOnlyDatalakes adds the onlyDatalakes to the list distro x v1 params
func (o *ListDistroXV1Params) WithOnlyDatalakes(onlyDatalakes *bool) *ListDistroXV1Params {
	o.SetOnlyDatalakes(onlyDatalakes)
	return o
}

// SetOnlyDatalakes adds the onlyDatalakes to the list distro x v1 params
func (o *ListDistroXV1Params) SetOnlyDatalakes(onlyDatalakes *bool) {
	o.OnlyDatalakes = onlyDatalakes
}

// WriteToRequest writes these params to a swagger request
func (o *ListDistroXV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Environment != nil {

		// query param environment
		var qrEnvironment string
		if o.Environment != nil {
			qrEnvironment = *o.Environment
		}
		qEnvironment := qrEnvironment
		if qEnvironment != "" {
			if err := r.SetQueryParam("environment", qEnvironment); err != nil {
				return err
			}
		}

	}

	if o.OnlyDatalakes != nil {

		// query param onlyDatalakes
		var qrOnlyDatalakes bool
		if o.OnlyDatalakes != nil {
			qrOnlyDatalakes = *o.OnlyDatalakes
		}
		qOnlyDatalakes := swag.FormatBool(qrOnlyDatalakes)
		if qOnlyDatalakes != "" {
			if err := r.SetQueryParam("onlyDatalakes", qOnlyDatalakes); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
