// Code generated by go-swagger; DO NOT EDIT.

package v1distrox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStatusDistroXV1Params creates a new StatusDistroXV1Params object
// with the default values initialized.
func NewStatusDistroXV1Params() *StatusDistroXV1Params {
	var ()
	return &StatusDistroXV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewStatusDistroXV1ParamsWithTimeout creates a new StatusDistroXV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewStatusDistroXV1ParamsWithTimeout(timeout time.Duration) *StatusDistroXV1Params {
	var ()
	return &StatusDistroXV1Params{

		timeout: timeout,
	}
}

// NewStatusDistroXV1ParamsWithContext creates a new StatusDistroXV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewStatusDistroXV1ParamsWithContext(ctx context.Context) *StatusDistroXV1Params {
	var ()
	return &StatusDistroXV1Params{

		Context: ctx,
	}
}

// NewStatusDistroXV1ParamsWithHTTPClient creates a new StatusDistroXV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStatusDistroXV1ParamsWithHTTPClient(client *http.Client) *StatusDistroXV1Params {
	var ()
	return &StatusDistroXV1Params{
		HTTPClient: client,
	}
}

/*StatusDistroXV1Params contains all the parameters to send to the API endpoint
for the status distro x v1 operation typically these are written to a http.Request
*/
type StatusDistroXV1Params struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the status distro x v1 params
func (o *StatusDistroXV1Params) WithTimeout(timeout time.Duration) *StatusDistroXV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the status distro x v1 params
func (o *StatusDistroXV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the status distro x v1 params
func (o *StatusDistroXV1Params) WithContext(ctx context.Context) *StatusDistroXV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the status distro x v1 params
func (o *StatusDistroXV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the status distro x v1 params
func (o *StatusDistroXV1Params) WithHTTPClient(client *http.Client) *StatusDistroXV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the status distro x v1 params
func (o *StatusDistroXV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the status distro x v1 params
func (o *StatusDistroXV1Params) WithName(name string) *StatusDistroXV1Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the status distro x v1 params
func (o *StatusDistroXV1Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StatusDistroXV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
