// Code generated by go-swagger; DO NOT EDIT.

package v1distrox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// StatusDistroXV1ByCrnReader is a Reader for the StatusDistroXV1ByCrn structure.
type StatusDistroXV1ByCrnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatusDistroXV1ByCrnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStatusDistroXV1ByCrnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStatusDistroXV1ByCrnOK creates a StatusDistroXV1ByCrnOK with default headers values
func NewStatusDistroXV1ByCrnOK() *StatusDistroXV1ByCrnOK {
	return &StatusDistroXV1ByCrnOK{}
}

/*StatusDistroXV1ByCrnOK handles this case with default header values.

successful operation
*/
type StatusDistroXV1ByCrnOK struct {
	Payload *model.StackStatusV4Response
}

func (o *StatusDistroXV1ByCrnOK) Error() string {
	return fmt.Sprintf("[GET /v1/distrox/crn/{crn}/status][%d] statusDistroXV1ByCrnOK  %+v", 200, o.Payload)
}

func (o *StatusDistroXV1ByCrnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.StackStatusV4Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
