package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/hortonworks/hdc-cli/models_autoscale"
)

// NewUpdatePrometheusAlertParams creates a new UpdatePrometheusAlertParams object
// with the default values initialized.
func NewUpdatePrometheusAlertParams() *UpdatePrometheusAlertParams {
	var ()
	return &UpdatePrometheusAlertParams{}
}

/*UpdatePrometheusAlertParams contains all the parameters to send to the API endpoint
for the update prometheus alert operation typically these are written to a http.Request
*/
type UpdatePrometheusAlertParams struct {

	/*AlertID*/
	AlertID int64
	/*Body*/
	Body *models_autoscale.PromhetheusAlert
	/*ClusterID*/
	ClusterID int64
}

// WithAlertID adds the alertId to the update prometheus alert params
func (o *UpdatePrometheusAlertParams) WithAlertID(alertId int64) *UpdatePrometheusAlertParams {
	o.AlertID = alertId
	return o
}

// WithBody adds the body to the update prometheus alert params
func (o *UpdatePrometheusAlertParams) WithBody(body *models_autoscale.PromhetheusAlert) *UpdatePrometheusAlertParams {
	o.Body = body
	return o
}

// WithClusterID adds the clusterId to the update prometheus alert params
func (o *UpdatePrometheusAlertParams) WithClusterID(clusterId int64) *UpdatePrometheusAlertParams {
	o.ClusterID = clusterId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePrometheusAlertParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param alertId
	if err := r.SetPathParam("alertId", swag.FormatInt64(o.AlertID)); err != nil {
		return err
	}

	if o.Body == nil {
		o.Body = new(models_autoscale.PromhetheusAlert)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param clusterId
	if err := r.SetPathParam("clusterId", swag.FormatInt64(o.ClusterID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
