package com.sequenceiq.cloudbreak.core.flow;

public enum FlowPhases {
    PROVISIONING_SETUP,
    PROVISIONING,
    METADATA_SETUP,
    AMBARI_ROLE_ALLOCATION,
    AMBARI_START,
    CLUSTER_CREATION,
    STACK_CREATION_FAILED,
    STACK_START,
    STACK_START_FAILED,
    STACK_STOP,
    STACK_STOP_FAILED,
    STACK_UPSCALE,
    STACK_DOWNSCALE,
    CLUSTER_START,
    CLUSTER_START_FAILED,
    CLUSTER_STOP,
    CLUSTER_STOP_FAILED,
    CLUSTER_UPSCALE,
    CLUSTER_DOWNSCALE,
    TERMINATION,
    TERMINATION_FAILED,
    UPDATE_ALLOWED_SUBNETS,
    SUCCESS,
    NONE
}
