package blueprints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetPrivateParams creates a new GetPrivateParams object
// with the default values initialized.
func NewGetPrivateParams() *GetPrivateParams {
	var ()
	return &GetPrivateParams{}
}

/*GetPrivateParams contains all the parameters to send to the API endpoint
for the get private operation typically these are written to a http.Request
*/
type GetPrivateParams struct {

	/*Name*/
	Name string
}

// WithName adds the name to the get private params
func (o *GetPrivateParams) WithName(name string) *GetPrivateParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrivateParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
