package com.sequenceiq.cloudbreak.common.type;

public enum ComponentType {
    IMAGE, CONTAINER, AMBARI_REPO_DETAILS, HDP_REPO_DETAILS, AMBARI_DATABASE_DETAILS, AMBARI_DATABASE_DETAILS_MIGRATED, CLOUDBREAK_DETAILS, STACK_TEMPLATE,
    SALT_STATE, HDF_REPO_DETAILS, CDH_PRODUCT_DETAILS, CM_REPO_DETAILS
}
