package com.sequenceiq.cloudbreak.common.type;

public enum ResourceType {
    // AWS
    CLOUDFORMATION_STACK,
    AWS_RESERVED_IP,
    S3_ACCESS_ROLE_ARN,
    AWS_SUBNET,
    AWS_S3_ROLE,
    AWS_VPC,

    // OPENSTACK
    HEAT_STACK,
    OPENSTACK_ATTACHED_DISK,
    OPENSTACK_NETWORK,
    OPENSTACK_SUBNET,
    OPENSTACK_ROUTER,
    OPENSTACK_SECURITY_GROUP,
    OPENSTACK_PORT,
    OPENSTACK_INSTANCE,
    OPENSTACK_FLOATING_IP,

    // GCP
    GCP_DISK,
    GCP_ATTACHED_DISK,
    GCP_RESERVED_IP,
    GCP_NETWORK,
    GCP_SUBNET,
    GCP_FIREWALL_IN,
    GCP_FIREWALL_INTERNAL,
    GCP_INSTANCE,

    // ARM
    ARM_TEMPLATE,

    // YARN
    YARN_APPLICATION,

    // MOCK
    MOCK_INSTANCE
}
