package com.sequenceiq.cloudbreak.common.type;

public enum ResourceType {
    // AZURE
    AZURE_VIRTUAL_MACHINE,
    AZURE_CLOUD_SERVICE,
    AZURE_RESERVED_IP,
    AZURE_BLOB,
    AZURE_STORAGE,
    AZURE_NETWORK,
    AZURE_AFFINITY_GROUP,
    AZURE_SERVICE_CERTIFICATE,

    // AWS
    CLOUDFORMATION_STACK,
    AWS_RESERVED_IP,

    // OPENSTACK
    HEAT_STACK,
    OPENSTACK_ATTACHED_DISK,
    OPENSTACK_NETWORK,
    OPENSTACK_SUBNET,
    OPENSTACK_ROUTER,
    OPENSTACK_SECURITY_GROUP,
    OPENSTACK_PORT,
    OPENSTACK_INSTANCE,
    OPENSTACK_FLOATING_IP,

    // GCP
    GCP_DISK,
    GCP_ATTACHED_DISK,
    GCP_RESERVED_IP,
    GCP_NETWORK,
    GCP_FIREWALL_IN,
    GCP_FIREWALL_INTERNAL,
    GCP_ROUTE,
    GCP_INSTANCE,

    // ARM
    ARM_TEMPLATE
}
