package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/hortonworks/hdc-cli/models_cloudbreak"
)

// NewPostClusterParams creates a new PostClusterParams object
// with the default values initialized.
func NewPostClusterParams() *PostClusterParams {
	var ()
	return &PostClusterParams{}
}

/*PostClusterParams contains all the parameters to send to the API endpoint
for the post cluster operation typically these are written to a http.Request
*/
type PostClusterParams struct {

	/*Body*/
	Body *models_cloudbreak.ClusterRequest
	/*ID*/
	ID int64
}

// WithBody adds the body to the post cluster params
func (o *PostClusterParams) WithBody(body *models_cloudbreak.ClusterRequest) *PostClusterParams {
	o.Body = body
	return o
}

// WithID adds the id to the post cluster params
func (o *PostClusterParams) WithID(id int64) *PostClusterParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostClusterParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models_cloudbreak.ClusterRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
