package com.sequenceiq.redbeams.api.model.common;

public enum DetailedDBStackStatus {
    UNKNOWN(null),
    // Provision statuses
    PROVISION_REQUESTED(Status.REQUESTED),
    CREATING_INFRASTRUCTURE(Status.CREATE_IN_PROGRESS),
    PROVISIONED(Status.AVAILABLE),
    PROVISION_FAILED(Status.CREATE_FAILED),
    // Termination statuses
    DELETE_REQUESTED(Status.DELETE_REQUESTED),
    DELETE_IN_PROGRESS(Status.DELETE_IN_PROGRESS),
    DEREGISTERING(Status.DELETE_IN_PROGRESS),
    DELETE_COMPLETED(Status.DELETE_COMPLETED),
    DELETE_FAILED(Status.DELETE_FAILED),
    // The stack is available
    AVAILABLE(Status.AVAILABLE),
    // Wait for sync
    WAIT_FOR_SYNC(Status.WAIT_FOR_SYNC),
    //Start statuses
    START_REQUESTED(Status.START_REQUESTED),
    START_IN_PROGRESS(Status.START_IN_PROGRESS),
    START_FAILED(Status.START_FAILED),
    STARTED(Status.AVAILABLE),
    //Stop statuses
    STOP_REQUESTED(Status.STOP_REQUESTED),
    STOP_IN_PROGRESS(Status.STOP_IN_PROGRESS),
    STOP_FAILED(Status.STOP_FAILED),
    STOPPED(Status.STOPPED),
    //cert ssl rotate statuses
    SSL_ROTATE_REQUESTED(Status.SSL_ROTATE_REQUESTED),
    SSL_ROTATE_IN_PROGRESS(Status.SSL_ROTATE_IN_PROGRESS),
    SSL_ROTATE_FAILED(Status.SSL_ROTATE_FAILED),
    SSL_ROTATED(Status.SSL_ROTATED),

    //DB ssl migration statuses
    DB_SSL_MIGRATION_IN_PROGRESS(Status.DB_SSL_MIGRATION_IN_PROGRESS),
    DB_SSL_MIGRATION_FAILED(Status.DB_SSL_MIGRATION_FAILED),
    DB_SSL_MIGRATION_COMPLETED(Status.DB_SSL_MIGRATION_COMPLETED),

    UPGRADE_REQUESTED(Status.UPGRADE_REQUESTED),
    UPGRADE_IN_PROGRESS(Status.UPGRADE_IN_PROGRESS),
    UPGRADE_FAILED(Status.UPGRADE_FAILED),

    VALIDATE_UPGRADE_REQUESTED(Status.VALIDATE_UPGRADE_REQUESTED),
    VALIDATE_UPGRADE_IN_PROGRESS(Status.VALIDATE_UPGRADE_IN_PROGRESS),
    VALIDATE_UPGRADE_FAILED(Status.VALIDATE_UPGRADE_FAILED),
    VALIDATE_UPGRADE_CLEANUP_REQUESTED(Status.VALIDATE_UPGRADE_REQUESTED),
    VALIDATE_UPGRADE_CLEANUP_IN_PROGRESS(Status.VALIDATE_UPGRADE_IN_PROGRESS),
    VALIDATE_UPGRADE_CLEANUP_FAILED(Status.VALIDATE_UPGRADE_FAILED);

    private final Status status;

    DetailedDBStackStatus(Status status) {
        this.status = status;
    }

    public Status getStatus() {
        return status;
    }
}