package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteTemplatesAccountNameParams creates a new DeleteTemplatesAccountNameParams object
// with the default values initialized.
func NewDeleteTemplatesAccountNameParams() *DeleteTemplatesAccountNameParams {
	var ()
	return &DeleteTemplatesAccountNameParams{}
}

/*DeleteTemplatesAccountNameParams contains all the parameters to send to the API endpoint
for the delete templates account name operation typically these are written to a http.Request
*/
type DeleteTemplatesAccountNameParams struct {

	/*Name*/
	Name string
}

// WithName adds the name to the delete templates account name params
func (o *DeleteTemplatesAccountNameParams) WithName(name string) *DeleteTemplatesAccountNameParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTemplatesAccountNameParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
