package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetTemplateParams creates a new GetTemplateParams object
// with the default values initialized.
func NewGetTemplateParams() *GetTemplateParams {
	var ()
	return &GetTemplateParams{}
}

/*GetTemplateParams contains all the parameters to send to the API endpoint
for the get template operation typically these are written to a http.Request
*/
type GetTemplateParams struct {

	/*ID*/
	ID int64
}

// WithID adds the id to the get template params
func (o *GetTemplateParams) WithID(id int64) *GetTemplateParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetTemplateParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
