#!/bin/bash
#
# /etc/rc.d/init.d/consul_template_prometheus
#
# Consul templates for the Prometheus Monitoring Server
#
#  chkconfig: 2345 20 80 Read
#  description: Consul templates for the Prometheus Monitoring Server
#  processname: consul-template

# Source function library.
. /etc/rc.d/init.d/functions

PROGNAME=consul-template
PROG=/usr/local/bin/$PROGNAME
USER=prometheus
LOGFILE=/var/log/prometheus/consul_template.log
LOCKFILE=/var/run/$PROGNAME.pid

start() {
    echo -n "Starting $PROGNAME: "
    daemon --user $USER --pidfile="$LOCKFILE" "$PROG -consul consul.service.consul:8500 \
     -template /etc/prometheus/templates/alerting_rules.ctmpl:/etc/prometheus/rules/alerting.rule:'pkill -HUP prometheus' \
     -template /etc/prometheus/templates/aggregation_rules.ctmpl:/etc/prometheus/rules/aggregation.rule:'pkill -HUP prometheus' \
     -retry '10s' &>$LOGFILE &"
    echo $(pidofproc $PROGNAME) >$LOCKFILE
    echo
}

stop() {
    echo -n "Shutting down $PROGNAME: "
    killproc $PROGNAME
    rm -f $LOCKFILE
    echo
}


case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status $PROGNAME
    ;;
    restart)
    stop
    start
    ;;
    reload)
    echo "Sending SIGHUP to $PROGNAME"
    kill -SIGHUP $(pidofproc $PROGNAME)
    ;;
    *)
        echo "Usage: <servicename> {start|stop|status|reload|restart}"
        exit 1
    ;;
esac