package com.sequenceiq.environment.environment.flow.encryptionprofile.event;

import com.sequenceiq.flow.core.FlowEvent;

public enum EnableEncryptionProfileStateSelectors implements FlowEvent {
    VALIDATE_ENABLE_ENCRYPTION_PROFILE_EVENT,
    VALIDATE_ENABLE_ENCRYPTION_PROFILE_HANDLER_EVENT,
    SET_ENCRYPTION_PROFILE_EVENT,
    SET_ENCRYPTION_PROFILE_HANDLER_EVENT,
    UPDATE_SSL_CONFIG_FREEIPA_EVENT,
    UPDATE_SSL_CONFIG_FREEIPA_HANDLER_EVENT,
    UPDATE_SSL_CONFIG_IN_CLUSTERS_EVENT,
    UPDATE_SSL_CONFIG_IN_CLUSTERS_HANDLER_EVENT,
    FINISH_ENABLE_ENCRYPTION_PROFILE_EVENT,
    FINALIZE_ENABLE_ENCRYPTION_PROFILE_EVENT,
    HANDLED_FAILED_ENABLE_ENCRYPTION_PROFILE_EVENT,
    FAILED_ENABLE_ENCRYPTION_PROFILE_EVENT;

    @Override
    public String event() {
        return name();
    }
}
