// Code generated by go-swagger; DO NOT EDIT.

package v3_workspace_id_mpacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewCreateManagementPackInWorkspaceParams creates a new CreateManagementPackInWorkspaceParams object
// with the default values initialized.
func NewCreateManagementPackInWorkspaceParams() *CreateManagementPackInWorkspaceParams {
	var ()
	return &CreateManagementPackInWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateManagementPackInWorkspaceParamsWithTimeout creates a new CreateManagementPackInWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateManagementPackInWorkspaceParamsWithTimeout(timeout time.Duration) *CreateManagementPackInWorkspaceParams {
	var ()
	return &CreateManagementPackInWorkspaceParams{

		timeout: timeout,
	}
}

// NewCreateManagementPackInWorkspaceParamsWithContext creates a new CreateManagementPackInWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateManagementPackInWorkspaceParamsWithContext(ctx context.Context) *CreateManagementPackInWorkspaceParams {
	var ()
	return &CreateManagementPackInWorkspaceParams{

		Context: ctx,
	}
}

// NewCreateManagementPackInWorkspaceParamsWithHTTPClient creates a new CreateManagementPackInWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateManagementPackInWorkspaceParamsWithHTTPClient(client *http.Client) *CreateManagementPackInWorkspaceParams {
	var ()
	return &CreateManagementPackInWorkspaceParams{
		HTTPClient: client,
	}
}

/*CreateManagementPackInWorkspaceParams contains all the parameters to send to the API endpoint
for the create management pack in workspace operation typically these are written to a http.Request
*/
type CreateManagementPackInWorkspaceParams struct {

	/*Body*/
	Body *model.ManagementPackRequest
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) WithTimeout(timeout time.Duration) *CreateManagementPackInWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) WithContext(ctx context.Context) *CreateManagementPackInWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) WithHTTPClient(client *http.Client) *CreateManagementPackInWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) WithBody(body *model.ManagementPackRequest) *CreateManagementPackInWorkspaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) SetBody(body *model.ManagementPackRequest) {
	o.Body = body
}

// WithWorkspaceID adds the workspaceID to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) WithWorkspaceID(workspaceID int64) *CreateManagementPackInWorkspaceParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the create management pack in workspace params
func (o *CreateManagementPackInWorkspaceParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateManagementPackInWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(model.ManagementPackRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
