package rdsconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/hortonworks/hdc-cli/models_cloudbreak"
)

// NewPostPublicRdsParams creates a new PostPublicRdsParams object
// with the default values initialized.
func NewPostPublicRdsParams() *PostPublicRdsParams {
	var ()
	return &PostPublicRdsParams{}
}

/*PostPublicRdsParams contains all the parameters to send to the API endpoint
for the post public rds operation typically these are written to a http.Request
*/
type PostPublicRdsParams struct {

	/*Body*/
	Body *models_cloudbreak.RDSConfig
}

// WithBody adds the body to the post public rds params
func (o *PostPublicRdsParams) WithBody(body *models_cloudbreak.RDSConfig) *PostPublicRdsParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostPublicRdsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models_cloudbreak.RDSConfig)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
