// Code generated by go-swagger; DO NOT EDIT.

package v1connectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// GetEncryptionKeysReader is a Reader for the GetEncryptionKeys structure.
type GetEncryptionKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEncryptionKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEncryptionKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEncryptionKeysOK creates a GetEncryptionKeysOK with default headers values
func NewGetEncryptionKeysOK() *GetEncryptionKeysOK {
	return &GetEncryptionKeysOK{}
}

/*GetEncryptionKeysOK handles this case with default header values.

successful operation
*/
type GetEncryptionKeysOK struct {
	Payload *models_cloudbreak.PlatformEncryptionKeysResponse
}

func (o *GetEncryptionKeysOK) Error() string {
	return fmt.Sprintf("[POST /v1/connectors/encryptionkeys][%d] getEncryptionKeysOK  %+v", 200, o.Payload)
}

func (o *GetEncryptionKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_cloudbreak.PlatformEncryptionKeysResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
