package com.sequenceiq.periscope.monitor.evaluator

import org.springframework.context.ApplicationEventPublisher
import org.springframework.context.ApplicationEventPublisherAware

interface EventPublisher : ApplicationEventPublisher, ApplicationEventPublisherAware, Runnable
