// Code generated by go-swagger; DO NOT EDIT.

package v3_workspace_id_clustertemplate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// CreateInWorkspaceFromTemplateReader is a Reader for the CreateInWorkspaceFromTemplate structure.
type CreateInWorkspaceFromTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInWorkspaceFromTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateInWorkspaceFromTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateInWorkspaceFromTemplateOK creates a CreateInWorkspaceFromTemplateOK with default headers values
func NewCreateInWorkspaceFromTemplateOK() *CreateInWorkspaceFromTemplateOK {
	return &CreateInWorkspaceFromTemplateOK{}
}

/*CreateInWorkspaceFromTemplateOK handles this case with default header values.

successful operation
*/
type CreateInWorkspaceFromTemplateOK struct {
	Payload *model.StackResponse
}

func (o *CreateInWorkspaceFromTemplateOK) Error() string {
	return fmt.Sprintf("[POST /v3/{workspaceId}/clustertemplate/{name}][%d] createInWorkspaceFromTemplateOK  %+v", 200, o.Payload)
}

func (o *CreateInWorkspaceFromTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.StackResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
