package com.sequenceiq.cloudbreak.core.flow2;

public class FlowTriggers {
    public static final String STACK_PROVISION_TRIGGER_EVENT = "STACK_PROVISION_TRIGGER_EVENT";

    public static final String CLUSTER_PROVISION_TRIGGER_EVENT = "CLUSTER_PROVISION_TRIGGER_EVENT";

    public static final String CLUSTER_INSTALL_TRIGGER_EVENT = "CLUSTER_INSTALL_TRIGGER_EVENT";

    public static final String CLUSTER_RESET_TRIGGER_EVENT = "CLUSTER_RESET_TRIGGER_EVENT";

    public static final String CLUSTER_CREDENTIALCHANGE_TRIGGER_EVENT = "CLUSTER_CREDENTIAL_CHANGE_TRIGGER_EVENT";

    public static final String STACK_UPSCALE_TRIGGER_EVENT = "STACK_UPSCALE_TRIGGER_EVENT";

    public static final String CLUSTER_UPSCALE_TRIGGER_EVENT = "CLUSTER_UPSCALE_TRIGGER_EVENT";

    public static final String STACK_DOWNSCALE_TRIGGER_EVENT = "STACK_DOWNSCALE_TRIGGER_EVENT";

    public static final String CLUSTER_DOWNSCALE_TRIGGER_EVENT = "CLUSTER_DOWNSCALE_TRIGGER_EVENT";

    public static final String STACK_START_TRIGGER_EVENT = "STACK_START_TRIGGER_EVENT";

    public static final String CLUSTER_START_TRIGGER_EVENT = "CLUSTER_START_TRIGGER_EVENT";

    public static final String STACK_STOP_TRIGGER_EVENT = "STACK_STOP_TRIGGER_EVENT";

    public static final String CLUSTER_STOP_TRIGGER_EVENT = "CLUSTER_STOP_TRIGGER_EVENT";

    public static final String STACK_SYNC_TRIGGER_EVENT = "STACK_SYNC_TRIGGER_EVENT";

    public static final String CLUSTER_SYNC_TRIGGER_EVENT = "CLUSTER_SYNC_TRIGGER_EVENT";

    public static final String REMOVE_INSTANCE_TRIGGER_EVENT = "REMOVE_INSTANCE_TRIGGER_EVENT";

    public static final String STACK_TERMINATE_TRIGGER_EVENT = "STACK_TERMINATE_TRIGGER_EVENT";

    public static final String STACK_FORCE_TERMINATE_TRIGGER_EVENT = "STACK_FORCE_TERMINATE_TRIGGER_EVENT";

    public static final String CLUSTER_TERMINATION_TRIGGER_EVENT = "CLUSTER_TERMINATION_TRIGGER_EVENT";

    private FlowTriggers() {
    }
}
