package com.sequenceiq.cloudbreak.core.flow2

object FlowTriggers {
    val FULL_PROVISION_TRIGGER_EVENT = "FULL_PROVISION_TRIGGER_EVENT"
    val STACK_PROVISION_TRIGGER_EVENT = "STACK_PROVISION_TRIGGER_EVENT"
    val CLUSTER_PROVISION_TRIGGER_EVENT = "CLUSTER_PROVISION_TRIGGER_EVENT"
    val CLUSTER_INSTALL_TRIGGER_EVENT = "CLUSTER_INSTALL_TRIGGER_EVENT"
    val CLUSTER_RESET_TRIGGER_EVENT = "CLUSTER_RESET_TRIGGER_EVENT"
    val CLUSTER_RESET_CHAIN_TRIGGER_EVENT = "CLUSTER_RESET_CHAIN_TRIGGER_EVENT"
    val CLUSTER_CREDENTIALCHANGE_TRIGGER_EVENT = "CLUSTER_CREDENTIAL_CHANGE_TRIGGER_EVENT"

    val FULL_UPSCALE_TRIGGER_EVENT = "FULL_UPSCALE_TRIGGER_EVENT"
    val STACK_UPSCALE_TRIGGER_EVENT = "STACK_UPSCALE_TRIGGER_EVENT"
    val CLUSTER_UPSCALE_TRIGGER_EVENT = "CLUSTER_UPSCALE_TRIGGER_EVENT"

    val FULL_DOWNSCALE_TRIGGER_EVENT = "FULL_DOWNSCALE_TRIGGER_EVENT"
    val STACK_DOWNSCALE_TRIGGER_EVENT = "STACK_DOWNSCALE_TRIGGER_EVENT"
    val CLUSTER_DOWNSCALE_TRIGGER_EVENT = "CLUSTER_DOWNSCALE_TRIGGER_EVENT"

    val FULL_START_TRIGGER_EVENT = "FULL_START_TRIGGER_EVENT"
    val STACK_START_TRIGGER_EVENT = "STACK_START_TRIGGER_EVENT"
    val CLUSTER_START_TRIGGER_EVENT = "CLUSTER_START_TRIGGER_EVENT"

    val FULL_STOP_TRIGGER_EVENT = "FULL_STOP_TRIGGER_EVENT"
    val STACK_STOP_TRIGGER_EVENT = "STACK_STOP_TRIGGER_EVENT"
    val CLUSTER_STOP_TRIGGER_EVENT = "CLUSTER_STOP_TRIGGER_EVENT"

    val FULL_SYNC_TRIGGER_EVENT = "FULL_SYNC_TRIGGER_EVENT"
    val STACK_SYNC_TRIGGER_EVENT = "STACK_SYNC_TRIGGER_EVENT"
    val CLUSTER_SYNC_TRIGGER_EVENT = "CLUSTER_SYNC_TRIGGER_EVENT"

    val REMOVE_INSTANCE_TRIGGER_EVENT = "REMOVE_INSTANCE_TRIGGER_EVENT"
    val STACK_TERMINATE_TRIGGER_EVENT = "STACK_TERMINATE_TRIGGER_EVENT"
    val STACK_FORCE_TERMINATE_TRIGGER_EVENT = "STACK_FORCE_TERMINATE_TRIGGER_EVENT"
    val CLUSTER_TERMINATION_TRIGGER_EVENT = "CLUSTER_TERMINATION_TRIGGER_EVENT"
}
