// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_clustertemplates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// GetClusterTemplateByCrnInWorkspaceReader is a Reader for the GetClusterTemplateByCrnInWorkspace structure.
type GetClusterTemplateByCrnInWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterTemplateByCrnInWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClusterTemplateByCrnInWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetClusterTemplateByCrnInWorkspaceOK creates a GetClusterTemplateByCrnInWorkspaceOK with default headers values
func NewGetClusterTemplateByCrnInWorkspaceOK() *GetClusterTemplateByCrnInWorkspaceOK {
	return &GetClusterTemplateByCrnInWorkspaceOK{}
}

/*GetClusterTemplateByCrnInWorkspaceOK handles this case with default header values.

successful operation
*/
type GetClusterTemplateByCrnInWorkspaceOK struct {
	Payload *model.ClusterTemplateV4Response
}

func (o *GetClusterTemplateByCrnInWorkspaceOK) Error() string {
	return fmt.Sprintf("[GET /v4/{workspaceId}/cluster_templates/crn/{crn}][%d] getClusterTemplateByCrnInWorkspaceOK  %+v", 200, o.Payload)
}

func (o *GetClusterTemplateByCrnInWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ClusterTemplateV4Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
