package securitygroups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetPublicSecurityGroupParams creates a new GetPublicSecurityGroupParams object
// with the default values initialized.
func NewGetPublicSecurityGroupParams() *GetPublicSecurityGroupParams {
	var ()
	return &GetPublicSecurityGroupParams{}
}

/*GetPublicSecurityGroupParams contains all the parameters to send to the API endpoint
for the get public security group operation typically these are written to a http.Request
*/
type GetPublicSecurityGroupParams struct {

	/*Name*/
	Name string
}

// WithName adds the name to the get public security group params
func (o *GetPublicSecurityGroupParams) WithName(name string) *GetPublicSecurityGroupParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetPublicSecurityGroupParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
