// Code generated by go-swagger; DO NOT EDIT.

package v1clustertemplates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// GetClusterTemplateFromClusterNameReader is a Reader for the GetClusterTemplateFromClusterName structure.
type GetClusterTemplateFromClusterNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterTemplateFromClusterNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClusterTemplateFromClusterNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetClusterTemplateFromClusterNameOK creates a GetClusterTemplateFromClusterNameOK with default headers values
func NewGetClusterTemplateFromClusterNameOK() *GetClusterTemplateFromClusterNameOK {
	return &GetClusterTemplateFromClusterNameOK{}
}

/*GetClusterTemplateFromClusterNameOK handles this case with default header values.

successful operation
*/
type GetClusterTemplateFromClusterNameOK struct {
	Payload *models_cloudbreak.StackV2Request
}

func (o *GetClusterTemplateFromClusterNameOK) Error() string {
	return fmt.Sprintf("[GET /v1/clustertemplates/cluster/user/{name}][%d] getClusterTemplateFromClusterNameOK  %+v", 200, o.Payload)
}

func (o *GetClusterTemplateFromClusterNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_cloudbreak.StackV2Request)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
