package com.sequenceiq.authorization.resource;

public enum AuthorizationResourceAction {
    CHANGE_CREDENTIAL,
    EDIT_CREDENTIAL,
    EDIT_ENVIRONMENT,
    START_ENVIRONMENT,
    STOP_ENVIRONMENT,
    DELETE_CREDENTIAL,
    DESCRIBE_CREDENTIAL,
    DELETE_ENVIRONMENT,
    DESCRIBE_ENVIRONMENT,
    ACCESS_ENVIRONMENT,
    ADMIN_FREEIPA,
    CREATE_CREDENTIAL,
    CREATE_ENVIRONMENT,
    GET_KEYTAB,
    CREATE_IMAGE_CATALOG,
    EDIT_IMAGE_CATALOG,
    DESCRIBE_IMAGE_CATALOG,
    DELETE_IMAGE_CATALOG,
    // deprecated actions, please do not use them
    ENVIRONMENT_READ,
    ENVIRONMENT_WRITE,
    DATALAKE_READ,
    DATALAKE_WRITE,
    DATAHUB_READ,
    DATAHUB_WRITE;
}
