// Code generated by go-swagger; DO NOT EDIT.

package v1ldap

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePublicLdapParams creates a new DeletePublicLdapParams object
// with the default values initialized.
func NewDeletePublicLdapParams() *DeletePublicLdapParams {
	var ()
	return &DeletePublicLdapParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePublicLdapParamsWithTimeout creates a new DeletePublicLdapParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePublicLdapParamsWithTimeout(timeout time.Duration) *DeletePublicLdapParams {
	var ()
	return &DeletePublicLdapParams{

		timeout: timeout,
	}
}

// NewDeletePublicLdapParamsWithContext creates a new DeletePublicLdapParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePublicLdapParamsWithContext(ctx context.Context) *DeletePublicLdapParams {
	var ()
	return &DeletePublicLdapParams{

		Context: ctx,
	}
}

// NewDeletePublicLdapParamsWithHTTPClient creates a new DeletePublicLdapParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePublicLdapParamsWithHTTPClient(client *http.Client) *DeletePublicLdapParams {
	var ()
	return &DeletePublicLdapParams{
		HTTPClient: client,
	}
}

/*DeletePublicLdapParams contains all the parameters to send to the API endpoint
for the delete public ldap operation typically these are written to a http.Request
*/
type DeletePublicLdapParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete public ldap params
func (o *DeletePublicLdapParams) WithTimeout(timeout time.Duration) *DeletePublicLdapParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete public ldap params
func (o *DeletePublicLdapParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete public ldap params
func (o *DeletePublicLdapParams) WithContext(ctx context.Context) *DeletePublicLdapParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete public ldap params
func (o *DeletePublicLdapParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete public ldap params
func (o *DeletePublicLdapParams) WithHTTPClient(client *http.Client) *DeletePublicLdapParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete public ldap params
func (o *DeletePublicLdapParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete public ldap params
func (o *DeletePublicLdapParams) WithName(name string) *DeletePublicLdapParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete public ldap params
func (o *DeletePublicLdapParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePublicLdapParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
