package models_autoscale

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ClusterSummary cluster summary

swagger:model ClusterSummary
*/
type ClusterSummary struct {

	/* Indicate that the Autoscaling feature set is enabled or disabled on the underlying Periscope cluster
	 */
	AutoscalingEnabled *bool `json:"autoscalingEnabled,omitempty"`

	/* Host address of the ambari server
	 */
	Host *string `json:"host,omitempty"`

	/* Id of the cluster
	 */
	ID *int64 `json:"id,omitempty"`

	/* Port of the Ambari server
	 */
	Port *string `json:"port,omitempty"`

	/* Id of the stack in cloudbreak
	 */
	StackID *int64 `json:"stackId,omitempty"`

	/* State of the cluster
	 */
	State *string `json:"state,omitempty"`
}

// Validate validates this cluster summary
func (m *ClusterSummary) Validate(formats strfmt.Registry) error {
	return nil
}
