// Code generated by go-swagger; DO NOT EDIT.

package v3_workspace_id_rdsconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewCreateRdsConfigInWorkspaceParams creates a new CreateRdsConfigInWorkspaceParams object
// with the default values initialized.
func NewCreateRdsConfigInWorkspaceParams() *CreateRdsConfigInWorkspaceParams {
	var ()
	return &CreateRdsConfigInWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRdsConfigInWorkspaceParamsWithTimeout creates a new CreateRdsConfigInWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRdsConfigInWorkspaceParamsWithTimeout(timeout time.Duration) *CreateRdsConfigInWorkspaceParams {
	var ()
	return &CreateRdsConfigInWorkspaceParams{

		timeout: timeout,
	}
}

// NewCreateRdsConfigInWorkspaceParamsWithContext creates a new CreateRdsConfigInWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRdsConfigInWorkspaceParamsWithContext(ctx context.Context) *CreateRdsConfigInWorkspaceParams {
	var ()
	return &CreateRdsConfigInWorkspaceParams{

		Context: ctx,
	}
}

// NewCreateRdsConfigInWorkspaceParamsWithHTTPClient creates a new CreateRdsConfigInWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRdsConfigInWorkspaceParamsWithHTTPClient(client *http.Client) *CreateRdsConfigInWorkspaceParams {
	var ()
	return &CreateRdsConfigInWorkspaceParams{
		HTTPClient: client,
	}
}

/*CreateRdsConfigInWorkspaceParams contains all the parameters to send to the API endpoint
for the create rds config in workspace operation typically these are written to a http.Request
*/
type CreateRdsConfigInWorkspaceParams struct {

	/*Body*/
	Body *model.RdsConfig
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) WithTimeout(timeout time.Duration) *CreateRdsConfigInWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) WithContext(ctx context.Context) *CreateRdsConfigInWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) WithHTTPClient(client *http.Client) *CreateRdsConfigInWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) WithBody(body *model.RdsConfig) *CreateRdsConfigInWorkspaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) SetBody(body *model.RdsConfig) {
	o.Body = body
}

// WithWorkspaceID adds the workspaceID to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) WithWorkspaceID(workspaceID int64) *CreateRdsConfigInWorkspaceParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the create rds config in workspace params
func (o *CreateRdsConfigInWorkspaceParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRdsConfigInWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
