package constraints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// DeleteConstraintReader is a Reader for the DeleteConstraint structure.
type DeleteConstraintReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteConstraintReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewDeleteConstraintDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteConstraintDefault creates a DeleteConstraintDefault with default headers values
func NewDeleteConstraintDefault(code int) *DeleteConstraintDefault {
	return &DeleteConstraintDefault{
		_statusCode: code,
	}
}

/*DeleteConstraintDefault handles this case with default header values.

successful operation
*/
type DeleteConstraintDefault struct {
	_statusCode int
}

// Code gets the status code for the delete constraint default response
func (o *DeleteConstraintDefault) Code() int {
	return o._statusCode
}

func (o *DeleteConstraintDefault) Error() string {
	return fmt.Sprintf("[DELETE /constraints/{id}][%d] deleteConstraint default ", o._statusCode)
}

func (o *DeleteConstraintDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
