package constraints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetConstraintParams creates a new GetConstraintParams object
// with the default values initialized.
func NewGetConstraintParams() *GetConstraintParams {
	var ()
	return &GetConstraintParams{}
}

/*GetConstraintParams contains all the parameters to send to the API endpoint
for the get constraint operation typically these are written to a http.Request
*/
type GetConstraintParams struct {

	/*ID*/
	ID int64
}

// WithID adds the id to the get constraint params
func (o *GetConstraintParams) WithID(id int64) *GetConstraintParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetConstraintParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
