package constraints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/hortonworks/hdc-cli/models_cloudbreak"
)

// GetConstraintsAccountReader is a Reader for the GetConstraintsAccount structure.
type GetConstraintsAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetConstraintsAccountReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConstraintsAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConstraintsAccountOK creates a GetConstraintsAccountOK with default headers values
func NewGetConstraintsAccountOK() *GetConstraintsAccountOK {
	return &GetConstraintsAccountOK{}
}

/*GetConstraintsAccountOK handles this case with default header values.

successful operation
*/
type GetConstraintsAccountOK struct {
	Payload []*models_cloudbreak.ConstraintTemplateResponse
}

func (o *GetConstraintsAccountOK) Error() string {
	return fmt.Sprintf("[GET /constraints/account][%d] getConstraintsAccountOK  %+v", 200, o.Payload)
}

func (o *GetConstraintsAccountOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
