package com.sequenceiq.maintenance.dispatcher.model;

public enum TaskDispatchSkipReason {
    WINDOW_ENDED,
    DEPENDENCY_NOT_FOUND,
    DEPENDENCY_SCOPE_MISMATCH,
    DEPENDENCY_NOT_COMPLETED,
    DEPENDENCY_FAILED,
    DEPENDENCY_SKIPPED,
    IMPLICIT_PLATFORM_ORDERING,
    IMPLICIT_PREREQUISITE_FAILED,
    IMPLICIT_PREREQUISITE_SKIPPED,
    DEDUP_RUNNING,
    DEDUP_COMPLETED,
    DEDUP_SKIPPED,
    RETRY_NOT_ALLOWED,
    RETRY_COOLDOWN
}
