// Code generated by go-swagger; DO NOT EDIT.

package configurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_autoscale"
)

// SetScalingConfigurationReader is a Reader for the SetScalingConfiguration structure.
type SetScalingConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetScalingConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetScalingConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetScalingConfigurationOK creates a SetScalingConfigurationOK with default headers values
func NewSetScalingConfigurationOK() *SetScalingConfigurationOK {
	return &SetScalingConfigurationOK{}
}

/*SetScalingConfigurationOK handles this case with default header values.

successful operation
*/
type SetScalingConfigurationOK struct {
	Payload *models_autoscale.ScalingConfiguration
}

func (o *SetScalingConfigurationOK) Error() string {
	return fmt.Sprintf("[POST /clusters/{clusterId}/configurations/scaling][%d] setScalingConfigurationOK  %+v", 200, o.Payload)
}

func (o *SetScalingConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models_autoscale.ScalingConfiguration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
