server:
  servlet:
    context-path: "/externalizedcompute"
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: ExternalizedComputeService
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 400
        order_inserts: true
        order_updates: true
  lifecycle:
    timeout-per-shutdown-phase: 60s
  main:
    allow-circular-references: true

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: info,health,prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,hikariState"
  metrics:
    distribution:
      slo:
        "[http.server.requests]": "125ms, 250ms, 500ms, 1s, 2s"
      percentiles:
        "[http.server.requests]": "0.5, 0.95"
  info:
    env:
      enabled: true

altus:
  ums:
    host: localhost
    caller: externalizedcompute
  audit:
    enabled: true
    endpoint: localhost:8982

externalizedcompute:
  cert.dir: /certs/
  client.id: externalizedcompute
  structuredevent:
    rest:
      enabled: false
  environmentservice:
    url: http://localhost:8088
  db:
    port.5432.tcp:
      port: 5432
      addr: localhost
    env:
      user: postgres
      pass:
      db: externalizedcomputedb
      schema: public
      cert.file: database.crt
      ssl: false
  liftie:
    host: localhost
    port: 9999

cdp.structuredevent:
  rest:
    contentlogging: true

crn:
  partition: cdp
  region: us-west-1