package credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// DeleteCredentialsAccountNameReader is a Reader for the DeleteCredentialsAccountName structure.
type DeleteCredentialsAccountNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteCredentialsAccountNameReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewDeleteCredentialsAccountNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteCredentialsAccountNameDefault creates a DeleteCredentialsAccountNameDefault with default headers values
func NewDeleteCredentialsAccountNameDefault(code int) *DeleteCredentialsAccountNameDefault {
	return &DeleteCredentialsAccountNameDefault{
		_statusCode: code,
	}
}

/*DeleteCredentialsAccountNameDefault handles this case with default header values.

successful operation
*/
type DeleteCredentialsAccountNameDefault struct {
	_statusCode int
}

// Code gets the status code for the delete credentials account name default response
func (o *DeleteCredentialsAccountNameDefault) Code() int {
	return o._statusCode
}

func (o *DeleteCredentialsAccountNameDefault) Error() string {
	return fmt.Sprintf("[DELETE /credentials/account/{name}][%d] DeleteCredentialsAccountName default ", o._statusCode)
}

func (o *DeleteCredentialsAccountNameDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
