package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PutStackReader is a Reader for the PutStack structure.
type PutStackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutStackReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPutStackDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutStackDefault creates a PutStackDefault with default headers values
func NewPutStackDefault(code int) *PutStackDefault {
	return &PutStackDefault{
		_statusCode: code,
	}
}

/*PutStackDefault handles this case with default header values.

successful operation
*/
type PutStackDefault struct {
	_statusCode int
}

// Code gets the status code for the put stack default response
func (o *PutStackDefault) Code() int {
	return o._statusCode
}

func (o *PutStackDefault) Error() string {
	return fmt.Sprintf("[PUT /stacks/{id}][%d] putStack default ", o._statusCode)
}

func (o *PutStackDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
