// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AmbariKerberosDescriptor ambari kerberos descriptor
// swagger:model AmbariKerberosDescriptor
type AmbariKerberosDescriptor struct {

	// kerberos admin user
	Admin string `json:"admin,omitempty"`

	// Ambari kerberos descriptor
	// Required: true
	Descriptor *string `json:"descriptor"`

	// cluster instances will set this as the domain part of their hostname
	Domain string `json:"domain,omitempty"`

	// Ambari kerberos krb5.conf template
	// Required: true
	Krb5Conf *string `json:"krb5Conf"`

	// comma separated list of nameservers' IP address which will be used by cluster instances
	// Pattern: (^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(,((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))*$)
	NameServers string `json:"nameServers,omitempty"`

	// kerberos admin password
	// Required: true
	// Max Length: 50
	// Min Length: 5
	Password *string `json:"password"`

	// kerberos principal
	// Required: true
	Principal *string `json:"principal"`

	// kerberos configuration name
	// Required: true
	TCPAllowed bool `json:"tcpAllowed"`

	// Allows to select either a trusting SSL connection or a validating (non-trusting) SSL connection to KDC
	VerifyKdcTrust *bool `json:"verifyKdcTrust,omitempty"`
}

// Validate validates this ambari kerberos descriptor
func (m *AmbariKerberosDescriptor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescriptor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKrb5Conf(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNameServers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrincipal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTCPAllowed(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AmbariKerberosDescriptor) validateDescriptor(formats strfmt.Registry) error {

	if err := validate.Required("descriptor", "body", m.Descriptor); err != nil {
		return err
	}

	return nil
}

func (m *AmbariKerberosDescriptor) validateKrb5Conf(formats strfmt.Registry) error {

	if err := validate.Required("krb5Conf", "body", m.Krb5Conf); err != nil {
		return err
	}

	return nil
}

func (m *AmbariKerberosDescriptor) validateNameServers(formats strfmt.Registry) error {

	if swag.IsZero(m.NameServers) { // not required
		return nil
	}

	if err := validate.Pattern("nameServers", "body", string(m.NameServers), `(^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(,((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))*$)`); err != nil {
		return err
	}

	return nil
}

func (m *AmbariKerberosDescriptor) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", string(*m.Password), 5); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", string(*m.Password), 50); err != nil {
		return err
	}

	return nil
}

func (m *AmbariKerberosDescriptor) validatePrincipal(formats strfmt.Registry) error {

	if err := validate.Required("principal", "body", m.Principal); err != nil {
		return err
	}

	return nil
}

func (m *AmbariKerberosDescriptor) validateTCPAllowed(formats strfmt.Registry) error {

	if err := validate.Required("tcpAllowed", "body", bool(m.TCPAllowed)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AmbariKerberosDescriptor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AmbariKerberosDescriptor) UnmarshalBinary(b []byte) error {
	var res AmbariKerberosDescriptor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
