// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AzureDistroXV1Parameters azure distro x v1 parameters
// swagger:model AzureDistroXV1Parameters
type AzureDistroXV1Parameters struct {

	// encrypt storage
	EncryptStorage bool `json:"encryptStorage,omitempty"`

	// resource group name
	ResourceGroupName string `json:"resourceGroupName,omitempty"`
}

// Validate validates this azure distro x v1 parameters
func (m *AzureDistroXV1Parameters) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureDistroXV1Parameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureDistroXV1Parameters) UnmarshalBinary(b []byte) error {
	var res AzureDistroXV1Parameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
