// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ManagementPackV4Entry management pack v4 entry
// swagger:model ManagementPackV4Entry
type ManagementPackV4Entry struct {

	// mpack Url
	MpackURL string `json:"mpackUrl,omitempty"`
}

// Validate validates this management pack v4 entry
func (m *ManagementPackV4Entry) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ManagementPackV4Entry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ManagementPackV4Entry) UnmarshalBinary(b []byte) error {
	var res ManagementPackV4Entry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
