// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// MockInstanceTemplateV4Parameters mock instance template v4 parameters
// swagger:model MockInstanceTemplateV4Parameters
type MockInstanceTemplateV4Parameters interface{}
