// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlatformVmtypesV4Response platform vmtypes v4 response
// swagger:model PlatformVmtypesV4Response
type PlatformVmtypesV4Response struct {

	// vm types
	VMTypes map[string]VirtualMachinesV4Response `json:"vmTypes,omitempty"`
}

// Validate validates this platform vmtypes v4 response
func (m *PlatformVmtypesV4Response) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVMTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlatformVmtypesV4Response) validateVMTypes(formats strfmt.Registry) error {

	if swag.IsZero(m.VMTypes) { // not required
		return nil
	}

	for k := range m.VMTypes {

		if err := validate.Required("vmTypes"+"."+k, "body", m.VMTypes[k]); err != nil {
			return err
		}
		if val, ok := m.VMTypes[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlatformVmtypesV4Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformVmtypesV4Response) UnmarshalBinary(b []byte) error {
	var res PlatformVmtypesV4Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
