// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RepoConfigValidationV4Response repo config validation v4 response
// swagger:model RepoConfigValidationV4Response
type RepoConfigValidationV4Response struct {

	// Indicates the request's value with the same key is valid and reachable by Cloudbreak or not
	AmbariBaseURL bool `json:"ambariBaseUrl,omitempty"`

	// Indicates the request's value with the same key is valid and reachable by Cloudbreak or not
	AmbariGpgKeyURL bool `json:"ambariGpgKeyUrl,omitempty"`

	// Indicates the request's value with the same key is valid and reachable by Cloudbreak or not
	MpackURL bool `json:"mpackUrl,omitempty"`

	// Indicates the request's value with the same key is valid and reachable by Cloudbreak or not
	StackBaseURL bool `json:"stackBaseURL,omitempty"`

	// Indicates the request's value with the same key is valid and reachable by Cloudbreak or not
	UtilsBaseURL bool `json:"utilsBaseURL,omitempty"`

	// Indicates the request's value with the same key is valid and reachable by Cloudbreak or not
	VersionDefinitionFileURL bool `json:"versionDefinitionFileUrl,omitempty"`
}

// Validate validates this repo config validation v4 response
func (m *RepoConfigValidationV4Response) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RepoConfigValidationV4Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepoConfigValidationV4Response) UnmarshalBinary(b []byte) error {
	var res RepoConfigValidationV4Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
