// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StackRepositoryV4Response stack repository v4 response
// swagger:model StackRepositoryV4Response
type StackRepositoryV4Response struct {

	// enable gpl repository
	EnableGplRepo *bool `json:"enableGplRepo,omitempty"`

	// url the MPACK that needs to be installed before HDF installation
	// Pattern: ^http[s]?://.*
	MpackURL string `json:"mpackUrl,omitempty"`

	// Management packs which are needed for the HDP / HDF clusters
	Mpacks []*ManagementPackDetailsV4Response `json:"mpacks"`

	// operating system for the stack, like redhat6
	Os string `json:"os,omitempty"`

	// operating system type for the stack, like centos6
	OsType string `json:"osType,omitempty"`

	// id of the stack repository
	RepoID string `json:"repoId,omitempty"`

	// repository
	Repository *RepositoryV4Response `json:"repository,omitempty"`

	// name of the stack, like HDP
	Stack string `json:"stack,omitempty"`

	// url of the stack utils repository
	UtilsBaseURL string `json:"utilsBaseURL,omitempty"`

	// id of the stack utils repository
	UtilsRepoID string `json:"utilsRepoId,omitempty"`

	// whether to verify or not the repo url
	Verify *bool `json:"verify,omitempty"`

	// version of the stack
	// Pattern: (^[0-9]+\.[0-9]+$)
	Version string `json:"version,omitempty"`

	// local path on the Ambari server or URL that point to the desired VDF file
	VersionDefinitionFileURL string `json:"versionDefinitionFileUrl,omitempty"`
}

// Validate validates this stack repository v4 response
func (m *StackRepositoryV4Response) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMpackURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMpacks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepository(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StackRepositoryV4Response) validateMpackURL(formats strfmt.Registry) error {

	if swag.IsZero(m.MpackURL) { // not required
		return nil
	}

	if err := validate.Pattern("mpackUrl", "body", string(m.MpackURL), `^http[s]?://.*`); err != nil {
		return err
	}

	return nil
}

func (m *StackRepositoryV4Response) validateMpacks(formats strfmt.Registry) error {

	if swag.IsZero(m.Mpacks) { // not required
		return nil
	}

	for i := 0; i < len(m.Mpacks); i++ {
		if swag.IsZero(m.Mpacks[i]) { // not required
			continue
		}

		if m.Mpacks[i] != nil {
			if err := m.Mpacks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("mpacks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *StackRepositoryV4Response) validateRepository(formats strfmt.Registry) error {

	if swag.IsZero(m.Repository) { // not required
		return nil
	}

	if m.Repository != nil {
		if err := m.Repository.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("repository")
			}
			return err
		}
	}

	return nil
}

func (m *StackRepositoryV4Response) validateVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.Version) { // not required
		return nil
	}

	if err := validate.Pattern("version", "body", string(m.Version), `(^[0-9]+\.[0-9]+$)`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StackRepositoryV4Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StackRepositoryV4Response) UnmarshalBinary(b []byte) error {
	var res StackRepositoryV4Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
