// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// VolumeParameterConfigV4Response volume parameter config v4 response
// swagger:model VolumeParameterConfigV4Response
type VolumeParameterConfigV4Response struct {

	// maximum number
	MaximumNumber int32 `json:"maximumNumber,omitempty"`

	// maximum size
	MaximumSize int32 `json:"maximumSize,omitempty"`

	// minimum number
	MinimumNumber int32 `json:"minimumNumber,omitempty"`

	// minimum size
	MinimumSize int32 `json:"minimumSize,omitempty"`

	// volume parameter type
	VolumeParameterType string `json:"volumeParameterType,omitempty"`
}

// Validate validates this volume parameter config v4 response
func (m *VolumeParameterConfigV4Response) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VolumeParameterConfigV4Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VolumeParameterConfigV4Response) UnmarshalBinary(b []byte) error {
	var res VolumeParameterConfigV4Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
