// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WorkloadAnalyticsAttributesHolder workload analytics attributes holder
// swagger:model WorkloadAnalyticsAttributesHolder
type WorkloadAnalyticsAttributesHolder struct {

	// sdx Id
	SdxID string `json:"sdxId,omitempty"`

	// sdx name
	SdxName string `json:"sdxName,omitempty"`
}

// Validate validates this workload analytics attributes holder
func (m *WorkloadAnalyticsAttributesHolder) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WorkloadAnalyticsAttributesHolder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkloadAnalyticsAttributesHolder) UnmarshalBinary(b []byte) error {
	var res WorkloadAnalyticsAttributesHolder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
