<html style="box-sizing: border-box;display: block;font-family: sans-serif;font-size: 10px;min-height: 100%;position: relative;">
<head style="box-sizing: border-box;display: none;font-family: sans-serif;font-size: 10px;height: auto;width: auto;"><title>Your cluster installation request
    completed with ${status} status</title></head>
<body id="page-home"
      style="background-color: rgb(217, 217, 217);box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;line-height: 26.0799999237061px;margin-bottom: 52px;margin-left: 0px;margin-right: 0px;margin-top: 0px;">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation"
     style="-webkit-transform: matrix(1, 0, 0, 1, 0, 0);background-color: rgb(242, 242, 242);border-bottom-color: rgb(226, 226, 226);border-bottom-left-radius: 0px;border-bottom-right-radius: 0px;border-bottom-style: solid;border-bottom-width: 1px;border-image-outset: 0px;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(226, 226, 226);border-left-style: solid;border-left-width: 0px;border-right-color: rgb(226, 226, 226);border-right-style: solid;border-right-width: 0px;border-top-color: rgb(226, 226, 226);border-top-left-radius: 0px;border-top-right-radius: 0px;border-top-style: solid;border-top-width: 0px;box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 53px;left: 0px;line-height: 26.0799999237061px;margin-bottom: 0px;min-height: 52px;position: fixed;right: 0px;top: 0px;transform: matrix(1, 0, 0, 1, 0, 0);z-index: 1030;">
    <div class="container"
         style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 52px;line-height: 26.0799999237061px;margin-left: 84.5px;margin-right: 84.5px;padding-left: 8px;padding-right: 8px">
        <div class="navbar-header"
             style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;float: left;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 52px;line-height: 26.0799999237061px;margin-left: 0px;margin-right: 0px;">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsing"
                    style="-webkit-appearance: none;-webkit-writing-mode: horizontal-tb;align-items: flex-start;background-color: rgba(0, 0, 0, 0);background-image: none;border-bottom-color: rgb(64, 64, 64);border-bottom-left-radius: 0px;border-bottom-right-radius: 0px;border-bottom-style: none;border-bottom-width: 0px;border-image-outset: 0px;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(64, 64, 64);border-left-style: none;border-left-width: 0px;border-right-color: rgb(64, 64, 64);border-right-style: none;border-right-width: 0px;border-top-color: rgb(64, 64, 64);border-top-left-radius: 0px;border-top-right-radius: 0px;border-top-style: none;border-top-width: 0px;box-sizing: border-box;color: rgb(64, 64, 64);cursor: pointer;display: none;float: right;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;font-stretch: normal;font-style: normal;font-variant: normal;font-weight: normal;height: auto;letter-spacing: normal;line-height: 26.0799999237061px;margin-bottom: 7.5px;margin-left: 0px;margin-right: 8px;margin-top: 7.5px;overflow-x: visible;overflow-y: visible;padding-bottom: 10px;padding-left: 10px;padding-right: 10px;padding-top: 10px;position: relative;text-align: center;text-indent: 0px;text-shadow: none;text-transform: none;word-spacing: 0px;writing-mode: lr-tb;">
                <span class="sr-only"
                      style="border-bottom-color: rgb(64, 64, 64);border-bottom-style: none;border-bottom-width: 0px;border-image-outset: 0px;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(64, 64, 64);border-left-style: none;border-left-width: 0px;border-right-color: rgb(64, 64, 64);border-right-style: none;border-right-width: 0px;border-top-color: rgb(64, 64, 64);border-top-style: none;border-top-width: 0px;box-sizing: border-box;clip: rect(0px 0px 0px 0px);color: rgb(64, 64, 64);cursor: pointer;display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;font-style: normal;font-variant: normal;font-weight: normal;height: 1px;letter-spacing: normal;line-height: 26.0799999237061px;margin-bottom: -1px;margin-left: -1px;margin-right: -1px;margin-top: -1px;overflow-x: hidden;overflow-y: hidden;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;padding-top: 0px;position: absolute;text-align: center;text-indent: 0px;text-shadow: none;text-transform: none;word-spacing: 0px;">Toggle navigation</span>
                <span class="icon-bar"
                      style="border-bottom-color: rgb(64, 64, 64);border-bottom-style: none;border-bottom-width: 0px;border-image-outset: 0px;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(64, 64, 64);border-left-style: none;border-left-width: 0px;border-right-color: rgb(64, 64, 64);border-right-style: none;border-right-width: 0px;border-top-color: rgb(64, 64, 64);border-top-style: none;border-top-width: 0px;box-sizing: border-box;clip: rect(0px 0px 0px 0px);color: rgb(64, 64, 64);cursor: pointer;display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;font-style: normal;font-variant: normal;font-weight: normal;height: 1px;letter-spacing: normal;line-height: 26.0799999237061px;margin-bottom: -1px;margin-left: -1px;margin-right: -1px;margin-top: -1px;overflow-x: hidden;overflow-y: hidden;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;padding-top: 0px;position: absolute;text-align: center;text-indent: 0px;text-shadow: none;text-transform: none;word-spacing: 0px;"></span>
                <span class="icon-bar"
                      style="border-bottom-color: rgb(64, 64, 64);border-bottom-style: none;border-bottom-width: 0px;border-image-outset: 0px;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(64, 64, 64);border-left-style: none;border-left-width: 0px;border-right-color: rgb(64, 64, 64);border-right-style: none;border-right-width: 0px;border-top-color: rgb(64, 64, 64);border-top-style: none;border-top-width: 0px;box-sizing: border-box;clip: rect(0px 0px 0px 0px);color: rgb(64, 64, 64);cursor: pointer;display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;font-style: normal;font-variant: normal;font-weight: normal;height: 1px;letter-spacing: normal;line-height: 26.0799999237061px;margin-bottom: -1px;margin-left: -1px;margin-right: -1px;margin-top: -1px;overflow-x: hidden;overflow-y: hidden;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;padding-top: 0px;position: absolute;text-align: center;text-indent: 0px;text-shadow: none;text-transform: none;word-spacing: 0px;"></span>
                <span class="icon-bar"
                      style="border-bottom-color: rgb(64, 64, 64);border-bottom-style: none;border-bottom-width: 0px;border-image-outset: 0px;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(64, 64, 64);border-left-style: none;border-left-width: 0px;border-right-color: rgb(64, 64, 64);border-right-style: none;border-right-width: 0px;border-top-color: rgb(64, 64, 64);border-top-style: none;border-top-width: 0px;box-sizing: border-box;clip: rect(0px 0px 0px 0px);color: rgb(64, 64, 64);cursor: pointer;display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;font-style: normal;font-variant: normal;font-weight: normal;height: 1px;letter-spacing: normal;line-height: 26.0799999237061px;margin-bottom: -1px;margin-left: -1px;margin-right: -1px;margin-top: -1px;overflow-x: hidden;overflow-y: hidden;padding-bottom: 0px;padding-left: 0px;padding-right: 0px;padding-top: 0px;position: absolute;text-align: center;text-indent: 0px;text-shadow: none;text-transform: none;word-spacing: 0px;"></span>
            </button>
            <a class="navbar-brand"
               style="-webkit-background-clip: border-box;-webkit-background-origin: padding-box;-webkit-background-size: auto;background-attachment: scroll;background-clip: border-box;background-color: rgba(0, 0, 0, 0);background-image: none;background-origin: padding-box;background-size: auto;box-sizing: border-box;color: rgb(89, 89, 89);display: block;float: left;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 29px;font-weight: 300;height: 52px;line-height: 26px;margin-left: -4px;padding-bottom: 13px;padding-left: 8px;padding-right: 8px;padding-top: 13px;text-decoration: none;">
            <span class="label label-success"
                  style="background-color: rgb(76, 184, 76);border-bottom-left-radius: 5.4375px;border-bottom-right-radius: 5.4375px;border-top-left-radius: 5.4375px;border-top-right-radius: 5.4375px;box-sizing: border-box;color: rgb(255, 255, 255);display: inline;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 22px;font-weight: bold;height: auto;line-height: 21.75px;padding-bottom: 6.52500009536743px;padding-left: 13.0500001907349px;padding-right: 13.0500001907349px;padding-top: 4.34999990463257px;text-align: center;vertical-align: baseline;white-space: nowrap;">${status}</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapsing"
             style="-webkit-box-shadow: none;border-bottom-color: rgb(226, 226, 226);border-left-color: rgb(226, 226, 226);border-right-color: rgb(226, 226, 226);border-top-color: rgb(226, 226, 226);border-top-style: none;border-top-width: 0px;box-shadow: none;box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 52px;">
            <ul class="nav navbar-nav navbar-right"
                style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;float: right;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 0px;line-height: 26.0799999237061px;list-style-image: none;list-style-position: outside;list-style-type: none;margin-bottom: 0px;margin-left: 0px;margin-right: -8px;margin-top: 0px;padding-left: 0px;"></ul>
        </div>
    </div>
</nav>
<section id="home-intro-1"
         style="padding-top: 60px !important;box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 253px;line-height: 26.0799999237061px;padding-top: 60px;">
    <div class="container"
         style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 193px;line-height: 26.0799999237061px;margin-left: 84.5px;margin-right: 84.5px;padding-left: 8px;padding-right: 8px;">
        <div class="row container"
             style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 193px;line-height: 26.0799999237061px;margin-left: -8px;margin-right: -8px;padding-left: 8px;padding-right: 8px;">
            <div class="col-md-12"
                 style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;float: left;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 193px;line-height: 26.0799999237061px;min-height: 1px;padding-left: 8px;padding-right: 8px;position: relative;">
                <h2 style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 34px;font-weight: 500;height: 37px;line-height: 37.4000015258789px;margin-bottom: 13px;margin-top: 26px;">
                    ${title}</h2>

                <p style="box-sizing: border-box;color: rgb(64, 64, 64);display: block;font-family: 'Roboto Condensed', 'Arial Narrow', Helvetica, sans-serif;font-size: 16px;height: 26px;line-height: 26.0799999237061px;margin-bottom: 13px;margin-left: 0px;margin-right: 0px;margin-top: 0px;">
                    ${text}</p>
                </br>
                Regards,
                </br>
                The Hortonworks Team
            </div>
        </div>
    </div>
</section>
</body>
</html>
