// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutClusterV4Reader is a Reader for the PutClusterV4 structure.
type PutClusterV4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutClusterV4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPutClusterV4Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPutClusterV4Default creates a PutClusterV4Default with default headers values
func NewPutClusterV4Default(code int) *PutClusterV4Default {
	return &PutClusterV4Default{
		_statusCode: code,
	}
}

/*PutClusterV4Default handles this case with default header values.

successful operation
*/
type PutClusterV4Default struct {
	_statusCode int
}

// Code gets the status code for the put cluster v4 default response
func (o *PutClusterV4Default) Code() int {
	return o._statusCode
}

func (o *PutClusterV4Default) Error() string {
	return fmt.Sprintf("[PUT /v4/{workspaceId}/stacks/{name}/cluster][%d] putClusterV4 default ", o._statusCode)
}

func (o *PutClusterV4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
