package flexsubscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// PutDefaultFlexSubscriptionByIDReader is a Reader for the PutDefaultFlexSubscriptionByID structure.
type PutDefaultFlexSubscriptionByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutDefaultFlexSubscriptionByIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewPutDefaultFlexSubscriptionByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutDefaultFlexSubscriptionByIDDefault creates a PutDefaultFlexSubscriptionByIDDefault with default headers values
func NewPutDefaultFlexSubscriptionByIDDefault(code int) *PutDefaultFlexSubscriptionByIDDefault {
	return &PutDefaultFlexSubscriptionByIDDefault{
		_statusCode: code,
	}
}

/*PutDefaultFlexSubscriptionByIDDefault handles this case with default header values.

successful operation
*/
type PutDefaultFlexSubscriptionByIDDefault struct {
	_statusCode int
}

// Code gets the status code for the put default flex subscription by id default response
func (o *PutDefaultFlexSubscriptionByIDDefault) Code() int {
	return o._statusCode
}

func (o *PutDefaultFlexSubscriptionByIDDefault) Error() string {
	return fmt.Sprintf("[PUT /flexsubscriptions/setdefault/{id}][%d] putDefaultFlexSubscriptionById default ", o._statusCode)
}

func (o *PutDefaultFlexSubscriptionByIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
