package accountpreferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/validate"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// IsPlatformSelectionDisabledReader is a Reader for the IsPlatformSelectionDisabled structure.
type IsPlatformSelectionDisabledReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *IsPlatformSelectionDisabledReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIsPlatformSelectionDisabledOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIsPlatformSelectionDisabledOK creates a IsPlatformSelectionDisabledOK with default headers values
func NewIsPlatformSelectionDisabledOK() *IsPlatformSelectionDisabledOK {
	return &IsPlatformSelectionDisabledOK{}
}

/*IsPlatformSelectionDisabledOK handles this case with default header values.

successful operation
*/
type IsPlatformSelectionDisabledOK struct {
	Payload IsPlatformSelectionDisabledOKBodyBody
}

func (o *IsPlatformSelectionDisabledOK) Error() string {
	return fmt.Sprintf("[GET /accountpreferences/isplatformselectiondisabled][%d] isPlatformSelectionDisabledOK  %+v", 200, o.Payload)
}

func (o *IsPlatformSelectionDisabledOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*IsPlatformSelectionDisabledOKBodyBody is platform selection disabled o k body body

swagger:model IsPlatformSelectionDisabledOKBodyBody
*/
type IsPlatformSelectionDisabledOKBodyBody map[string]bool

// Validate validates this is platform selection disabled o k body body
func (o IsPlatformSelectionDisabledOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("isPlatformSelectionDisabledOK", "body", o); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
