// Code generated by go-swagger; DO NOT EDIT.

package v3_workspace_id_flexsubscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/dataplane/api/model"
)

// CreateFlexSubscriptionInWorkspaceReader is a Reader for the CreateFlexSubscriptionInWorkspace structure.
type CreateFlexSubscriptionInWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFlexSubscriptionInWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateFlexSubscriptionInWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateFlexSubscriptionInWorkspaceOK creates a CreateFlexSubscriptionInWorkspaceOK with default headers values
func NewCreateFlexSubscriptionInWorkspaceOK() *CreateFlexSubscriptionInWorkspaceOK {
	return &CreateFlexSubscriptionInWorkspaceOK{}
}

/*CreateFlexSubscriptionInWorkspaceOK handles this case with default header values.

successful operation
*/
type CreateFlexSubscriptionInWorkspaceOK struct {
	Payload *model.FlexSubscriptionResponse
}

func (o *CreateFlexSubscriptionInWorkspaceOK) Error() string {
	return fmt.Sprintf("[POST /v3/{workspaceId}/flexsubscriptions][%d] createFlexSubscriptionInWorkspaceOK  %+v", 200, o.Payload)
}

func (o *CreateFlexSubscriptionInWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.FlexSubscriptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
