package com.sequenceiq.cloudbreak.api.endpoint.v4.database.base;

public enum DatabaseType {
    HIVE,
    RANGER,
    DRUID,
    SUPERSET,
    OOZIE,
    AMBARI,
    CLOUDERA_MANAGER,
    CLOUDERA_MANAGER_MANAGEMENT_SERVICE_ACTIVITY_MONITOR,
    CLOUDERA_MANAGER_MANAGEMENT_SERVICE_REPORTS_MANAGER,
    CLOUDERA_MANAGER_MANAGEMENT_SERVICE_NAVIGATOR,
    CLOUDERA_MANAGER_MANAGEMENT_SERVICE_NAVIGATOR_METASERVER,
    BEACON,
    REGISTRY,
    HIVE_DAS
}
