// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RedeploySdxByCrnReader is a Reader for the RedeploySdxByCrn structure.
type RedeploySdxByCrnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RedeploySdxByCrnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewRedeploySdxByCrnDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewRedeploySdxByCrnDefault creates a RedeploySdxByCrnDefault with default headers values
func NewRedeploySdxByCrnDefault(code int) *RedeploySdxByCrnDefault {
	return &RedeploySdxByCrnDefault{
		_statusCode: code,
	}
}

/*RedeploySdxByCrnDefault handles this case with default header values.

successful operation
*/
type RedeploySdxByCrnDefault struct {
	_statusCode int
}

// Code gets the status code for the redeploy sdx by crn default response
func (o *RedeploySdxByCrnDefault) Code() int {
	return o._statusCode
}

func (o *RedeploySdxByCrnDefault) Error() string {
	return fmt.Sprintf("[POST /sdx/crn/{clusterCrn}/redeploy][%d] redeploySdxByCrn default ", o._statusCode)
}

func (o *RedeploySdxByCrnDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
