name: "config-change-migration-tests"
tests:
  - name: "config-change-migration-tests"
    classes:
      - name: com.sequenceiq.it.cloudbreak.testcase.mock.MockSdxRepairTests
        includedMethods:
          - repairTerminatedMaster
