// Code generated by go-swagger; DO NOT EDIT.

package v3_organization_id_credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCredentialInOrganizationParams creates a new DeleteCredentialInOrganizationParams object
// with the default values initialized.
func NewDeleteCredentialInOrganizationParams() *DeleteCredentialInOrganizationParams {
	var ()
	return &DeleteCredentialInOrganizationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCredentialInOrganizationParamsWithTimeout creates a new DeleteCredentialInOrganizationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCredentialInOrganizationParamsWithTimeout(timeout time.Duration) *DeleteCredentialInOrganizationParams {
	var ()
	return &DeleteCredentialInOrganizationParams{

		timeout: timeout,
	}
}

// NewDeleteCredentialInOrganizationParamsWithContext creates a new DeleteCredentialInOrganizationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCredentialInOrganizationParamsWithContext(ctx context.Context) *DeleteCredentialInOrganizationParams {
	var ()
	return &DeleteCredentialInOrganizationParams{

		Context: ctx,
	}
}

// NewDeleteCredentialInOrganizationParamsWithHTTPClient creates a new DeleteCredentialInOrganizationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCredentialInOrganizationParamsWithHTTPClient(client *http.Client) *DeleteCredentialInOrganizationParams {
	var ()
	return &DeleteCredentialInOrganizationParams{
		HTTPClient: client,
	}
}

/*DeleteCredentialInOrganizationParams contains all the parameters to send to the API endpoint
for the delete credential in organization operation typically these are written to a http.Request
*/
type DeleteCredentialInOrganizationParams struct {

	/*Name*/
	Name string
	/*OrganizationID*/
	OrganizationID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) WithTimeout(timeout time.Duration) *DeleteCredentialInOrganizationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) WithContext(ctx context.Context) *DeleteCredentialInOrganizationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) WithHTTPClient(client *http.Client) *DeleteCredentialInOrganizationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) WithName(name string) *DeleteCredentialInOrganizationParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) SetName(name string) {
	o.Name = name
}

// WithOrganizationID adds the organizationID to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) WithOrganizationID(organizationID int64) *DeleteCredentialInOrganizationParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete credential in organization params
func (o *DeleteCredentialInOrganizationParams) SetOrganizationID(organizationID int64) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCredentialInOrganizationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", swag.FormatInt64(o.OrganizationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
