package com.sequenceiq.periscope.api.model;

public enum TriggerStatus {
    METRICS_COLLECTION_SUCCESS,
    METRICS_COLLECTION_FAILED,

    MANDATORY_UPSCALE,
    MANDATORY_DOWNSCALE,

    UPSCALE_TRIGGER_SUCCESS,
    UPSCALE_TRIGGER_FAILED,

    DOWNSCALE_TRIGGER_SUCCESS,
    DOWNSCALE_TRIGGER_FAILED,

    SCALING_FLOW_IN_PROGRESS,
    SCALING_FLOW_SUCCESS,
    SCALING_FLOW_FAILED
}
