// Code generated by go-swagger; DO NOT EDIT.

package v1events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStructuredEventsParams creates a new GetStructuredEventsParams object
// with the default values initialized.
func NewGetStructuredEventsParams() *GetStructuredEventsParams {
	var ()
	return &GetStructuredEventsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStructuredEventsParamsWithTimeout creates a new GetStructuredEventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStructuredEventsParamsWithTimeout(timeout time.Duration) *GetStructuredEventsParams {
	var ()
	return &GetStructuredEventsParams{

		timeout: timeout,
	}
}

// NewGetStructuredEventsParamsWithContext creates a new GetStructuredEventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStructuredEventsParamsWithContext(ctx context.Context) *GetStructuredEventsParams {
	var ()
	return &GetStructuredEventsParams{

		Context: ctx,
	}
}

// NewGetStructuredEventsParamsWithHTTPClient creates a new GetStructuredEventsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStructuredEventsParamsWithHTTPClient(client *http.Client) *GetStructuredEventsParams {
	var ()
	return &GetStructuredEventsParams{
		HTTPClient: client,
	}
}

/*GetStructuredEventsParams contains all the parameters to send to the API endpoint
for the get structured events operation typically these are written to a http.Request
*/
type GetStructuredEventsParams struct {

	/*StackID*/
	StackID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get structured events params
func (o *GetStructuredEventsParams) WithTimeout(timeout time.Duration) *GetStructuredEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get structured events params
func (o *GetStructuredEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get structured events params
func (o *GetStructuredEventsParams) WithContext(ctx context.Context) *GetStructuredEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get structured events params
func (o *GetStructuredEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get structured events params
func (o *GetStructuredEventsParams) WithHTTPClient(client *http.Client) *GetStructuredEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get structured events params
func (o *GetStructuredEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStackID adds the stackID to the get structured events params
func (o *GetStructuredEventsParams) WithStackID(stackID int64) *GetStructuredEventsParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get structured events params
func (o *GetStructuredEventsParams) SetStackID(stackID int64) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStructuredEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param stackId
	if err := r.SetPathParam("stackId", swag.FormatInt64(o.StackID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
