package com.sequenceiq.cloudbreak.domain.stack;

public enum StackPatchType {
    UNBOUND_RESTART,
    LOGGING_AGENT_AUTO_RESTART,
    LOGGING_AGENT_AUTO_RESTART_V2,
    METERING_AZURE_METADATA,
    METERING_FOLLOW_INODES,
    CLUSTER_PUBLIC_ENDPOINT,
    MOCK,
    DISABLE_REGION_FOR_FLUENTD,
    COLLECT_DB_ENGINE_VERSION,
    USER_DATA_MIGRATION,
    USER_DATA_CCMV2_SETUP,
    UPDATE_OUTDATED_VAULT_SECRETS,
    EMBEDDED_DB_CERTIFICATE_ROTATION,
    GCP_SUBNET_ID_FIX,
    UNKNOWN
}
