// Code generated by go-swagger; DO NOT EDIT.

package freeipa_environment_name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new freeipa environment name API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for freeipa environment name API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateFreeIPA creates free IP a instance
*/
func (a *Client) CreateFreeIPA(params *CreateFreeIPAParams) (*CreateFreeIPAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateFreeIPAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createFreeIPA",
		Method:             "POST",
		PathPattern:        "/freeipa/{environmentName}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateFreeIPAReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateFreeIPAOK), nil

}

/*
DeleteFreeIPA deletes free IP a instance
*/
func (a *Client) DeleteFreeIPA(params *DeleteFreeIPAParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteFreeIPAParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteFreeIPA",
		Method:             "DELETE",
		PathPattern:        "/freeipa/{environmentName}/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteFreeIPAReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
