package clustertemplates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// DeleteClustertemplatesIDReader is a Reader for the DeleteClustertemplatesID structure.
type DeleteClustertemplatesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteClustertemplatesIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewDeleteClustertemplatesIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteClustertemplatesIDDefault creates a DeleteClustertemplatesIDDefault with default headers values
func NewDeleteClustertemplatesIDDefault(code int) *DeleteClustertemplatesIDDefault {
	return &DeleteClustertemplatesIDDefault{
		_statusCode: code,
	}
}

/*DeleteClustertemplatesIDDefault handles this case with default header values.

successful operation
*/
type DeleteClustertemplatesIDDefault struct {
	_statusCode int
}

// Code gets the status code for the delete clustertemplates ID default response
func (o *DeleteClustertemplatesIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteClustertemplatesIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /clustertemplates/{id}][%d] DeleteClustertemplatesID default ", o._statusCode)
}

func (o *DeleteClustertemplatesIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
