// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_kubernetes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteKubernetesConfigsInWorkspaceParams creates a new DeleteKubernetesConfigsInWorkspaceParams object
// with the default values initialized.
func NewDeleteKubernetesConfigsInWorkspaceParams() *DeleteKubernetesConfigsInWorkspaceParams {
	var ()
	return &DeleteKubernetesConfigsInWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteKubernetesConfigsInWorkspaceParamsWithTimeout creates a new DeleteKubernetesConfigsInWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteKubernetesConfigsInWorkspaceParamsWithTimeout(timeout time.Duration) *DeleteKubernetesConfigsInWorkspaceParams {
	var ()
	return &DeleteKubernetesConfigsInWorkspaceParams{

		timeout: timeout,
	}
}

// NewDeleteKubernetesConfigsInWorkspaceParamsWithContext creates a new DeleteKubernetesConfigsInWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteKubernetesConfigsInWorkspaceParamsWithContext(ctx context.Context) *DeleteKubernetesConfigsInWorkspaceParams {
	var ()
	return &DeleteKubernetesConfigsInWorkspaceParams{

		Context: ctx,
	}
}

// NewDeleteKubernetesConfigsInWorkspaceParamsWithHTTPClient creates a new DeleteKubernetesConfigsInWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteKubernetesConfigsInWorkspaceParamsWithHTTPClient(client *http.Client) *DeleteKubernetesConfigsInWorkspaceParams {
	var ()
	return &DeleteKubernetesConfigsInWorkspaceParams{
		HTTPClient: client,
	}
}

/*DeleteKubernetesConfigsInWorkspaceParams contains all the parameters to send to the API endpoint
for the delete kubernetes configs in workspace operation typically these are written to a http.Request
*/
type DeleteKubernetesConfigsInWorkspaceParams struct {

	/*Body*/
	Body []string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) WithTimeout(timeout time.Duration) *DeleteKubernetesConfigsInWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) WithContext(ctx context.Context) *DeleteKubernetesConfigsInWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) WithHTTPClient(client *http.Client) *DeleteKubernetesConfigsInWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) WithBody(body []string) *DeleteKubernetesConfigsInWorkspaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) SetBody(body []string) {
	o.Body = body
}

// WithWorkspaceID adds the workspaceID to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) WithWorkspaceID(workspaceID int64) *DeleteKubernetesConfigsInWorkspaceParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the delete kubernetes configs in workspace params
func (o *DeleteKubernetesConfigsInWorkspaceParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteKubernetesConfigsInWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
