package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// DeleteNetworksAccountNameReader is a Reader for the DeleteNetworksAccountName structure.
type DeleteNetworksAccountNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteNetworksAccountNameReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	default:
		result := NewDeleteNetworksAccountNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteNetworksAccountNameDefault creates a DeleteNetworksAccountNameDefault with default headers values
func NewDeleteNetworksAccountNameDefault(code int) *DeleteNetworksAccountNameDefault {
	return &DeleteNetworksAccountNameDefault{
		_statusCode: code,
	}
}

/*DeleteNetworksAccountNameDefault handles this case with default header values.

successful operation
*/
type DeleteNetworksAccountNameDefault struct {
	_statusCode int
}

// Code gets the status code for the delete networks account name default response
func (o *DeleteNetworksAccountNameDefault) Code() int {
	return o._statusCode
}

func (o *DeleteNetworksAccountNameDefault) Error() string {
	return fmt.Sprintf("[DELETE /networks/account/{name}][%d] DeleteNetworksAccountName default ", o._statusCode)
}

func (o *DeleteNetworksAccountNameDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
