package com.sequenceiq.cloudbreak.validation;

public enum AllServiceTypes {
    SOLR,
    TEZ,
    STREAMS_REPLICATION_MANAGER,
    NIFIREGISTRY,
    HBASE,
    SPARK3_ON_YARN,
    ATLAS,
    HIVE,
    QUEUEMANAGER,
    KUDU,
    HUE,
    SCHEMAREGISTRY,
    NIFI,
    OMID,
    SPARK_ON_YARN,
    LIVY,
    PHOENIX,
    HDFS,
    OOZIE,
    SQOOP_CLIENT,
    ZOOKEEPER,
    YARN,
    KNOX,
    RANGER,
    HIVE_ON_TEZ,
    ZEPPELIN,
    CORE_SETTINGS,
    STREAMS_MESSAGING_MANAGER,
    DAS,
    KAFKA,
    LIVY_FOR_SPARK3,
    IMPALA,
    FLINK,
    HUE_QUERY_PROCESSOR
}
