services:
  HIVE_SERVER:
    config-name: hive-site
    port-key: hive.server2.thrift.http.port

  HIVE_SERVER_INTERACTIVE:
    config-name: hive-interactive-site
    port-key: hive.server2.thrift.http.port

  SPARK_JOBHISTORYSERVER:
    config-name: spark-defaults
    port-key: spark.history.ui.port

  ZEPPELIN:
    config-name: zeppelin-config
    port-key: zeppelin.server.port

  # WEBHDFS
  NAMENODE:
    config-name: hdfs-site
    host-key: dfs.namenode.http-address

  # YARN
  RESOURCEMANAGER:
    config-name: yarn-site
    host-key: yarn.resourcemanager.webapp.address
