// Code generated by go-swagger; DO NOT EDIT.

package v1kerberosmgmt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteServicePrinciapalV1Reader is a Reader for the DeleteServicePrinciapalV1 structure.
type DeleteServicePrinciapalV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServicePrinciapalV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteServicePrinciapalV1Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteServicePrinciapalV1Default creates a DeleteServicePrinciapalV1Default with default headers values
func NewDeleteServicePrinciapalV1Default(code int) *DeleteServicePrinciapalV1Default {
	return &DeleteServicePrinciapalV1Default{
		_statusCode: code,
	}
}

/*DeleteServicePrinciapalV1Default handles this case with default header values.

successful operation
*/
type DeleteServicePrinciapalV1Default struct {
	_statusCode int
}

// Code gets the status code for the delete service princiapal v1 default response
func (o *DeleteServicePrinciapalV1Default) Code() int {
	return o._statusCode
}

func (o *DeleteServicePrinciapalV1Default) Error() string {
	return fmt.Sprintf("[DELETE /v1/kerberosmgmt/serviceprincipal][%d] deleteServicePrinciapalV1 default ", o._statusCode)
}

func (o *DeleteServicePrinciapalV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
