name: 'Real UMS Test'
description: 'Run Real UMS integration tests'

runs:
  using: "composite"
  steps:
    - name: real_ums_test
      shell: bash
      run: |-
        export AWS=false
        export INTEGRATIONTEST_SUITE_FILES=file:/it/src/main/resources/testsuites/v4/mock/real-ums-mock-tests.yaml
        export INTEGRATIONTEST_UMS_HOST=usermanagement.internal-insecure.dps.mow-dev.cloudera.com
        export INTEGRATIONTEST_UMS_PORT=80
        export INTEGRATIONTEST_CDL_HOST=thunderhead-mock
        export INTEGRATIONTEST_CDL_PORT=8982
        export CUSTOM_UMS_SHORT_TIMEOUT=10
        export INTEGRATIONTEST_UMS_DEPLOYMENTKEY=dev
        export INTEGRATIONTEST_UMS_ACCOUNTKEY=e2e
        export INTEGRATIONTEST_UMS_JSONSECRET_DESTINATIONPATH=./src/main/resources/ums-users/api-credentials.json
        echo $REAL_UMS_USERS_DEV

        make real-ums-test-steps_real_ums_test
    - name: real_ums_test_show_result
      if: ${{ always() }}
      uses: Kitchen/RE-thirdparty-actions/actions/testng-report@main
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN}}
      with:
        fail_if_empty: false
        commit: ${{ github.event.pull_request.head.sha }}
        show_skipped: true
        check_name: 'Real UMS Test Report'
        report_paths: |
          **/testng-results.xml
    - name: real_ums_test_compress_results
      if: ${{ always() }}
      shell: bash
      run: |-
        cd integration-test
        make compress-results
    - name: real_ums_test_collect_service_artifacts
      uses: cloudbreak/cloudbreak-github-actions/actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: real-ums-test-artifact
        retention-days: 5
        path: |
          integration-test/integcb-logs.tar.gz
          integration-test/cloudbreak.log
          integration-test/datalake.log
          integration-test/redbeams.log
          integration-test/environment.log
          integration-test/freeipa.log
          integration-test/thunderhead-mock.log
          integration-test/jumpgate-interop.log
          integration-test/jumpgate-admin.log
          integration-test/jumpgate-proxy.log
          integration-test/dev-gateway.log
          integration-test/core-gateway.log
          integration-test/envoy.log
    - name: real_ums_test_collect_test_artifacts
      uses: cloudbreak/cloudbreak-github-actions/actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: real-ums-test-artifact
        retention-days: 5
        path: |
          integration-test/suites.tar.gz
