// Code generated by go-swagger; DO NOT EDIT.

package internalsdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-sdx/model"
)

// CreateInternalSdxReader is a Reader for the CreateInternalSdx structure.
type CreateInternalSdxReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInternalSdxReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateInternalSdxOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateInternalSdxOK creates a CreateInternalSdxOK with default headers values
func NewCreateInternalSdxOK() *CreateInternalSdxOK {
	return &CreateInternalSdxOK{}
}

/*CreateInternalSdxOK handles this case with default header values.

successful operation
*/
type CreateInternalSdxOK struct {
	Payload *model.SdxClusterResponse
}

func (o *CreateInternalSdxOK) Error() string {
	return fmt.Sprintf("[POST /internal/sdx/{name}][%d] createInternalSdxOK  %+v", 200, o.Payload)
}

func (o *CreateInternalSdxOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.SdxClusterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
