// Code generated by go-swagger; DO NOT EDIT.

package v1freeipa

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-freeipa/model"
)

// NewAddDNSZoneForSubnetIdsV1Params creates a new AddDNSZoneForSubnetIdsV1Params object
// with the default values initialized.
func NewAddDNSZoneForSubnetIdsV1Params() *AddDNSZoneForSubnetIdsV1Params {
	var ()
	return &AddDNSZoneForSubnetIdsV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddDNSZoneForSubnetIdsV1ParamsWithTimeout creates a new AddDNSZoneForSubnetIdsV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddDNSZoneForSubnetIdsV1ParamsWithTimeout(timeout time.Duration) *AddDNSZoneForSubnetIdsV1Params {
	var ()
	return &AddDNSZoneForSubnetIdsV1Params{

		timeout: timeout,
	}
}

// NewAddDNSZoneForSubnetIdsV1ParamsWithContext creates a new AddDNSZoneForSubnetIdsV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewAddDNSZoneForSubnetIdsV1ParamsWithContext(ctx context.Context) *AddDNSZoneForSubnetIdsV1Params {
	var ()
	return &AddDNSZoneForSubnetIdsV1Params{

		Context: ctx,
	}
}

// NewAddDNSZoneForSubnetIdsV1ParamsWithHTTPClient creates a new AddDNSZoneForSubnetIdsV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddDNSZoneForSubnetIdsV1ParamsWithHTTPClient(client *http.Client) *AddDNSZoneForSubnetIdsV1Params {
	var ()
	return &AddDNSZoneForSubnetIdsV1Params{
		HTTPClient: client,
	}
}

/*AddDNSZoneForSubnetIdsV1Params contains all the parameters to send to the API endpoint
for the add Dns zone for subnet ids v1 operation typically these are written to a http.Request
*/
type AddDNSZoneForSubnetIdsV1Params struct {

	/*Body*/
	Body *model.AddDNSZoneForSubnetIdsV1Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) WithTimeout(timeout time.Duration) *AddDNSZoneForSubnetIdsV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) WithContext(ctx context.Context) *AddDNSZoneForSubnetIdsV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) WithHTTPClient(client *http.Client) *AddDNSZoneForSubnetIdsV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) WithBody(body *model.AddDNSZoneForSubnetIdsV1Request) *AddDNSZoneForSubnetIdsV1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add Dns zone for subnet ids v1 params
func (o *AddDNSZoneForSubnetIdsV1Params) SetBody(body *model.AddDNSZoneForSubnetIdsV1Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddDNSZoneForSubnetIdsV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
