// Code generated by go-swagger; DO NOT EDIT.

package v1freeipa

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFreeIpaRootCertificateByEnvironmentV1Params creates a new GetFreeIpaRootCertificateByEnvironmentV1Params object
// with the default values initialized.
func NewGetFreeIpaRootCertificateByEnvironmentV1Params() *GetFreeIpaRootCertificateByEnvironmentV1Params {
	var ()
	return &GetFreeIpaRootCertificateByEnvironmentV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFreeIpaRootCertificateByEnvironmentV1ParamsWithTimeout creates a new GetFreeIpaRootCertificateByEnvironmentV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFreeIpaRootCertificateByEnvironmentV1ParamsWithTimeout(timeout time.Duration) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	var ()
	return &GetFreeIpaRootCertificateByEnvironmentV1Params{

		timeout: timeout,
	}
}

// NewGetFreeIpaRootCertificateByEnvironmentV1ParamsWithContext creates a new GetFreeIpaRootCertificateByEnvironmentV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetFreeIpaRootCertificateByEnvironmentV1ParamsWithContext(ctx context.Context) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	var ()
	return &GetFreeIpaRootCertificateByEnvironmentV1Params{

		Context: ctx,
	}
}

// NewGetFreeIpaRootCertificateByEnvironmentV1ParamsWithHTTPClient creates a new GetFreeIpaRootCertificateByEnvironmentV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFreeIpaRootCertificateByEnvironmentV1ParamsWithHTTPClient(client *http.Client) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	var ()
	return &GetFreeIpaRootCertificateByEnvironmentV1Params{
		HTTPClient: client,
	}
}

/*GetFreeIpaRootCertificateByEnvironmentV1Params contains all the parameters to send to the API endpoint
for the get free ipa root certificate by environment v1 operation typically these are written to a http.Request
*/
type GetFreeIpaRootCertificateByEnvironmentV1Params struct {

	/*Environment*/
	Environment *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) WithTimeout(timeout time.Duration) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) WithContext(ctx context.Context) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) WithHTTPClient(client *http.Client) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironment adds the environment to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) WithEnvironment(environment *string) *GetFreeIpaRootCertificateByEnvironmentV1Params {
	o.SetEnvironment(environment)
	return o
}

// SetEnvironment adds the environment to the get free ipa root certificate by environment v1 params
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) SetEnvironment(environment *string) {
	o.Environment = environment
}

// WriteToRequest writes these params to a swagger request
func (o *GetFreeIpaRootCertificateByEnvironmentV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Environment != nil {

		// query param environment
		var qrEnvironment string
		if o.Environment != nil {
			qrEnvironment = *o.Environment
		}
		qEnvironment := qrEnvironment
		if qEnvironment != "" {
			if err := r.SetQueryParam("environment", qEnvironment); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
