// Code generated by go-swagger; DO NOT EDIT.

package v1util

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCheckClientVersionParams creates a new CheckClientVersionParams object
// with the default values initialized.
func NewCheckClientVersionParams() *CheckClientVersionParams {
	var ()
	return &CheckClientVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckClientVersionParamsWithTimeout creates a new CheckClientVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckClientVersionParamsWithTimeout(timeout time.Duration) *CheckClientVersionParams {
	var ()
	return &CheckClientVersionParams{

		timeout: timeout,
	}
}

// NewCheckClientVersionParamsWithContext creates a new CheckClientVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckClientVersionParamsWithContext(ctx context.Context) *CheckClientVersionParams {
	var ()
	return &CheckClientVersionParams{

		Context: ctx,
	}
}

// NewCheckClientVersionParamsWithHTTPClient creates a new CheckClientVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckClientVersionParamsWithHTTPClient(client *http.Client) *CheckClientVersionParams {
	var ()
	return &CheckClientVersionParams{
		HTTPClient: client,
	}
}

/*CheckClientVersionParams contains all the parameters to send to the API endpoint
for the check client version operation typically these are written to a http.Request
*/
type CheckClientVersionParams struct {

	/*Version*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check client version params
func (o *CheckClientVersionParams) WithTimeout(timeout time.Duration) *CheckClientVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check client version params
func (o *CheckClientVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check client version params
func (o *CheckClientVersionParams) WithContext(ctx context.Context) *CheckClientVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check client version params
func (o *CheckClientVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check client version params
func (o *CheckClientVersionParams) WithHTTPClient(client *http.Client) *CheckClientVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check client version params
func (o *CheckClientVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersion adds the version to the check client version params
func (o *CheckClientVersionParams) WithVersion(version string) *CheckClientVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the check client version params
func (o *CheckClientVersionParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *CheckClientVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
