// Code generated by go-swagger; DO NOT EDIT.

package v1util

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewGetFileSystemParametersParams creates a new GetFileSystemParametersParams object
// with the default values initialized.
func NewGetFileSystemParametersParams() *GetFileSystemParametersParams {
	var ()
	return &GetFileSystemParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileSystemParametersParamsWithTimeout creates a new GetFileSystemParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFileSystemParametersParamsWithTimeout(timeout time.Duration) *GetFileSystemParametersParams {
	var ()
	return &GetFileSystemParametersParams{

		timeout: timeout,
	}
}

// NewGetFileSystemParametersParamsWithContext creates a new GetFileSystemParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFileSystemParametersParamsWithContext(ctx context.Context) *GetFileSystemParametersParams {
	var ()
	return &GetFileSystemParametersParams{

		Context: ctx,
	}
}

// NewGetFileSystemParametersParamsWithHTTPClient creates a new GetFileSystemParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFileSystemParametersParamsWithHTTPClient(client *http.Client) *GetFileSystemParametersParams {
	var ()
	return &GetFileSystemParametersParams{
		HTTPClient: client,
	}
}

/*GetFileSystemParametersParams contains all the parameters to send to the API endpoint
for the get file system parameters operation typically these are written to a http.Request
*/
type GetFileSystemParametersParams struct {

	/*Body*/
	Body *model.StructuredParametersQueryRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get file system parameters params
func (o *GetFileSystemParametersParams) WithTimeout(timeout time.Duration) *GetFileSystemParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file system parameters params
func (o *GetFileSystemParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file system parameters params
func (o *GetFileSystemParametersParams) WithContext(ctx context.Context) *GetFileSystemParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file system parameters params
func (o *GetFileSystemParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file system parameters params
func (o *GetFileSystemParametersParams) WithHTTPClient(client *http.Client) *GetFileSystemParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file system parameters params
func (o *GetFileSystemParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get file system parameters params
func (o *GetFileSystemParametersParams) WithBody(body *model.StructuredParametersQueryRequest) *GetFileSystemParametersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get file system parameters params
func (o *GetFileSystemParametersParams) SetBody(body *model.StructuredParametersQueryRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileSystemParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(model.StructuredParametersQueryRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
