// Code generated by go-swagger; DO NOT EDIT.

package v1util

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// GetFileSystemParametersReader is a Reader for the GetFileSystemParameters structure.
type GetFileSystemParametersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileSystemParametersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFileSystemParametersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFileSystemParametersOK creates a GetFileSystemParametersOK with default headers values
func NewGetFileSystemParametersOK() *GetFileSystemParametersOK {
	return &GetFileSystemParametersOK{}
}

/*GetFileSystemParametersOK handles this case with default header values.

successful operation
*/
type GetFileSystemParametersOK struct {
	Payload *model.StructuredParameterQueriesResponse
}

func (o *GetFileSystemParametersOK) Error() string {
	return fmt.Sprintf("[POST /v1/util/filesystem-parameters][%d] getFileSystemParametersOK  %+v", 200, o.Payload)
}

func (o *GetFileSystemParametersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.StructuredParameterQueriesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
