package com.sequenceiq.cloudbreak.api.endpoint.v4.stacks.response.database;

public enum DatabaseServerStatus {

    REQUESTED,
    CREATE_IN_PROGRESS,
    AVAILABLE,
    UPDATE_IN_PROGRESS,
    UPDATE_REQUESTED,
    UPDATE_FAILED,
    CREATE_FAILED,
    ENABLE_SECURITY_FAILED,
    DELETE_REQUESTED,
    PRE_DELETE_IN_PROGRESS,
    DELETE_IN_PROGRESS,
    DELETE_FAILED,
    DELETE_COMPLETED,
    STOPPED,
    SSL_ROTATED,
    STOP_REQUESTED,
    SSL_ROTATE_REQUESTED,
    START_REQUESTED,
    STOP_IN_PROGRESS,
    SSL_ROTATE_IN_PROGRESS,
    START_IN_PROGRESS,
    START_FAILED,
    STOP_FAILED,
    SSL_ROTATE_FAILED,
    WAIT_FOR_SYNC,
    MAINTENANCE_MODE_ENABLED,
    UPGRADE_REQUESTED,
    UPGRADE_IN_PROGRESS,
    UPGRADE_FAILED,
    VALIDATE_UPGRADE_REQUESTED,
    VALIDATE_UPGRADE_IN_PROGRESS,
    VALIDATE_UPGRADE_FAILED,
    DB_SSL_MIGRATION_COMPLETED,
    DB_SSL_MIGRATION_REQUESTED,
    DB_SSL_MIGRATION_IN_PROGRESS,
    DB_SSL_MIGRATION_FAILED,
    UNKNOWN;

    public boolean isAvailableForUpgrade() {
        return AVAILABLE.equals(this)
                || UPGRADE_FAILED.equals(this)
                || VALIDATE_UPGRADE_FAILED.equals(this);
    }
}