// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SuccessDetailsV1 success details v1
// swagger:model SuccessDetailsV1
type SuccessDetailsV1 struct {

	// environment
	Environment string `json:"environment,omitempty"`
}

// Validate validates this success details v1
func (m *SuccessDetailsV1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SuccessDetailsV1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SuccessDetailsV1) UnmarshalBinary(b []byte) error {
	var res SuccessDetailsV1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
