package com.sequenceiq.cloudbreak.core.flow2.chain;

public class FlowChainTriggers {

    public static final String FULL_PROVISION_TRIGGER_EVENT = "FULL_PROVISION_TRIGGER_EVENT";

    public static final String RECOVERY_PROVISION_TRIGGER_EVENT = "RECOVERY_PROVISION_TRIGGER_EVENT";

    public static final String CLUSTER_RESET_CHAIN_TRIGGER_EVENT = "CLUSTER_RESET_CHAIN_TRIGGER_EVENT";

    public static final String CLUSTER_UPGRADE_CHAIN_TRIGGER_EVENT = "CLUSTER_UPGRADE_CHAIN_TRIGGER_EVENT";

    public static final String FULL_UPSCALE_TRIGGER_EVENT = "FULL_UPSCALE_TRIGGER_EVENT";

    public static final String STOPSTART_UPSCALE_CHAIN_TRIGGER_EVENT = "STOPSTART_UPSCALE_CHAIN_TRIGGER_EVENT";

    public static final String FULL_DOWNSCALE_TRIGGER_EVENT = "FULL_DOWNSCALE_TRIGGER_EVENT";

    public static final String STOPSTART_DOWNSCALE_CHAIN_TRIGGER_EVENT = "STOPSTART_DOWNSCALE_CHAIN_TRIGGER_EVENT";

    public static final String FULL_DOWNSCALE_MULTIHOSTGROUP_TRIGGER_EVENT = "FULL_DOWNSCALE_MULTIHOSTGROUP_TRIGGER_EVENT";

    public static final String RESTART_INSTANCES_WITH_RDS_RESTART_CHAIN_TRIGGER_EVENT = "RESTART_INSTANCES_WITH_RDS_RESTART_CHAIN_TRIGGER_EVENT";

    public static final String FULL_START_TRIGGER_EVENT = "FULL_START_TRIGGER_EVENT";

    public static final String FULL_STOP_TRIGGER_EVENT = "FULL_STOP_TRIGGER_EVENT";

    public static final String FULL_SYNC_TRIGGER_EVENT = "FULL_SYNC_TRIGGER_EVENT";

    public static final String STACK_REPAIR_TRIGGER_EVENT = "STACK_REPAIR_TRIGGER_EVENT";

    public static final String CLUSTER_REPAIR_TRIGGER_EVENT = "CLUSTER_REPAIR_TRIGGER_EVENT";

    public static final String OS_UPGRADE_BY_UPGRADE_SETS_TRIGGER_EVENT = "OS_UPGRADE_BY_UPGRADE_SETS_TRIGGER_EVENT";

    public static final String TERMINATION_TRIGGER_EVENT = "TERMINATION_TRIGGER_EVENT";

    public static final String PROPER_TERMINATION_TRIGGER_EVENT = "PROPER_TERMINATION_TRIGGER_EVENT";

    public static final String RECOVERY_TERMINATION_TRIGGER_EVENT = "RECOVERY_TERMINATION_TRIGGER_EVENT";

    public static final String STACK_IMAGE_UPDATE_TRIGGER_EVENT = "STACK_IMAGE_UPDATE_TRIGGER_EVENT";

    public static final String CLUSTER_MAINTENANCE_MODE_VALIDATION_TRIGGER_EVENT = "CLUSTER_MAINTENANCE_MODE_VALIDATION_TRIGGER_EVENT";

    public static final String CLUSTER_PROXY_RE_REGISTER_EVENT = "CLUSTER_PROXY_RE_REGISTER_EVENT";

    public static final String RESCHEDULE_STATUS_CHECK_TRIGGER_EVENT = "RESCHEDULE_STATUS_CHECK_TRIGGER_EVENT";

    public static final String DATALAKE_CLUSTER_UPGRADE_CHAIN_TRIGGER_EVENT = "DATALAKE_CLUSTER_UPGRADE_CHAIN_TRIGGER_EVENT";

    public static final String DISTROX_CLUSTER_UPGRADE_CHAIN_TRIGGER_EVENT = "DISTROX_CLUSTER_UPGRADE_CHAIN_TRIGGER_EVENT";

    public static final String CLUSTER_UPGRADE_PREPARATION_CHAIN_TRIGGER_EVENT = "CLUSTER_UPGRADE_PREPARATION_CHAIN_TRIGGER_EVENT";

    public static final String CLUSTER_RECOVERY_CHAIN_TRIGGER_EVENT = "CLUSTER_RECOVERY_CHAIN_TRIGGER_EVENT";

    public static final String ROTATE_CLUSTER_CERTIFICATES_CHAIN_TRIGGER_EVENT = "ROTATE_CLUSTER_CERTIFICATES_CHAIN_TRIGGER_EVENT";

    public static final String DATALAKE_DATABASE_BACKUP_CHAIN_TRIGGER_EVENT = "DATALAKE_DATABASE_BACKUP_CHAIN_TRIGGER_EVENT";

    public static final String UPGRADE_CCM_CHAIN_TRIGGER_EVENT = "UPGRADE_CCM_CHAIN_TRIGGER_EVENT";

    public static final String UPGRADE_RDS_CHAIN_TRIGGER_EVENT = "UPGRADE_RDS_CHAIN_TRIGGER_EVENT";

    public static final String MODIFY_PROXY_CONFIG_CHAIN_TRIGGER_EVENT = "MODIFY_PROXY_CONFIG_CHAIN_TRIGGER_EVENT";

    public static final String REFRESH_ENTITLEMENT_PARAM_CHAIN_TRIGGER_EVENT = "REFRESH_ENTITLEMENT_PARAM_CHAIN_TRIGGER_EVENT";

    public static final String SET_DEFAULT_JAVA_VERSION_CHAIN_TRIGGER_EVENT = "SET_DEFAULT_JAVA_VERSION_CHAIN_TRIGGER_EVENT";

    public static final String CORE_ROOT_VOLUME_UPDATE_TRIGGER_EVENT = "CORE_ROOT_VOLUME_UPDATE_TRIGGER_EVENT";

    public static final String MIGRATE_ZOOKEEPER_TO_KRAFT_CHAIN_TRIGGER_EVENT = "MIGRATE_ZOOKEEPER_TO_KRAFT_CHAIN_TRIGGER_EVENT";

    private FlowChainTriggers() {
    }
}
