package com.sequenceiq.cloudbreak.core.flow2.cluster.datalake.upgrade.validation.event;

import com.sequenceiq.flow.core.FlowEvent;

public enum ClusterUpgradeValidationStateSelectors implements FlowEvent {

    START_CLUSTER_UPGRADE_VALIDATION_INIT_EVENT,
    START_CLUSTER_UPGRADE_IMAGE_VALIDATION_EVENT,
    START_CLUSTER_UPGRADE_DISK_SPACE_VALIDATION_EVENT,
    FINISH_CLUSTER_UPGRADE_DISK_SPACE_VALIDATION_EVENT,
    START_CLUSTER_UPGRADE_SERVICE_VALIDATION_EVENT,
    START_CLUSTER_UPGRADE_FREEIPA_STATUS_VALIDATION_EVENT,
    FINISH_CLUSTER_UPGRADE_FREEIPA_STATUS_VALIDATION_EVENT,
    START_CLUSTER_UPGRADE_EXISTING_UPGRADE_COMMAND_VALIDATION_EVENT,
    FINISH_CLUSTER_UPGRADE_EXISTING_UPGRADE_COMMAND_VALIDATION_EVENT,
    FINISH_CLUSTER_UPGRADE_CLOUDPROVIDER_UPDATECHECK_EVENT,
    FINISH_CLUSTER_UPGRADE_VALIDATION_EVENT,
    FINALIZE_CLUSTER_UPGRADE_VALIDATION_EVENT,
    FAILED_CLUSTER_UPGRADE_VALIDATION_EVENT,
    HANDLED_FAILED_CLUSTER_UPGRADE_VALIDATION_EVENT;

    @Override
    public String event() {
        return name();
    }
}
