package com.sequenceiq.it.cloudbreak

object CloudbreakITContextConstants {
    val CLOUDBREAK_SERVER = "CLOUDBREAK_SERVER"
    val BLUEPRINT_ID = "BLUEPRINT_ID"
    val RECIPE_ID = "RECIPE_ID"
    val TEMPLATE_ID = "TEMPLATE_ID"
    val NETWORK_ID = "NETWORK_ID"
    val SECURITY_GROUP_ID = "SECURITY_GROUP_ID"
    val CREDENTIAL_ID = "CREDENTIAL_ID"
    val STACK_ID = "STACK_ID"
    val HOSTGROUP_ID = "HOSTGROUP_ID"
    val FAILED_TESTS = "FAILED_TESTS"
    val SKIP_REMAINING_SUITETEST_AFTER_ONE_FAILED = "SKIP_REMAINING_SUITETEST_AFTER_ONE_FAILED"
    val AMBARI_USER_ID = "AMBARI_USER"
    val AMBARI_PASSWORD_ID = "AMBARI_PASSWORD"

    val CLOUDBREAK_CLIENT = "CLOUDBREAK_CLIENT"
}
