// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/dataplane/oauthapi/model"
)

// DisableTenantReader is a Reader for the DisableTenant structure.
type DisableTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisableTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDisableTenantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDisableTenantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDisableTenantUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDisableTenantForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDisableTenantInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDisableTenantOK creates a DisableTenantOK with default headers values
func NewDisableTenantOK() *DisableTenantOK {
	return &DisableTenantOK{}
}

/*DisableTenantOK handles this case with default header values.

successful operation
*/
type DisableTenantOK struct {
	Payload []*model.Tenant
}

func (o *DisableTenantOK) Error() string {
	return fmt.Sprintf("[PUT /caas/api/tenants/{tenantName}][%d] disableTenantOK  %+v", 200, o.Payload)
}

func (o *DisableTenantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisableTenantBadRequest creates a DisableTenantBadRequest with default headers values
func NewDisableTenantBadRequest() *DisableTenantBadRequest {
	return &DisableTenantBadRequest{}
}

/*DisableTenantBadRequest handles this case with default header values.

Bad Request
*/
type DisableTenantBadRequest struct {
}

func (o *DisableTenantBadRequest) Error() string {
	return fmt.Sprintf("[PUT /caas/api/tenants/{tenantName}][%d] disableTenantBadRequest ", 400)
}

func (o *DisableTenantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDisableTenantUnauthorized creates a DisableTenantUnauthorized with default headers values
func NewDisableTenantUnauthorized() *DisableTenantUnauthorized {
	return &DisableTenantUnauthorized{}
}

/*DisableTenantUnauthorized handles this case with default header values.

Unauthorized
*/
type DisableTenantUnauthorized struct {
}

func (o *DisableTenantUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /caas/api/tenants/{tenantName}][%d] disableTenantUnauthorized ", 401)
}

func (o *DisableTenantUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDisableTenantForbidden creates a DisableTenantForbidden with default headers values
func NewDisableTenantForbidden() *DisableTenantForbidden {
	return &DisableTenantForbidden{}
}

/*DisableTenantForbidden handles this case with default header values.

Forbidden
*/
type DisableTenantForbidden struct {
}

func (o *DisableTenantForbidden) Error() string {
	return fmt.Sprintf("[PUT /caas/api/tenants/{tenantName}][%d] disableTenantForbidden ", 403)
}

func (o *DisableTenantForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDisableTenantInternalServerError creates a DisableTenantInternalServerError with default headers values
func NewDisableTenantInternalServerError() *DisableTenantInternalServerError {
	return &DisableTenantInternalServerError{}
}

/*DisableTenantInternalServerError handles this case with default header values.

Internal server error
*/
type DisableTenantInternalServerError struct {
}

func (o *DisableTenantInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /caas/api/tenants/{tenantName}][%d] disableTenantInternalServerError ", 500)
}

func (o *DisableTenantInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
