package usages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDeployerUsageParams creates a new GetDeployerUsageParams object
// with the default values initialized.
func NewGetDeployerUsageParams() *GetDeployerUsageParams {
	var ()
	return &GetDeployerUsageParams{}
}

/*GetDeployerUsageParams contains all the parameters to send to the API endpoint
for the get deployer usage operation typically these are written to a http.Request
*/
type GetDeployerUsageParams struct {

	/*Account*/
	Account *string
	/*Cloud*/
	Cloud *string
	/*Filterenddate*/
	Filterenddate *int64
	/*Since*/
	Since *int64
	/*User*/
	User *string
	/*Zone*/
	Zone *string
}

// WithAccount adds the account to the get deployer usage params
func (o *GetDeployerUsageParams) WithAccount(account *string) *GetDeployerUsageParams {
	o.Account = account
	return o
}

// WithCloud adds the cloud to the get deployer usage params
func (o *GetDeployerUsageParams) WithCloud(cloud *string) *GetDeployerUsageParams {
	o.Cloud = cloud
	return o
}

// WithFilterenddate adds the filterenddate to the get deployer usage params
func (o *GetDeployerUsageParams) WithFilterenddate(filterenddate *int64) *GetDeployerUsageParams {
	o.Filterenddate = filterenddate
	return o
}

// WithSince adds the since to the get deployer usage params
func (o *GetDeployerUsageParams) WithSince(since *int64) *GetDeployerUsageParams {
	o.Since = since
	return o
}

// WithUser adds the user to the get deployer usage params
func (o *GetDeployerUsageParams) WithUser(user *string) *GetDeployerUsageParams {
	o.User = user
	return o
}

// WithZone adds the zone to the get deployer usage params
func (o *GetDeployerUsageParams) WithZone(zone *string) *GetDeployerUsageParams {
	o.Zone = zone
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeployerUsageParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Account != nil {

		// query param account
		var qrAccount string
		if o.Account != nil {
			qrAccount = *o.Account
		}
		qAccount := qrAccount
		if qAccount != "" {
			if err := r.SetQueryParam("account", qAccount); err != nil {
				return err
			}
		}

	}

	if o.Cloud != nil {

		// query param cloud
		var qrCloud string
		if o.Cloud != nil {
			qrCloud = *o.Cloud
		}
		qCloud := qrCloud
		if qCloud != "" {
			if err := r.SetQueryParam("cloud", qCloud); err != nil {
				return err
			}
		}

	}

	if o.Filterenddate != nil {

		// query param filterenddate
		var qrFilterenddate int64
		if o.Filterenddate != nil {
			qrFilterenddate = *o.Filterenddate
		}
		qFilterenddate := swag.FormatInt64(qrFilterenddate)
		if qFilterenddate != "" {
			if err := r.SetQueryParam("filterenddate", qFilterenddate); err != nil {
				return err
			}
		}

	}

	if o.Since != nil {

		// query param since
		var qrSince int64
		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {
			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}

	}

	if o.User != nil {

		// query param user
		var qrUser string
		if o.User != nil {
			qrUser = *o.User
		}
		qUser := qrUser
		if qUser != "" {
			if err := r.SetQueryParam("user", qUser); err != nil {
				return err
			}
		}

	}

	if o.Zone != nil {

		// query param zone
		var qrZone string
		if o.Zone != nil {
			qrZone = *o.Zone
		}
		qZone := qrZone
		if qZone != "" {
			if err := r.SetQueryParam("zone", qZone); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
