// Code generated by go-swagger; DO NOT EDIT.

package v1util

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/models_cloudbreak"
)

// NewTestLdapConnectionUtilParams creates a new TestLdapConnectionUtilParams object
// with the default values initialized.
func NewTestLdapConnectionUtilParams() *TestLdapConnectionUtilParams {
	var ()
	return &TestLdapConnectionUtilParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestLdapConnectionUtilParamsWithTimeout creates a new TestLdapConnectionUtilParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestLdapConnectionUtilParamsWithTimeout(timeout time.Duration) *TestLdapConnectionUtilParams {
	var ()
	return &TestLdapConnectionUtilParams{

		timeout: timeout,
	}
}

// NewTestLdapConnectionUtilParamsWithContext creates a new TestLdapConnectionUtilParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestLdapConnectionUtilParamsWithContext(ctx context.Context) *TestLdapConnectionUtilParams {
	var ()
	return &TestLdapConnectionUtilParams{

		Context: ctx,
	}
}

// NewTestLdapConnectionUtilParamsWithHTTPClient creates a new TestLdapConnectionUtilParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTestLdapConnectionUtilParamsWithHTTPClient(client *http.Client) *TestLdapConnectionUtilParams {
	var ()
	return &TestLdapConnectionUtilParams{
		HTTPClient: client,
	}
}

/*TestLdapConnectionUtilParams contains all the parameters to send to the API endpoint
for the test ldap connection util operation typically these are written to a http.Request
*/
type TestLdapConnectionUtilParams struct {

	/*Body*/
	Body *models_cloudbreak.LdapValidationRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) WithTimeout(timeout time.Duration) *TestLdapConnectionUtilParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) WithContext(ctx context.Context) *TestLdapConnectionUtilParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) WithHTTPClient(client *http.Client) *TestLdapConnectionUtilParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) WithBody(body *models_cloudbreak.LdapValidationRequest) *TestLdapConnectionUtilParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the test ldap connection util params
func (o *TestLdapConnectionUtilParams) SetBody(body *models_cloudbreak.LdapValidationRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TestLdapConnectionUtilParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models_cloudbreak.LdapValidationRequest)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
