// Code generated by go-swagger; DO NOT EDIT.

package v3_workspace_id_kubernetesconfigs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// PutKubernetesConfigInWorkspaceReader is a Reader for the PutKubernetesConfigInWorkspace structure.
type PutKubernetesConfigInWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutKubernetesConfigInWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutKubernetesConfigInWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutKubernetesConfigInWorkspaceOK creates a PutKubernetesConfigInWorkspaceOK with default headers values
func NewPutKubernetesConfigInWorkspaceOK() *PutKubernetesConfigInWorkspaceOK {
	return &PutKubernetesConfigInWorkspaceOK{}
}

/*PutKubernetesConfigInWorkspaceOK handles this case with default header values.

successful operation
*/
type PutKubernetesConfigInWorkspaceOK struct {
	Payload *model.KubernetesConfigResponse
}

func (o *PutKubernetesConfigInWorkspaceOK) Error() string {
	return fmt.Sprintf("[PUT /v3/{workspaceId}/kubernetesconfigs][%d] putKubernetesConfigInWorkspaceOK  %+v", 200, o.Payload)
}

func (o *PutKubernetesConfigInWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.KubernetesConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
