package com.sequenceiq.cloudbreak.domain;

public enum ResourceType {
    // AZURE
    AZURE_VIRTUAL_MACHINE,
    AZURE_CLOUD_SERVICE,
    AZURE_RESERVED_IP,
    AZURE_BLOB,
    AZURE_STORAGE,
    AZURE_NETWORK,
    AZURE_AFFINITY_GROUP,
    AZURE_SERVICE_CERTIFICATE,

    // AWS
    CLOUDFORMATION_STACK,
    AWS_RESERVED_IP,

    // OPENSTACK
    HEAT_STACK,

    // GCP
    GCP_DISK,
    GCP_ATTACHED_DISK,
    GCP_RESERVED_IP,
    GCP_NETWORK,
    GCP_FIREWALL_IN,
    GCP_FIREWALL_INTERNAL,
    GCP_ROUTE,
    GCP_INSTANCE,
}
