// Code generated by go-swagger; DO NOT EDIT.

package v1smartsensesubscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSmartSenseSubscriptionParams creates a new GetSmartSenseSubscriptionParams object
// with the default values initialized.
func NewGetSmartSenseSubscriptionParams() *GetSmartSenseSubscriptionParams {

	return &GetSmartSenseSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSmartSenseSubscriptionParamsWithTimeout creates a new GetSmartSenseSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSmartSenseSubscriptionParamsWithTimeout(timeout time.Duration) *GetSmartSenseSubscriptionParams {

	return &GetSmartSenseSubscriptionParams{

		timeout: timeout,
	}
}

// NewGetSmartSenseSubscriptionParamsWithContext creates a new GetSmartSenseSubscriptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSmartSenseSubscriptionParamsWithContext(ctx context.Context) *GetSmartSenseSubscriptionParams {

	return &GetSmartSenseSubscriptionParams{

		Context: ctx,
	}
}

// NewGetSmartSenseSubscriptionParamsWithHTTPClient creates a new GetSmartSenseSubscriptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSmartSenseSubscriptionParamsWithHTTPClient(client *http.Client) *GetSmartSenseSubscriptionParams {

	return &GetSmartSenseSubscriptionParams{
		HTTPClient: client,
	}
}

/*GetSmartSenseSubscriptionParams contains all the parameters to send to the API endpoint
for the get smart sense subscription operation typically these are written to a http.Request
*/
type GetSmartSenseSubscriptionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get smart sense subscription params
func (o *GetSmartSenseSubscriptionParams) WithTimeout(timeout time.Duration) *GetSmartSenseSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get smart sense subscription params
func (o *GetSmartSenseSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get smart sense subscription params
func (o *GetSmartSenseSubscriptionParams) WithContext(ctx context.Context) *GetSmartSenseSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get smart sense subscription params
func (o *GetSmartSenseSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get smart sense subscription params
func (o *GetSmartSenseSubscriptionParams) WithHTTPClient(client *http.Client) *GetSmartSenseSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get smart sense subscription params
func (o *GetSmartSenseSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSmartSenseSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
