package com.sequenceiq.cloudbreak.cloud;

public enum UpdateType {
    INSTANCE_METADATA_UPDATE_TOKEN_REQUIRED,
    INSTANCE_METADATA_UPDATE_TOKEN_OPTIONAL,
    IMAGE_UPDATE,
    VERTICAL_SCALE,
    VERTICAL_SCALE_WITHOUT_INSTANCES;
}
