name: cloudbreak-pull-request-test

env:
  APP_NAME: cloudbreak
  namespace: cloudbreak-pr-${{github.event.number}}
  serviceversion: ${{github.sha}}
  PROJECT: cloudbreak/cloudbreak
  BRANCH: ${{github.base_ref}}
  SOURCE_BRANCH: ${{github.head_ref}}
  PULL_REQUEST_NUMBER: ${{ github.event.number }}
  GITHUB_RUN_ATTEMPT: ${{github.run_attempt}}
  GITHUB_ENV: true

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jira-update:
    permissions: write-all
    name: Jira Update
    runs-on: [cb-ubuntu22]
    env:
      PROJECT: cloudbreak/cloudbreak
      SOURCE_BRANCH: ${{github.head_ref}}
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/jira-update

  unit-test:
    permissions: write-all
    name: Unit Test
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/unit-test

  checkstyle-main:
    permissions: write-all
    name: Checkstyle Main
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/checkstyle-main

  checkstyle-test:
    permissions: write-all
    name: Checkstyle Test
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/checkstyle-test

  spotbugs-test:
    permissions: write-all
    name: Spotbugs Test
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/spotbugs-test

  spotbugs-main:
    permissions: write-all
    name: Spotbugs Main
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/spotbugs-main

  auto-approve:
    permissions: write-all
    name: Auto Approve
    runs-on: [cb-ubuntu22]
    if: github.actor == 'dependabot[bot]' || github.actor == 'cloudbreak-jenkins'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/auto-approve

  swagger-compatiblity:
    permissions: write-all
    name: Swagger Compatibility
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/swagger-compatiblity

  component-test:
    permissions: write-all
    name: Component Test
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/component-test

  config-change-integration-test:
    permissions: write-all
    name: Config Change Integration Test
    runs-on: [cb-ubuntu22]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/config-change-integration-test

  schema-compatibility-test:
    permissions: write-all
    name: Schema Compatibility Test
    runs-on: [cb-ubuntu22-large]
    timeout-minutes: 90
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/schema-compatibility-test

  integration-test:
    permissions: write-all
    name: Integration Test
    runs-on: [cb-ubuntu22-large]
    timeout-minutes: 90
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/integration-test

  fedramp-integration-test:
    permissions: write-all
    name: FedRAMP Integration Test
    runs-on: [cb-ubuntu22-large]
    timeout-minutes: 90
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/fedramp-integration-test

  real-ums-test:
    permissions: write-all
    name: Real UMS Test
    runs-on: [cb-ubuntu22-large]
    timeout-minutes: 90
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/real-ums-test

  aws-test:
    permissions: write-all
    name: Aws Test
    runs-on: [cb-ubuntu22-large]
    timeout-minutes: 90
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare
        uses: ./.github/actions/pull-request/base
      - name: execute
        uses: ./.github/actions/pull-request/aws-test
