#!/bin/bash
#
# Reject pushes that contain commits with messages that do not adhere
# to the defined regex.

# This can be a useful pre-receive hook [1] if you want to ensure every
# commit is associated with a ticket ID.
#
# As an example this hook ensures that the commit message contains a
# JIRA issue formatted as [JIRA-<issue number>].
#
# [1] https://help.github.com/en/enterprise/user/articles/working-with-pre-receive-hooks
#

set -e

msg_regex='^[a-z]+\-[0-9]+\s?|^Merge|^Bumps.*from|^Revert'

echo "[Starting] JIRA ID in commit message validation"

commits=$(git log HEAD --not --remotes --max-count=10 --pretty=format:%s)

while IFS=$'\n' read -r commitMessage
do
	if ! echo $commitMessage | grep -iqE "$msg_regex"; then
		echo "ERROR:"
		echo "ERROR: Invalid commit message. Your push was rejected because the commit message: -----> '$commitMessage'" >&2;
		echo "ERROR: Its missing the JIRA Issue. Please use the format'{JIRAPROJECT}-{TICKET_NUMBER} e.g: CB-12345 my commit message goes here." >&2;
		echo "ERROR: Please fix the commit message and push again."
		echo "ERROR: https://help.github.com/en/articles/changing-a-commit-message"
		echo "ERROR"
		exit 1
	fi
done <<< "$commits"

echo "[Finished] JIRA ID in commit message validation"
