// Code generated by go-swagger; DO NOT EDIT.

package database_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-redbeams/model"
)

// ListDatabaseServersReader is a Reader for the ListDatabaseServers structure.
type ListDatabaseServersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDatabaseServersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListDatabaseServersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListDatabaseServersOK creates a ListDatabaseServersOK with default headers values
func NewListDatabaseServersOK() *ListDatabaseServersOK {
	return &ListDatabaseServersOK{}
}

/*ListDatabaseServersOK handles this case with default header values.

successful operation
*/
type ListDatabaseServersOK struct {
	Payload *model.DatabaseServerV4Responses
}

func (o *ListDatabaseServersOK) Error() string {
	return fmt.Sprintf("[GET /v4/databaseservers][%d] listDatabaseServersOK  %+v", 200, o.Payload)
}

func (o *ListDatabaseServersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DatabaseServerV4Responses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
