-- // CLOUD-46697 Refactor platform parameters
-- Migration SQL that makes the change goes here.

ALTER TABLE cloudbreakevent ADD COLUMN availabilityZone text;
ALTER TABLE cloudbreakusage ADD COLUMN availabilityZone text;

update stack set region='us-central1', availabilityZone='us-central1-a' where region='US_CENTRAL1_A';
update cloudbreakevent set region='us-central1', availabilityZone='us-central1-a' where region='US_CENTRAL1_A';
update cloudbreakusage set region='us-central1', availabilityZone='us-central1-a' where region='US_CENTRAL1_A';
update stack set region='us-central1', availabilityZone='us-central1-b' where region='US_CENTRAL1_B';
update cloudbreakevent set region='us-central1', availabilityZone='us-central1-b' where region='US_CENTRAL1_B';
update cloudbreakusage set region='us-central1', availabilityZone='us-central1-b' where region='US_CENTRAL1_B';
update stack set region='us-central1', availabilityZone='us-central1-f' where region='US_CENTRAL1_F';
update cloudbreakevent set region='us-central1', availabilityZone='us-central1-f' where region='US_CENTRAL1_F';
update cloudbreakusage set region='us-central1', availabilityZone='us-central1-f' where region='US_CENTRAL1_F';
update stack set region='us-central1', availabilityZone='us-central1-c' where region='US_CENTRAL1_C';
update cloudbreakevent set region='us-central1', availabilityZone='us-central1-c' where region='US_CENTRAL1_C';
update cloudbreakusage set region='us-central1', availabilityZone='us-central1-c' where region='US_CENTRAL1_C';
update stack set region='europe-west1', availabilityZone='europe-west1-b' where region='EUROPE_WEST1_B';
update cloudbreakevent set region='europe-west1', availabilityZone='europe-west1-b' where region='EUROPE_WEST1_B';
update cloudbreakusage set region='europe-west1', availabilityZone='europe-west1-b' where region='EUROPE_WEST1_B';
update stack set region='europe-west1', availabilityZone='europe-west1-c' where region='EUROPE_WEST1_C';
update cloudbreakevent set region='europe-west1', availabilityZone='europe-west1-c' where region='EUROPE_WEST1_C';
update cloudbreakusage set region='europe-west1', availabilityZone='europe-west1-c' where region='EUROPE_WEST1_C';
update stack set region='europe-west1', availabilityZone='europe-west1-d' where region='EUROPE_WEST1_D';
update cloudbreakevent set region='europe-west1', availabilityZone='europe-west1-d' where region='EUROPE_WEST1_D';
update cloudbreakusage set region='europe-west1', availabilityZone='europe-west1-d' where region='EUROPE_WEST1_D';
update stack set region='asia-east1', availabilityZone='asia-east1-a' where region='ASIA_EAST1_A';
update cloudbreakevent set region='asia-east1', availabilityZone='asia-east1-a' where region='ASIA_EAST1_A';
update cloudbreakusage set region='asia-east1', availabilityZone='asia-east1-a' where region='ASIA_EAST1_A';
update stack set region='asia-east1', availabilityZone='asia-east1-b' where region='ASIA_EAST1_B';
update cloudbreakevent set region='asia-east1', availabilityZone='asia-east1-b' where region='ASIA_EAST1_B';
update cloudbreakusage set region='asia-east1', availabilityZone='asia-east1-b' where region='ASIA_EAST1_B';
update stack set region='asia-east1', availabilityZone='asia-east1-c' where region='ASIA_EAST1_C';
update cloudbreakevent set region='asia-east1', availabilityZone='asia-east1-c' where region='ASIA_EAST1_C';
update cloudbreakusage set region='asia-east1', availabilityZone='asia-east1-c' where region='ASIA_EAST1_C';
update stack set region='East Asia' where region='EAST_ASIA';
update cloudbreakevent set region='East Asia' where region='EAST_ASIA';
update cloudbreakusage set region='East Asia' where region='EAST_ASIA';
update stack set region='North Europe' where region='NORTH_EUROPE';
update cloudbreakevent set region='North Europe' where region='NORTH_EUROPE';
update cloudbreakusage set region='North Europe' where region='NORTH_EUROPE';
update stack set region='West Europe' where region='WEST_EUROPE';
update cloudbreakevent set region='West Europe' where region='WEST_EUROPE';
update cloudbreakusage set region='West Europe' where region='WEST_EUROPE';
update stack set region='East US' where region='EAST_US';
update cloudbreakevent set region='East US' where region='EAST_US';
update cloudbreakusage set region='East US' where region='EAST_US';
update stack set region='Central US' where region='CENTRAL_US';
update cloudbreakevent set region='Central US' where region='CENTRAL_US';
update cloudbreakusage set region='Central US' where region='CENTRAL_US';
update stack set region='South Central US' where region='SOUTH_CENTRAL_US';
update cloudbreakevent set region='South Central US' where region='SOUTH_CENTRAL_US';
update cloudbreakusage set region='South Central US' where region='SOUTH_CENTRAL_US';
update stack set region='North Central US' where region='NORTH_CENTRAL_US';
update cloudbreakevent set region='North Central US' where region='NORTH_CENTRAL_US';
update cloudbreakusage set region='North Central US' where region='NORTH_CENTRAL_US';
update stack set region='East US 2' where region='EAST_US_2';
update cloudbreakevent set region='East US 2' where region='EAST_US_2';
update cloudbreakusage set region='East US 2' where region='EAST_US_2';
update stack set region='West US' where region='WEST_US';
update cloudbreakevent set region='West US' where region='WEST_US';
update cloudbreakusage set region='West US' where region='WEST_US';
update stack set region='Japan East' where region='JAPAN_EAST';
update cloudbreakevent set region='Japan East' where region='JAPAN_EAST';
update cloudbreakusage set region='Japan East' where region='JAPAN_EAST';
update stack set region='Japan West' where region='JAPAN_WEST';
update cloudbreakevent set region='Japan West' where region='JAPAN_WEST';
update cloudbreakusage set region='Japan West' where region='JAPAN_WEST';
update stack set region='Southeast Asia' where region='SOUTHEAST_ASIA';
update cloudbreakevent set region='Southeast Asia' where region='SOUTHEAST_ASIA';
update cloudbreakusage set region='Southeast Asia' where region='SOUTHEAST_ASIA';
update stack set region='Brazil South' where region='BRAZIL_SOUTH';
update cloudbreakevent set region='Brazil South' where region='BRAZIL_SOUTH';
update cloudbreakusage set region='Brazil South' where region='BRAZIL_SOUTH';
update stack set region='us-gov-west-1' where region='GovCloud';
update cloudbreakevent set region='us-gov-west-1' where region='GovCloud';
update cloudbreakusage set region='us-gov-west-1' where region='GovCloud';
update stack set region='us-east-1' where region='US_EAST_1';
update cloudbreakevent set region='us-east-1' where region='US_EAST_1';
update cloudbreakusage set region='us-east-1' where region='US_EAST_1';
update stack set region='us-west-1' where region='US_WEST_1';
update cloudbreakevent set region='us-west-1' where region='US_WEST_1';
update cloudbreakusage set region='us-west-1' where region='US_WEST_1';
update stack set region='us-west-2' where region='US_WEST_2';
update cloudbreakevent set region='us-west-2' where region='US_WEST_2';
update cloudbreakusage set region='us-west-2' where region='US_WEST_2';
update stack set region='eu-west-1' where region='EU_WEST_1';
update cloudbreakevent set region='eu-west-1' where region='EU_WEST_1';
update cloudbreakusage set region='eu-west-1' where region='EU_WEST_1';
update stack set region='eu-central-1' where region='EU_CENTRAL_1';
update cloudbreakevent set region='eu-central-1' where region='EU_CENTRAL_1';
update cloudbreakusage set region='eu-central-1' where region='EU_CENTRAL_1';
update stack set region='ap-southeast-1' where region='AP_SOUTHEAST_1';
update cloudbreakevent set region='ap-southeast-1' where region='AP_SOUTHEAST_1';
update cloudbreakusage set region='ap-southeast-1' where region='AP_SOUTHEAST_1';
update stack set region='ap-southeast-2' where region='AP_SOUTHEAST_2';
update cloudbreakevent set region='ap-southeast-2' where region='AP_SOUTHEAST_2';
update cloudbreakusage set region='ap-southeast-2' where region='AP_SOUTHEAST_2';
update stack set region='ap-northeast-1' where region='AP_NORTHEAST_1';
update cloudbreakevent set region='ap-northeast-1' where region='AP_NORTHEAST_1';
update cloudbreakusage set region='ap-northeast-1' where region='AP_NORTHEAST_1';
update stack set region='sa-east-1' where region='SA_EAST_1';
update cloudbreakevent set region='sa-east-1' where region='SA_EAST_1';
update cloudbreakusage set region='sa-east-1' where region='SA_EAST_1';
update stack set region='cn-north-1' where region='CN_NORTH_1';
update cloudbreakevent set region='cn-north-1' where region='CN_NORTH_1';
update cloudbreakusage set region='cn-north-1' where region='CN_NORTH_1';
update stack set region='local', availabilityZone='local' where region='LOCAL';
update cloudbreakevent set region='local', availabilityZone='local' where region='LOCAL';
update cloudbreakusage set region='local', availabilityZone='local' where region='LOCAL';


-- //@UNDO
-- SQL to undo the change goes here.

ALTER TABLE cloudbreakevent DROP COLUMN availabilityZone;
ALTER TABLE cloudbreakusage DROP COLUMN availabilityZone;

update stack set region='US_CENTRAL1_A', availabilityZone='' where region='us-central1';
update cloudbreakevent set region='US_CENTRAL1_A' where region='us-central1';
update cloudbreakusage set region='US_CENTRAL1_A' where region='us-central1';
update stack set region='US_CENTRAL1_B', availabilityZone='' where region='us-central1';
update cloudbreakevent set region='US_CENTRAL1_B' where region='us-central1';
update cloudbreakusage set region='US_CENTRAL1_B' where region='us-central1';
update stack set region='US_CENTRAL1_F', availabilityZone='' where region='us-central1';
update cloudbreakevent set region='US_CENTRAL1_F' where region='us-central1';
update cloudbreakusage set region='US_CENTRAL1_F' where region='us-central1';
update stack set region='US_CENTRAL1_C', availabilityZone='' where region='us-central1';
update cloudbreakevent set region='US_CENTRAL1_C' where region='us-central1';
update cloudbreakusage set region='US_CENTRAL1_C' where region='us-central1';
update stack set region='EUROPE_WEST1_B', availabilityZone='' where region='europe-west1';
update cloudbreakevent set region='EUROPE_WEST1_B' where region='europe-west1';
update cloudbreakusage set region='EUROPE_WEST1_B' where region='europe-west1';
update stack set region='EUROPE_WEST1_C', availabilityZone='' where region='europe-west1';
update cloudbreakevent set region='EUROPE_WEST1_C' where region='europe-west1';
update cloudbreakusage set region='EUROPE_WEST1_C' where region='europe-west1';
update stack set region='EUROPE_WEST1_D', availabilityZone='' where region='europe-west1';
update cloudbreakevent set region='EUROPE_WEST1_D' where region='europe-west1';
update cloudbreakusage set region='EUROPE_WEST1_D' where region='europe-west1';
update stack set region='ASIA_EAST1_A', availabilityZone='' where region='asia-east1';
update cloudbreakevent set region='ASIA_EAST1_A' where region='asia-east1';
update cloudbreakusage set region='ASIA_EAST1_A' where region='asia-east1';
update stack set region='ASIA_EAST1_B', availabilityZone='' where region='asia-east1';
update cloudbreakevent set region='ASIA_EAST1_B' where region='asia-east1';
update cloudbreakusage set region='ASIA_EAST1_B' where region='asia-east1';
update stack set region='ASIA_EAST1_C', availabilityZone='' where region='asia-east1';
update cloudbreakevent set region='ASIA_EAST1_C' where region='asia-east1';
update cloudbreakusage set region='ASIA_EAST1_C' where region='asia-east1';
update stack set region='EAST_ASIA' where region='East Asia';
update cloudbreakevent set region='EAST_ASIA' where region='East Asia';
update cloudbreakusage set region='EAST_ASIA' where region='East Asia';
update stack set region='NORTH_EUROPE' where region='North Europe';
update cloudbreakevent set region='NORTH_EUROPE' where region='North Europe';
update cloudbreakusage set region='NORTH_EUROPE' where region='North Europe';
update stack set region='WEST_EUROPE' where region='West Europe';
update cloudbreakevent set region='WEST_EUROPE' where region='West Europe';
update cloudbreakusage set region='WEST_EUROPE' where region='West Europe';
update stack set region='EAST_US' where region='East US';
update cloudbreakevent set region='EAST_US' where region='East US';
update cloudbreakusage set region='EAST_US' where region='East US';
update stack set region='CENTRAL_US' where region='Central US';
update cloudbreakevent set region='CENTRAL_US' where region='Central US';
update cloudbreakusage set region='CENTRAL_US' where region='Central US';
update stack set region='SOUTH_CENTRAL_US' where region='South Central US';
update cloudbreakevent set region='SOUTH_CENTRAL_US' where region='South Central US';
update cloudbreakusage set region='SOUTH_CENTRAL_US' where region='South Central US';
update stack set region='NORTH_CENTRAL_US' where region='North Central US';
update cloudbreakevent set region='NORTH_CENTRAL_US' where region='North Central US';
update cloudbreakusage set region='NORTH_CENTRAL_US' where region='North Central US';
update stack set region='EAST_US_2' where region='East US 2';
update cloudbreakevent set region='EAST_US_2' where region='East US 2';
update cloudbreakusage set region='EAST_US_2' where region='East US 2';
update stack set region='WEST_US' where region='West US';
update cloudbreakevent set region='WEST_US' where region='West US';
update cloudbreakusage set region='WEST_US' where region='West US';
update stack set region='JAPAN_EAST' where region='Japan East';
update cloudbreakevent set region='JAPAN_EAST' where region='Japan East';
update cloudbreakusage set region='JAPAN_EAST' where region='Japan East';
update stack set region='JAPAN_WEST' where region='Japan West';
update cloudbreakevent set region='JAPAN_WEST' where region='Japan West';
update cloudbreakusage set region='JAPAN_WEST' where region='Japan West';
update stack set region='SOUTHEAST_ASIA' where region='Southeast Asia';
update cloudbreakevent set region='SOUTHEAST_ASIA' where region='Southeast Asia';
update cloudbreakusage set region='SOUTHEAST_ASIA' where region='Southeast Asia';
update stack set region='BRAZIL_SOUTH' where region='Brazil South';
update cloudbreakevent set region='BRAZIL_SOUTH' where region='Brazil South';
update cloudbreakusage set region='BRAZIL_SOUTH' where region='Brazil South';
update stack set region='GovCloud' where region='us-gov-west-1';
update cloudbreakevent set region='GovCloud' where region='us-gov-west-1';
update cloudbreakusage set region='GovCloud' where region='us-gov-west-1';
update stack set region='US_EAST_1' where region='us-east-1';
update cloudbreakevent set region='US_EAST_1' where region='us-east-1';
update cloudbreakusage set region='US_EAST_1' where region='us-east-1';
update stack set region='US_WEST_1' where region='us-west-1';
update cloudbreakevent set region='US_WEST_1' where region='us-west-1';
update cloudbreakusage set region='US_WEST_1' where region='us-west-1';
update stack set region='US_WEST_2' where region='us-west-2';
update cloudbreakevent set region='US_WEST_2' where region='us-west-2';
update cloudbreakusage set region='US_WEST_2' where region='us-west-2';
update stack set region='EU_WEST_1' where region='eu-west-1';
update cloudbreakevent set region='EU_WEST_1' where region='eu-west-1';
update cloudbreakusage set region='EU_WEST_1' where region='eu-west-1';
update stack set region='EU_CENTRAL_1' where region='eu-central-1';
update cloudbreakevent set region='EU_CENTRAL_1' where region='eu-central-1';
update cloudbreakusage set region='EU_CENTRAL_1' where region='eu-central-1';
update stack set region='AP_SOUTHEAST_1' where region='ap-southeast-1';
update cloudbreakevent set region='AP_SOUTHEAST_1' where region='ap-southeast-1';
update cloudbreakusage set region='AP_SOUTHEAST_1' where region='ap-southeast-1';
update stack set region='AP_SOUTHEAST_2' where region='ap-southeast-2';
update cloudbreakevent set region='AP_SOUTHEAST_2' where region='ap-southeast-2';
update cloudbreakusage set region='AP_SOUTHEAST_2' where region='ap-southeast-2';
update stack set region='AP_NORTHEAST_1' where region='ap-northeast-1';
update cloudbreakevent set region='AP_NORTHEAST_1' where region='ap-northeast-1';
update cloudbreakusage set region='AP_NORTHEAST_1' where region='ap-northeast-1';
update stack set region='SA_EAST_1' where region='sa-east-1';
update cloudbreakevent set region='SA_EAST_1' where region='sa-east-1';
update cloudbreakusage set region='SA_EAST_1' where region='sa-east-1';
update stack set region='CN_NORTH_1' where region='cn-north-1';
update cloudbreakevent set region='CN_NORTH_1' where region='cn-north-1';
update cloudbreakusage set region='CN_NORTH_1' where region='cn-north-1';
update stack set region='LOCAL', availabilityZone='' where region='local';
update cloudbreakevent set region='LOCAL' where region='local';
update cloudbreakusage set region='LOCAL' where region='local';