-- // CLOUD-47851 Refactor vm types
-- Migration SQL that makes the change goes here.

update template set instancetype = gcpinstancetype, gcpinstancetype = '' where gcpinstancetype <> '';
update template set instancetype = vmtype, vmtype = '' where vmtype <> '';

update template set instancetype='m3.medium' where instancetype='M3Medium' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='m3.medium' where instancetype='M3Medium' and provider='AWS';
update template set instancetype='m3.large' where instancetype='M3Large' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='m3.large' where instancetype='M3Large' and provider='AWS';
update template set instancetype='m3.xlarge' where instancetype='M3Xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='m3.xlarge' where instancetype='M3Xlarge' and provider='AWS';
update template set instancetype='m3.2xlarge' where instancetype='M32xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='m3.2xlarge' where instancetype='M32xlarge' and provider='AWS';
update template set instancetype='i2.xlarge' where instancetype='I2Xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='i2.xlarge' where instancetype='I2Xlarge' and provider='AWS';
update template set instancetype='i2.2xlarge' where instancetype='I22xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='i2.2xlarge' where instancetype='I22xlarge' and provider='AWS';
update template set instancetype='i2.4xlarge' where instancetype='I24xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='i2.4xlarge' where instancetype='I24xlarge' and provider='AWS';
update template set instancetype='i2.8xlarge' where instancetype='I28xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='i2.8xlarge' where instancetype='I28xlarge' and provider='AWS';
update template set instancetype='hi1.4xlarge' where instancetype='Hi14xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='hi1.4xlarge' where instancetype='Hi14xlarge' and provider='AWS';
update template set instancetype='hs1.8xlarge' where instancetype='Hs18xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='hs1.8xlarge' where instancetype='Hs18xlarge' and provider='AWS';
update template set instancetype='c3.large' where instancetype='C3Large' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='c3.large' where instancetype='C3Large' and provider='AWS';
update template set instancetype='c3.xlarge' where instancetype='C3Xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='c3.xlarge' where instancetype='C3Xlarge' and provider='AWS';
update template set instancetype='c3.2xlarge' where instancetype='C32xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='c3.2xlarge' where instancetype='C32xlarge' and provider='AWS';
update template set instancetype='c3.4xlarge' where instancetype='C34xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='c3.4xlarge' where instancetype='C34xlarge' and provider='AWS';
update template set instancetype='c3.8xlarge' where instancetype='C38xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='c3.8xlarge' where instancetype='C38xlarge' and provider='AWS';
update template set instancetype='cc2.8xlarge' where instancetype='Cc28xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='cc2.8xlarge' where instancetype='Cc28xlarge' and provider='AWS';
update template set instancetype='cg1.4xlarge' where instancetype='Cg14xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='cg1.4xlarge' where instancetype='Cg14xlarge' and provider='AWS';
update template set instancetype='cr1.8xlarge' where instancetype='Cr18xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='cr1.8xlarge' where instancetype='Cr18xlarge' and provider='AWS';
update template set instancetype='g2.2xlarge' where instancetype='G22xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='g2.2xlarge' where instancetype='G22xlarge' and provider='AWS';
update template set instancetype='r3.large' where instancetype='R3Large' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='r3.large' where instancetype='R3Large' and provider='AWS';
update template set instancetype='r3.xlarge' where instancetype='R3Xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='r3.xlarge' where instancetype='R3Xlarge' and provider='AWS';
update template set instancetype='r3.2xlarge' where instancetype='R32xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='r3.2xlarge' where instancetype='R32xlarge' and provider='AWS';
update template set instancetype='r3.4xlarge' where instancetype='R34xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='r3.4xlarge' where instancetype='R34xlarge' and provider='AWS';
update template set instancetype='r3.8xlarge' where instancetype='R38xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='r3.8xlarge' where instancetype='R38xlarge' and provider='AWS';
update template set instancetype='d2.xlarge' where instancetype='D2Xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='d2.xlarge' where instancetype='D2Xlarge' and provider='AWS';
update template set instancetype='d2.2xlarge' where instancetype='D22xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='d2.2xlarge' where instancetype='D22xlarge' and provider='AWS';
update template set instancetype='d2.4xlarge' where instancetype='D24xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='d2.4xlarge' where instancetype='D24xlarge' and provider='AWS';
update template set instancetype='d2.8xlarge' where instancetype='D28xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='d2.8xlarge' where instancetype='D28xlarge' and provider='AWS';
update template set instancetype='n1-standard-1' where instancetype='N1_STANDARD_1' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-standard-1' where instancetype='N1_STANDARD_1' and provider='GCP';
update template set instancetype='n1-standard-2' where instancetype='N1_STANDARD_2' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-standard-2' where instancetype='N1_STANDARD_2' and provider='GCP';
update template set instancetype='n1-standard-4' where instancetype='N1_STANDARD_4' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-standard-4' where instancetype='N1_STANDARD_4' and provider='GCP';
update template set instancetype='n1-standard-8' where instancetype='N1_STANDARD_8' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-standard-8' where instancetype='N1_STANDARD_8' and provider='GCP';
update template set instancetype='n1-standard-16' where instancetype='N1_STANDARD_16' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-standard-16' where instancetype='N1_STANDARD_16' and provider='GCP';
update template set instancetype='n1-highmem-2' where instancetype='N1_HIGHMEM_2' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highmem-2' where instancetype='N1_HIGHMEM_2' and provider='GCP';
update template set instancetype='n1-highmem-4' where instancetype='N1_HIGHMEM_4' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highmem-4' where instancetype='N1_HIGHMEM_4' and provider='GCP';
update template set instancetype='n1-highmem-8' where instancetype='N1_HIGHMEM_8' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highmem-8' where instancetype='N1_HIGHMEM_8' and provider='GCP';
update template set instancetype='n1-highmem-16' where instancetype='N1_HIGHMEM_16' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highmem-16' where instancetype='N1_HIGHMEM_16' and provider='GCP';
update template set instancetype='n1-highcpu-2' where instancetype='N1_HIGHCPU_2' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highcpu-2' where instancetype='N1_HIGHCPU_2' and provider='GCP';
update template set instancetype='n1-highcpu-4' where instancetype='N1_HIGHCPU_4' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highcpu-4' where instancetype='N1_HIGHCPU_4' and provider='GCP';
update template set instancetype='n1-highcpu-8' where instancetype='N1_HIGHCPU_8' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highcpu-8' where instancetype='N1_HIGHCPU_8' and provider='GCP';
update template set instancetype='n1-highcpu-16' where instancetype='N1_HIGHCPU_16' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='n1-highcpu-16' where instancetype='N1_HIGHCPU_16' and provider='GCP';
update template set instancetype='f1-micro' where instancetype='F1_MICRO' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='f1-micro' where instancetype='F1_MICRO' and provider='GCP';
update template set instancetype='g1-small' where instancetype='G1_SMALL' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='g1-small' where instancetype='G1_SMALL' and provider='GCP';
update template set instancetype='Standard_A5' where instancetype='A5' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A5' where instancetype='A5' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_A6' where instancetype='A6' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A6' where instancetype='A6' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_A7' where instancetype='A7' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A7' where instancetype='A7' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_A8' where instancetype='A8' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A8' where instancetype='A8' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_A9' where instancetype='A9' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A9' where instancetype='A9' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_A10' where instancetype='A10' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A10' where instancetype='A10' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_A11' where instancetype='A11' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_A11' where instancetype='A11' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_G1' where instancetype='STANDARD_G1' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_G1' where instancetype='STANDARD_G1' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_G2' where instancetype='STANDARD_G2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_G2' where instancetype='STANDARD_G2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_G3' where instancetype='STANDARD_G3' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_G3' where instancetype='STANDARD_G3' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_G4' where instancetype='STANDARD_G4' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_G4' where instancetype='STANDARD_G4' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_G5' where instancetype='STANDARD_G5' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_G5' where instancetype='STANDARD_G5' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D1' where instancetype='STANDARD_D1' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D1' where instancetype='STANDARD_D1' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D2' where instancetype='STANDARD_D2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D2' where instancetype='STANDARD_D2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D3' where instancetype='STANDARD_D3' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D3' where instancetype='STANDARD_D3' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D4' where instancetype='STANDARD_D4' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D4' where instancetype='STANDARD_D4' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D11' where instancetype='STANDARD_D11' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D11' where instancetype='STANDARD_D11' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D12' where instancetype='STANDARD_D12' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D12' where instancetype='STANDARD_D12' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D13' where instancetype='STANDARD_D13' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D13' where instancetype='STANDARD_D13' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D14' where instancetype='STANDARD_D14' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D14' where instancetype='STANDARD_D14' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D1_v2' where instancetype='STANDARD_D1_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D1_v2' where instancetype='STANDARD_D1_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D2_v2' where instancetype='STANDARD_D2_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D2_v2' where instancetype='STANDARD_D2_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D3_v2' where instancetype='STANDARD_D3_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D3_v2' where instancetype='STANDARD_D3_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D4_v2' where instancetype='STANDARD_D4_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D4_v2' where instancetype='STANDARD_D4_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D5_v2' where instancetype='STANDARD_D5_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D5_v2' where instancetype='STANDARD_D5_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D11_v2' where instancetype='STANDARD_D11_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D11_v2' where instancetype='STANDARD_D11_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D12_v2' where instancetype='STANDARD_D12_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D12_v2' where instancetype='STANDARD_D12_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D13_v2' where instancetype='STANDARD_D13_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D13_v2' where instancetype='STANDARD_D13_V2' and (provider='AZURE_RM' or provider='AZURE');
update template set instancetype='Standard_D14_v2' where instancetype='STANDARD_D14_V2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='Standard_D14_v2' where instancetype='STANDARD_D14_V2' and (provider='AZURE_RM' or provider='AZURE');

ALTER TABLE template DROP COLUMN gcpinstancetype;
ALTER TABLE template DROP COLUMN vmtype;

-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE template ADD COLUMN gcpinstancetype varchar (255);
ALTER TABLE template ADD COLUMN vmtype varchar (255);

update template set instancetype='M3Medium' where instancetype='m3.medium' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='M3Medium' where instancetype='m3.medium' and provider='AWS';
update template set instancetype='M3Large' where instancetype='m3.large' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='M3Large' where instancetype='m3.large' and provider='AWS';
update template set instancetype='M3Xlarge' where instancetype='m3.xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='M3Xlarge' where instancetype='m3.xlarge' and provider='AWS';
update template set instancetype='M32xlarge' where instancetype='m3.2xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='M32xlarge' where instancetype='m3.2xlarge' and provider='AWS';
update template set instancetype='I2Xlarge' where instancetype='i2.xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='I2Xlarge' where instancetype='i2.xlarge' and provider='AWS';
update template set instancetype='I22xlarge' where instancetype='i2.2xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='I22xlarge' where instancetype='i2.2xlarge' and provider='AWS';
update template set instancetype='I24xlarge' where instancetype='i2.4xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='I24xlarge' where instancetype='i2.4xlarge' and provider='AWS';
update template set instancetype='I28xlarge' where instancetype='i2.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='I28xlarge' where instancetype='i2.8xlarge' and provider='AWS';
update template set instancetype='Hi14xlarge' where instancetype='hi1.4xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='Hi14xlarge' where instancetype='hi1.4xlarge' and provider='AWS';
update template set instancetype='Hs18xlarge' where instancetype='hs1.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='Hs18xlarge' where instancetype='hs1.8xlarge' and provider='AWS';
update template set instancetype='C3Large' where instancetype='c3.large' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='C3Large' where instancetype='c3.large' and provider='AWS';
update template set instancetype='C3Xlarge' where instancetype='c3.xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='C3Xlarge' where instancetype='c3.xlarge' and provider='AWS';
update template set instancetype='C32xlarge' where instancetype='c3.2xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='C32xlarge' where instancetype='c3.2xlarge' and provider='AWS';
update template set instancetype='C34xlarge' where instancetype='c3.4xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='C34xlarge' where instancetype='c3.4xlarge' and provider='AWS';
update template set instancetype='C38xlarge' where instancetype='c3.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='C38xlarge' where instancetype='c3.8xlarge' and provider='AWS';
update template set instancetype='Cc28xlarge' where instancetype='cc2.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='Cc28xlarge' where instancetype='cc2.8xlarge' and provider='AWS';
update template set instancetype='Cg14xlarge' where instancetype='cg1.4xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='Cg14xlarge' where instancetype='cg1.4xlarge' and provider='AWS';
update template set instancetype='Cr18xlarge' where instancetype='cr1.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='Cr18xlarge' where instancetype='cr1.8xlarge' and provider='AWS';
update template set instancetype='G22xlarge' where instancetype='g2.2xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='G22xlarge' where instancetype='g2.2xlarge' and provider='AWS';
update template set instancetype='R3Large' where instancetype='r3.large' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='R3Large' where instancetype='r3.large' and provider='AWS';
update template set instancetype='R3Xlarge' where instancetype='r3.xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='R3Xlarge' where instancetype='r3.xlarge' and provider='AWS';
update template set instancetype='R32xlarge' where instancetype='r3.2xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='R32xlarge' where instancetype='r3.2xlarge' and provider='AWS';
update template set instancetype='R34xlarge' where instancetype='r3.4xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='R34xlarge' where instancetype='r3.4xlarge' and provider='AWS';
update template set instancetype='R38xlarge' where instancetype='r3.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='R38xlarge' where instancetype='r3.8xlarge' and provider='AWS';
update template set instancetype='D2Xlarge' where instancetype='d2.xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='D2Xlarge' where instancetype='d2.xlarge' and provider='AWS';
update template set instancetype='D22xlarge' where instancetype='d2.2xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='D22xlarge' where instancetype='d2.2xlarge' and provider='AWS';
update template set instancetype='D24xlarge' where instancetype='d2.4xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='D24xlarge' where instancetype='d2.4xlarge' and provider='AWS';
update template set instancetype='D28xlarge' where instancetype='d2.8xlarge' and dtype='AwsTemplate';
update cloudbreakusage set instancetype='D28xlarge' where instancetype='d2.8xlarge' and provider='AWS';
update template set gcpinstancetype='N1_STANDARD_1', instancetype='' where instancetype='n1-standard-1' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_STANDARD_1' where instancetype='n1-standard-1' and provider='GCP';
update template set gcpinstancetype='N1_STANDARD_2', instancetype='' where instancetype='n1-standard-2' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_STANDARD_2' where instancetype='n1-standard-2' and provider='GCP';
update template set gcpinstancetype='N1_STANDARD_4', instancetype='' where instancetype='n1-standard-4' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_STANDARD_4' where instancetype='n1-standard-4' and provider='GCP';
update template set gcpinstancetype='N1_STANDARD_8', instancetype='' where instancetype='n1-standard-8' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_STANDARD_8' where instancetype='n1-standard-8' and provider='GCP';
update template set gcpinstancetype='N1_STANDARD_16', instancetype='' where instancetype='n1-standard-16' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_STANDARD_16' where instancetype='n1-standard-16' and provider='GCP';
update template set gcpinstancetype='N1_HIGHMEM_2', instancetype='' where instancetype='n1-highmem-2' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHMEM_2' where instancetype='n1-highmem-2' and provider='GCP';
update template set gcpinstancetype='N1_HIGHMEM_4', instancetype='' where instancetype='n1-highmem-4' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHMEM_4' where instancetype='n1-highmem-4' and provider='GCP';
update template set gcpinstancetype='N1_HIGHMEM_8', instancetype='' where instancetype='n1-highmem-8' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHMEM_8' where instancetype='n1-highmem-8' and provider='GCP';
update template set gcpinstancetype='N1_HIGHMEM_16', instancetype='' where instancetype='n1-highmem-16' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHMEM_16' where instancetype='n1-highmem-16' and provider='GCP';
update template set gcpinstancetype='N1_HIGHCPU_2', instancetype='' where instancetype='n1-highcpu-2' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHCPU_2' where instancetype='n1-highcpu-2' and provider='GCP';
update template set gcpinstancetype='N1_HIGHCPU_4', instancetype='' where instancetype='n1-highcpu-4' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHCPU_4' where instancetype='n1-highcpu-4' and provider='GCP';
update template set gcpinstancetype='N1_HIGHCPU_8', instancetype='' where instancetype='n1-highcpu-8' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHCPU_8' where instancetype='n1-highcpu-8' and provider='GCP';
update template set gcpinstancetype='N1_HIGHCPU_16', instancetype='' where instancetype='n1-highcpu-16' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='N1_HIGHCPU_16' where instancetype='n1-highcpu-16' and provider='GCP';
update template set gcpinstancetype='F1_MICRO', instancetype='' where instancetype='f1-micro' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='F1_MICRO' where instancetype='f1-micro' and provider='GCP';
update template set gcpinstancetype='G1_SMALL', instancetype='' where instancetype='g1-small' and dtype='GcpTemplate';
update cloudbreakusage set instancetype='G1_SMALL' where instancetype='g1-small' and provider='GCP';
update template set vmtype='A5', instancetype='' where instancetype='Standard_A5' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A5' where instancetype='Standard_A5' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='A6', instancetype='' where instancetype='Standard_A6' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A6' where instancetype='Standard_A6' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='A7', instancetype='' where instancetype='Standard_A7' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A7' where instancetype='Standard_A7' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='A8', instancetype='' where instancetype='Standard_A8' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A8' where instancetype='Standard_A8' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='A9', instancetype='' where instancetype='Standard_A9' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A9' where instancetype='Standard_A9' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='A10', instancetype='' where instancetype='Standard_A10' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A10' where instancetype='Standard_A10' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='A11', instancetype='' where instancetype='Standard_A11' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='A11' where instancetype='Standard_A11' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_G1', instancetype='' where instancetype='Standard_G1' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_G1' where instancetype='Standard_G1' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_G2', instancetype='' where instancetype='Standard_G2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_G2' where instancetype='Standard_G2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_G3', instancetype='' where instancetype='Standard_G3' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_G3' where instancetype='Standard_G3' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_G4', instancetype='' where instancetype='Standard_G4' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_G4' where instancetype='Standard_G4' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_G5', instancetype='' where instancetype='Standard_G5' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_G5' where instancetype='Standard_G5' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D1', instancetype='' where instancetype='Standard_D1' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D1' where instancetype='Standard_D1' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D2', instancetype='' where instancetype='Standard_D2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D2' where instancetype='Standard_D2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D3', instancetype='' where instancetype='Standard_D3' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D3' where instancetype='Standard_D3' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D4', instancetype='' where instancetype='Standard_D4' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D4' where instancetype='Standard_D4' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D11', instancetype='' where instancetype='Standard_D11' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D11' where instancetype='Standard_D11' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D12', instancetype='' where instancetype='Standard_D12' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D12' where instancetype='Standard_D12' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D13', instancetype='' where instancetype='Standard_D13' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D13' where instancetype='Standard_D13' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D14', instancetype='' where instancetype='Standard_D14' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D14' where instancetype='Standard_D14' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D1_V2', instancetype='' where instancetype='Standard_D1_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D1_V2' where instancetype='Standard_D1_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D2_V2', instancetype='' where instancetype='Standard_D2_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D2_V2' where instancetype='Standard_D2_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D3_V2', instancetype='' where instancetype='Standard_D3_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D3_V2' where instancetype='Standard_D3_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D4_V2', instancetype='' where instancetype='Standard_D4_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D4_V2' where instancetype='Standard_D4_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D5_V2', instancetype='' where instancetype='Standard_D5_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D5_V2' where instancetype='Standard_D5_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D11_V2', instancetype='' where instancetype='Standard_D11_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D11_V2' where instancetype='Standard_D11_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D12_V2', instancetype='' where instancetype='Standard_D12_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D12_V2' where instancetype='Standard_D12_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D13_V2', instancetype='' where instancetype='Standard_D13_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D13_V2' where instancetype='Standard_D13_v2' and (provider='AZURE' or provider='AZURE_RM');
update template set vmtype='STANDARD_D14_V2', instancetype='' where instancetype='Standard_D14_v2' and dtype='AzureTemplate';
update cloudbreakusage set instancetype='STANDARD_D14_V2' where instancetype='Standard_D14_v2' and (provider='AZURE' or provider='AZURE_RM');

