package com.sequenceiq.datalake.entity;

public enum SdxClusterStatus {
    REQUESTED,
    STACK_CREATION_IN_PROGRESS,
    STACK_DELETED,
    STACK_DELETION_IN_PROGRESS,
    EXTERNAL_DATABASE_CREATION_IN_PROGRESS,
    EXTERNAL_DATABASE_DELETION_IN_PROGRESS,
    RUNNING,
    PROVISIONING_FAILED,
    DELETE_REQUESTED,
    DELETED,
    DELETE_FAILED
}
